### PR TITLE
fix(tailwind): correct disabled tag styles

### LINKED ISSUE #7245: TagGroup does not apply disabled styles in tailwind starter
### Provide a general summary of the issue here

The compound variants are missing the isDisabled property so they are not evaluated when the component styles are computed.

### 🤔 Expected Behavior?

disabled tags should have a diffefent style

### 😯 Current Behavior

the isDisabled prop does not affect the component styling

### 💁 Possible Solution

add isDisabled: false to the compoundVariant object creation

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

View the storybook story for tag group and update one tag to be disabled.

### Version

latest

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

macOS

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by steveoh**
this allows the styles defined in isDisabled to be applied

Closes #7245

## ✅ Pull Request Checklist:

- [x] Included link to corresponding 
   - https://github.com/adobe/react-spectrum/issues/7245
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [x] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

## 📝 Test Instructions:

View the TagGroup story for the tailwind starter project

## 🧢 Your Project:

refs #7246

### CODE REVIEW

**Comment by steveoh** [comment]
Ok, I added that class.

**Review by snowystinger — DISMISSED** [review]

**Comment by steveoh** [comment]
Do I need to do anything for the 1 waiting workflow, branch is out of date and the 1 more approver requirement? 

I can certainly rebase main but that might make your approval reset.

**Comment by snowystinger** [comment]
I'm not sure what's up with the waiting workflow, for now don't worry about it.
One more reviewer is required, but that should be it for now

**Comment by steveoh** [comment]
Ok thanks. Are the other reviewers aware or how does that work?

**Comment by snowystinger** [comment]
yes, someone will review it when they have time. if it becomes more than a week, feel free to ping again

**Comment by steveoh** [comment]
I think I fixed the pr title to pass your linting but i'm not sure about what scope to use for this.

**Review by reidbarber — CHANGES_REQUESTED** [review]
Thanks for the PR!

The light mode styles look good, but I think the dark mode styles should retain the background, otherwise it looks like it is selected:

Screenshot 2024-10-28 at 12 49 21 PM

**Comment by steveoh** [comment]
Since my PR was specific to getting the existing disabled styles applied to the tags, would you two mind sorting out these stylistic choices?

I'm happy to throw darts at the style board but it's a little outside of my wheelhouse.

**Comment by steveoh** [comment]
I added some styles to make it look like the tabs but again, I'm not sure what you really want.

**Comment by yihuiliao** [comment]
> I think I fixed the pr title to pass your linting but i'm not sure about what scope to use for this.

No worries about the scope since it's optional. I think tailwind is fine!

**Comment by steveoh** [comment]
@snowystinger it looks like we need your reapproval.

**Review by snowystinger — APPROVED** [review]

**Pull request merged**
