### PR TITLE
Fix tooling on Windows

### PR DESCRIPTION
**Pull request by mischnic**
Closes https://github.com/adobe/react-spectrum/issues/796

### Todo

- [x] Write a script that does the same as `yarn icons` but only builds changed files (like make does)
	- [x] It currently does the same as the Makefile did, but it probably makes more sense to compare `@adobe/react-spectrum-ui/dist/*.js` and `packages/spectrum-icons/ui/*.js` and run `yarn make-icons && yarn build-icons` if changed
	- [x] Test that script on Windows again

### CODE REVIEW

**Comment by snowystinger** [comment]
This PR has a little bit of tweaking to move/rename some of those commands as well. We don't have to use it, but figured I'd give you the heads up

**Comment by mischnic** [comment]
Was `This PR` supposed to be a link? Or do you mean that I should leave the makefile as is?

**Comment by snowystinger** [comment]
yep, was definitely meant to have a link, went too fast, sorry about that

**Comment by devongovett** [comment]
@sanskar-p does this fix the issue for you?

**Comment by sanskar-p** [comment]
> @sanskar-p does this fix the issue for you?

The storybook still does not display properly for me @devongovett

**Comment by mischnic** [comment]
I've just tested it again by running
```
git reset --hard origin/build-windows
git clean -fdx
yarn
yarn start
```
and the styling in the storybook is correct for me

**Comment by sanskar-p** [comment]
@mischnic there must be something wrong with my system as the storybook styling is still not correct.
Is it fine if you reassign the task to somebody else? I will install Linux on my system and work on different tasks.
Extremely sorry for the inconvenience caused.

**Pull request merged**
