### PR TITLE
Fix combobox no label width

### PR DESCRIPTION
**Pull request by snowystinger**
Closes 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Review by ktabors — COMMENTED** [review]
Can you run chromatic on this?
The change looked good in the table stories, but I want chromatic to tell me if anything else changed. :)

**Review by devongovett — APPROVED** [review]
Seems ok? I don't quite understand the changes though

**Comment by snowystinger** [comment]
Yep, I'll run chromatic on this after a couple others go through, specifically https://github.com/adobe/react-spectrum/pull/2176

**Comment by snowystinger** [comment]
Closing, this is the wrong approach, but making an issue to address the default width of ComboBox

**Pull request closed without merging**
