### PR TITLE
Improve small DragPreview offset fallback, from center to proportional

### PR DESCRIPTION
**Pull request by AlexGalays**
See [Discussion](https://github.com/adobe/react-spectrum/discussions/4801)

Added `Math.floor` as i'm not sure whether all browsers nicely handle floats here. Also Math.floor ensures we're on the safe side (inside the drag preview)

## ✅ Pull Request Checklist:

- Quick change.
- Updated the test.
- Couldn't find a mention of this specific corner case in the documentation.

Before this change:

image

After this change:

image

### CODE REVIEW

**Comment by reidbarber** [comment]
GET_BUILD

**Review by reidbarber — APPROVED** [review]
LGTM, thanks for the improvement!

**Review by snowystinger — COMMENTED** [review]
I noticed that dragging from different positions in table rows could yield unexpected positions. For instance, dragging on "Lexy" was much further right than I expected.
https://reactspectrum.blob.core.windows.net/reactspectrum/151ffcdeb9a82ba166f64013eedbe4230f56c8e1/storybook/index.html?path=/story/tableview-drag-and-drop--custom-drag-preview&providerSwitcher-express=false

In general, though, I like the direction of this change.

**Comment by snowystinger** [comment]
Closing this one as it should be addressed by https://github.com/adobe/react-spectrum/issues/5409

**Pull request closed without merging**
