### PR TITLE
Expose focusPage from useCalendarState

### LINKED ISSUE #2627: Expose setStartDate in useCalendarState
# 🙋 Feature Request

I wish to be able to set the start date in CalendarState/RangeCalendarState.
## 🤔 Expected Behavior

I can use setStartDate method in CalendarState from outside the hook.
## 😯 Current Behavior

The setStartDate method is not exposed.
## 💁 Possible Solution

Expose the setStartDate method from useCalendarState.
## 🔦 Context

I have created my own calendar component for an UI library, and i wish to be able to select a different year by clicking on the current year. To do this, i need to be able to set the start date from outside the useCalendarState hook.
## 💻 Examples

Calendar view

Calendar year picker

### PR DESCRIPTION
**Pull request by datagutt**
Closes #2627

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

1. Attempt to use state.focusPage from a component, to focus on a particular date (different month, year).
2. Verify that the focused date changes.

### CODE REVIEW

**Comment by datagutt** [comment]
I don't think i need storybook-changes for this, since it is a hook-level change. It does also not affect any actual functionality, so do i need unit tests for this? setStartDate is already used inside the hook 😄

**Comment by devongovett** [comment]
I think you should probably use some of the other methods to change the focused date. Only setting the `startDate` would mean that no cell would be focused which would cause accessibility problems. You probably want to set the focused date, which will cause the start date to change as well. Perhaps the `setFocusedDate` method could be used instead? I think maybe it needs to change to call `focusCell` instead though, which is what changes the `startDate` accordingly.

**Comment by datagutt** [comment]
Yeah, i did look at setFocusedDate but could not get it working. So you are probably right in that it needs to be changed to call ``focusCell``.

**Comment by datagutt** [comment]
Is this implementation more suitable? I took inspiration from the `focusNextPage` and `focusPrevPage` methods, and figured a `focusPage`-method would fit with the current API.
With this, i can do this to go to a particular month or year:
`state.focusPage(state.focusedDate.set({ month: 1, year: 2011 })`

**Comment by datagutt** [comment]
@devongovett Hey, any update on a solution for this?

**Comment by devongovett** [comment]
Hey, sorry for the slow reply. I'd prefer if we could change the `setFocusedDate` method to call `focusCell` internally, but it would require some testing to ensure it doesn't break anything. I can try that in the new year, or feel free to try it yourself if you like!

**Comment by datagutt** [comment]
Looking forward to seeing something in the new year then :)
Happy holidays!

**Pull request closed without merging**
