### PR TITLE
Support fragments in collections

### PR DESCRIPTION
**Pull request by solimant**
Closes 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

### CODE REVIEW

**Review by snowystinger — COMMENTED** [review]
Thanks for the PR, we'll need tests for this.
Something to look out for is caching of entire children of the fragment when they would each be individually cached if not in a fragment.
Another is making sure that mixed structures like these work
```
<Parent>
  <Item></Item>
  <>
    <Item></Item>
  </>
</Parent>

<Parent>
  <>
    <Item></Item>
    <Item></Item>
  </>
</Parent>
```

**Comment by solimant** [comment]
@snowystinger - Rob, thank you for the review, and sorry for the delay in addressing the feedback. I've included tests, and revised the implementation a little which I think should address the use of the cache. Happy to address any further feedback.

**Review by snowystinger — APPROVED** [review]

**Comment by snowystinger** [comment]
No worries, this looks reasonable. We'll get someone else to review it after our next release. Hopefully next week. Thanks @solimant !

**Review by reidbarber — APPROVED** [review]
LGTM

**Pull request merged**
