### PR TITLE
Handle virtual click from html label elements in firefox

### LINKED ISSUE #3613: Labels for buttons not triggering click events with `onPress` on Firefox
# 🐛 Bug Report 

On firefox, there seems to be a problem when a label is associated with a sibling `button` that uses `onPress`. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#try_it) we should expect that, 
> When a user clicks or touches/taps a label, the browser passes the focus to its associated input (the resulting event is also raised for the input). That increased hit area for focusing the input provides an advantage to anyone trying to activate it — including those using a touch-screen device.

## 🤔 Expected Behavior

The behaviour should be the same as when I use `onClick`, for the click on the label to be sent to the button and initiate an alert (see codesandbox)

## 😯 Current Behavior

on Firefox, clicking the label simply triggers the hover state of the button but does not click.

## 💁 Possible Solution

This is purely an issue with `onPress` not catching the event that the browser is passing, `onClick` works as intended on all browsers. My rough solution was to simply honor an associated labels click event seen here 
https://github.com/adobe/react-spectrum/pull/3614

## 🔦 Context

I expect that the solution should work the same across browsers. Currently this presents a trade-off for me. So either

A. I use `onClick` instead of `onPress`, and sacrifice all the benefits of `onPress` such as keyboard navigation etc
or
B. I use `onPress` and accept that firefox users clicking labels will have a sub-optimal experience.

## 💻 Code Sample

https://codesandbox.io/s/react-aria-firefox-label-issue-8hj39z?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-aria   | 3.2.0
| Browser          | Firefox
| Operating System | Mac OS Monterey 12.0.1

### PR DESCRIPTION
**Pull request by wahidshafique**
The mozInputSource on ff is 1 when a label associated with a button is fired; might as well handle that as a click since otherwise it does not register at all

Closes #3613

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [x] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Compare the relevant storybook example on firefox

http://localhost:9003/?path=/story/button--button-with-associated-external-label&providerSwitcher-toastPosition=bottom

with the live buggy example here:

https://codesandbox.io/s/react-aria-firefox-label-issue-8hj39z?file=/src/App.js

On the storybook page you should be seeing the virtual event firing successfully from the label itself

### CODE REVIEW

**Comment by devongovett** [comment]
The point of this code is to detect a screen reader click. We don't want to detect mouse clicks here.

**Comment by wahidshafique** [comment]
env


So I tested it out here with my instructions on ff in windows 10 pro

Here is me testing this PR: https://youtu.be/iy_W0KlwpGo

Here is me testing the prod behaviour: https://youtu.be/iy_W0KlwpGo

I currently do not have access to JAWS.

To @devongovett from my view its just looking for a specific `mozInputSource` which already guards it from affecting other functionality. As for if we don't want to detect mouse clicks, I guess its still _technically_ a virtual click as the initiator is a label. In fact from testing the two do not overlap.

**Comment by snowystinger** [comment]
Hey, so I meant tested in other places. As Devon said, this code is looking to detect a screen reader click. Virtual meaning virtual cursor, not virtual click. I think we'll need to find another way to handle this.

**Comment by wahidshafique** [comment]
> Hey, so I meant tested in other places. As Devon said, this code is looking to detect a screen reader click. Virtual meaning virtual cursor, not virtual click. I think we'll need to find another way to handle this.

@snowystinger I see exactly what you mean, this change is a tad more universal than simply being about buttons and labels. I will poke around to see if there is a more localized/stable way of addressing this, and welcome any feedback or ideas you might have

**Comment by wahidshafique** [comment]
@snowystinger  @devongovett 

Okay, new strategy, brings down scope of change to just `usePress`.

db782fd12acc5c8506fff85c6ef9469c81ea669e

Since we are talking about `labels`, I use the mozilla specific prop `explicitOriginalTarget`, as per the [docs](https://developer.mozilla.org/en-US/docs/Web/API/Event/explicitOriginalTarget)
> For example, mouse events are retargeted to their parent node when they happen over text nodes (see [bug 185889](https://bugzilla.mozilla.org/show_bug.cgi?id=185889)), and in that case [currentTarget](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget) will show the parent while this property will show the text node.

After that I grab the `explicitOriginalTarget` `control` property, which is [unique](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabelElement/control) to a `label`, and to be sure, I check if the control matches with our button element.

**Review by snowystinger — COMMENTED** [review]
This matches the behavior I see already existing in Chrome and Safari

**Review by snowystinger — APPROVED** [review]

**Comment by snowystinger** [comment]
closing for reason in https://github.com/adobe/react-spectrum/issues/3613

**Pull request closed without merging**
