### PR TITLE
Upgrade parcel to v2.8.0

### PR DESCRIPTION
**Pull request by devongovett**

### CODE REVIEW

**Comment by snowystinger** [comment]
> ## API Changes
> unknown top level export { type: 'identifier', name: 'Column' } unknown top level export { type: 'identifier', name: 'Column' }

I believe the solution to this is in DocsTransformer line 108
```
-return processExport(path.get('expression'), node);
+return processExport(path.get('type'), node);
```

but I was having some trouble with it in another PR where it stopped showing the export for Button. something I wanted to consult with you on once release was done.

**Review by snowystinger — DISMISSED** [review]
spot checked docs Props tables and function signatures, looks good
docs built, looks good
storybook, looks good
ran locally, looks good

There are some new warnings when I run it locally
@parcel/resolver-default: Could not resolve package "assert" that satisfies ^2.0.0. Found 1.5.0.

**Review by LFDanLu — COMMENTED** [review]
I'm seeing some jank in some of the input field focus rings in the built/local storybook/docs:
(combobox)
image
(colorfield)
image
Running chromatic now

**Comment by devongovett** [comment]
I believe the remaining Chromatic changes match the changes currently on main (from [this build](https://www.chromatic.com/build?appId=5f0dd5ad2b5fc10022a2e320&number=421))

**Review by snowystinger — APPROVED** [review]

**Review by reidbarber — APPROVED** [review]

**Pull request merged**
