### PR TITLE
fix(#5691): [WHCM] ActionButton restore border for isQuiet and isQuiet + isDisabled states

### LINKED ISSUE #5691: [Windows High contrast Mode] Border is getting drawn around quiet button in disabled state
### Provide a general summary of the issue here

[Windows High contrast Mode] Border is getting drawn around quiet button in disabled state

### 🤔 Expected Behavior?

Border should not be drawn around quiet button in disabled state

### 😯 Current Behavior

Border is drawn around quiet button in disabled state

### 💁 Possible Solution

border color in disabled state should be set to --spectrum-high-contrast-button-face

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

[code](https://codesandbox.io/p/sandbox/angry-lalande-d7hx4n?file=%2Fsrc%2FApp.js%3A1%2C1-57%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqxh2b9j00063b6h6vzm2y4v%2522%252C%2522sizes%2522%253A%255B89.96527777777777%252C10.034722222222229%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqxh2b9j00023b6hmdih9bm7%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqxh2b9j00033b6hjovsvwa9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqxh2b9j00053b6hv07aloab%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqxh2b9j00023b6hmdih9bm7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqxh2b9i00013b6hiltpezvd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clr4wcykt00023b6hn1ch3voq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A57%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqxh2b9j00023b6hmdih9bm7%2522%252C%2522activeTabId%2522%253A%2522clr4wcykt00023b6hn1ch3voq%2522%257D%252C%2522clqxh2b9j00053b6hv07aloab%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqxh2b9j00043b6hruta5ck7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqxh2b9j00053b6hv07aloab%2522%252C%2522activeTabId%2522%253A%2522clqxh2b9j00043b6hruta5ck7%2522%257D%252C%2522clqxh2b9j00033b6hjovsvwa9%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqxh2b9j00033b6hjovsvwa9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

check this in windows high contrast enabled state

### Version

latest

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### If other, please specify.

_No response_

### What operating system are you using?

Mac, windows

### 🧢 Your Company/Team
Adobe

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by majornista**
Closes #5691 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue 5691](https://github.com/adobe/react-spectrum/issue/5691).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

1. Open [Button > ActionButton >  Default Storybook Example](https://reactspectrum.blob.core.windows.net/reactspectrum/d98a689d6f3089695b6ea084bcd782f40059decb/storybook/index.html?path=/story/button-actionbutton--default&args=isQuiet:true&providerSwitcher-express=false) in Google Chrome or MS Edge.
2. In the Storybook Add Ons panel, set Controls > isQuiet to `true`.
3. Open Developer Tools and under the Customize and control DevTools menu button, the vertically oriented ellipsis in the upper right of the Developers Tools toolbar, select More tools > Rendering, and under Emulate CSS media feature forced-colors select `forced-colors: active`.
4. The enabled and disabled ActionButtons with `isQuiet === true` should display a border.

Enabled and Disabled Quiet ActionButtons add a border when `forced-colors: active`: 
ActionButtons when forced-colors: active

As a point of reference, here are screen shots of the MS Word toolbar in Office 365 showing border being added to icon buttons when `forced-colors: active`:

With high contrast mode OFF:
MS Word toolbar with high contrast mode OFF, showing icon-only buttons without a border

With high contrast mode ON:
MS Word toolbar in dark mode with high contrast mode ON, showing icon-only buttons with an added border

## 🧢 Your Project:

Adobe/Accessibility

### CODE REVIEW

**Comment by majornista** [comment]
@snowystinger and @PreetiNagal

**Comment by snowystinger** [comment]
I know it was in the UI kit, but is this really correct? The non-disabled one just looks like text... the disabled one is probably fine because the green isn't used for text

**Review by LFDanLu — DISMISSED** [review]
Tested in AssitiviLabs and local, looks good to me

**Review by snowystinger — COMMENTED** [review]
Border is fixed for regular quiet, however, for static white/black, the border disappears for quiet.
I think we could apply the same, but with a different fallback?
```
xvar(--spectrum-high-contrast-button-text, transparent);
```

**Comment by LFDanLu** [comment]
Looks like the most recent changes are affecting non-WHCM action buttons, was this intentional? https://www.chromatic.com/test?appId=5f0dd5ad2b5fc10022a2e320&id=65aabadefc91752c1e1caf06

The WHCM changes look good to me though, the borders are rendering properly: https://www.chromatic.com/build?appId=651b502f6b74abaae4ee734c&number=16

**Comment by majornista** [comment]
> Looks like the most recent changes are affecting non-WHCM action buttons, was this intentional? https://www.chromatic.com/test?appId=5f0dd5ad2b5fc10022a2e320&id=65aabadefc91752c1e1caf06
> 
> The WHCM changes look good to me though, the borders are rendering properly: https://www.chromatic.com/build?appId=651b502f6b74abaae4ee734c&number=16 

Definitely not intentional. See fix: https://github.com/adobe/react-spectrum/pull/5705/commits/4e8c30125016a77fba491184d9a3671df03e870e

**Comment by LFDanLu** [comment]
Looks better, but still a couple of small changes in non-WHCM: https://www.chromatic.com/test?appId=5f0dd5ad2b5fc10022a2e320&id=65ab204ab93710f6c7f1227b (aka extra border added for some variants of the toggle button)
WHCM has some changes now though, looks like the disabled buttons sometimes have a background fill: https://www.chromatic.com/test?appId=651b502f6b74abaae4ee734c&id=65ab1fb2baa3079f7858a7a9
https://www.chromatic.com/test?appId=651b502f6b74abaae4ee734c&id=65ab1fb2baa3079f7858a7b0

**Comment by majornista** [comment]
> Looks better, but still a couple of small changes in non-WHCM: https://www.chromatic.com/test?appId=5f0dd5ad2b5fc10022a2e320&id=65ab204ab93710f6c7f1227b (aka extra border added for some variants of the toggle button) WHCM has some changes now though, looks like the disabled buttons sometimes have a background fill: https://www.chromatic.com/test?appId=651b502f6b74abaae4ee734c&id=65ab1fb2baa3079f7858a7a9 https://www.chromatic.com/test?appId=651b502f6b74abaae4ee734c&id=65ab1fb2baa3079f7858a7b0

The background fill is intentional in order to disambiguate between disabled and selected + disabled.

**Comment by devongovett** [comment]
Perhaps we should get Spectrum to update the UI kit for this change so we avoid confusion in the future.

**Review by snowystinger — APPROVED** [review]

**Review by LFDanLu — APPROVED** [review]

**Pull request merged**
