### PR TITLE
Fix restoreTextSelection on pointerup event

### LINKED ISSUE #5549: Breadcrumbs tail element cannot be selected
### Provide a general summary of the issue here

In the current implementation, as seen in the example at [useBreadcrumbs](https://react-spectrum.adobe.com/react-aria/useBreadcrumbs.html#example), the tail element of breadcrumbs becomes unselectable. This occurs due to `user-select: none;` being applied when the element is clicked.

### 🤔 Expected Behavior?

Users should be able to select and copy the text of the breadcrumb's tail element.

### 😯 Current Behavior

Currently, when attempting to select the tail element of the breadcrumbs in the react-aria-components library, as demonstrated in the [example](https://react-spectrum.adobe.com/react-aria/useBreadcrumbs.html#example), the text cannot be selected. This is due to the application of `user-select: none`.

### 💁 Possible Solution

The issue seems to stem from the use of useLink in useBreadcrumbItem, as seen in the [GitHub code here](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/breadcrumbs/src/useBreadcrumbItem.ts#L36). Specifically, `disableTextSelection(state.target);` is executed in usePress's onPointerDown handler ([source code](https://github.com/adobe/react-spectrum/blob/bdd37cd188bad79baf4911cd97fa582a7af343b0/packages/%40react-aria/interactions/src/usePress.ts#L407-L409)). A potential solution could involve adjusting this behavior to allow text selection for the tail breadcrumb element.

### 🔦 Context

This unselectability may inconvenience users who wish to copy the text from the tail element of the breadcrumb.

### 🖥️ Steps to Reproduce

Go to the [Breadcrumbs example page](https://react-spectrum.adobe.com/react-aria/useBreadcrumbs.html#example).
Try selecting the text of the last breadcrumb item.
Notice that the text cannot be selected due to `user-select: none` being applied.

### Version

react-aria@3.30.0

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

MacOS

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by sookmax**
Closes #5549

Hello, this PR corrects `restoreTextSelection()` to properly remove `user-select: none` on `pointerup` events. 

I originally [suggested](https://github.com/adobe/react-spectrum/issues/5549#issuecomment-1850139901) to change the condition `target.style.userSelect === 'none' && targetOldUserSelect` to `target.style.userSelect === 'none' && targetOldUserSelect !== undefined` so that the value `''` passes the test, but I realized `targetOldUserSelect !== undefined` is unnecessary since we have an outer if statement that checks `modifiedElementMap.has(target)` so `targetOldUserSelect` is never `undefined`.

https://github.com/adobe/react-spectrum/blob/5ce9a29250e7cd009d73d9d1d36aa1010d7099b9/packages/%40react-aria/interactions/src/textSelection.ts#L83-L98

So instead in this PR, I simply removed `&& targetOldUserSelect` from the condition (and I added a small test)

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:
1. Go to http://localhost:9003/?path=/story/breadcrumbs--default&providerSwitcher-express=false&strict=true
2. Open up a browser devtools, and select the last breadcrumb item.
3. Click on the last breadcrumb item and see if `user-select: none;` is properly added/removed during pointerdown and pointerup.

### CODE REVIEW

**Review by snowystinger — APPROVED** [review]
Thanks so much for the test!

**Comment by snowystinger** [comment]
GET_BUILD

**Comment by LFDanLu** [comment]
GET_BUILD

**Review by LFDanLu — APPROVED** [review]
LGTM, thanks for the speedy fix!

**Pull request merged**
