### PR TITLE
docs: useOverlayTrigger import is missing in example

### PR DESCRIPTION
**Pull request by anuraghazra**
Closes 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [x] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Comment by anuraghazra** [comment]
Ahh i guess there is an auto imports somewhere, i actually copy pasted the code and found that useOverlayTrigger is missing. Closing it then.

**Comment by dannify** [comment]
Hey @anuraghazra I think this is a valid change we should make. The import statement of useOverlayTrigger is a little further up in the mdx file (lines 20-22). Would you like to include the removal of those lines to this pr? I think that should fix the failing docs build. I'm also happy to make the change myself in the next few days. Thanks for pointing this out!

**Comment by anuraghazra** [comment]
@dannify Ohh okay, this should work then.

**Comment by dannify** [comment]
Awesome. Thanks @anuraghazra

**Pull request merged**
