### PR TITLE
fix: remove min/max limits for all segments in `parseDuration`

### LINKED ISSUE #5416: `parseDuration` prohibits carry over values
### Provide a general summary of the issue here

Valid ISO 8601 durations such as `PT36H` can not be parsed using `parseDuration` from `@internationalized/date` because 36 falls outside of the internal range constraint.

### 🤔 Expected Behavior?

```js
parseDuration("PT36H")
```

```
{
   "years": 0,
   "months": 0,
   "weeks": 0,
   "days": 0,
   "hours": 36,
   "minutes": 0,
   "seconds": 0
}
```

### 😯 Current Behavior

```js
parseDuration("PT36H")
```

```
Error: Invalid ISO 8601 Duration string: PT36H
```

### 💁 Possible Solution

These limits could be removed:

https://github.com/adobe/react-spectrum/blob/f600fdfa2af9f3131b34b1536a790aa1bb348151/packages/%40internationalized/date/src/string.ts#L254

### 🔦 Context

This current behavior makes it difficult to use `parseDuration` when you are working with time units only.

I can't tell exactly how the standard treats the issue, but it does seem that there is no general conversion between units. This makes sense to me, because `P1DT12H` could represent a longer, shorter or equivalent length of time to `PT36H` depending on the start date time (due to daylight savings). I believe most other ISO 8601 duration implementations preserve the distinction between `P1DT12H` and `PT36H`.

### 🖥️ Steps to Reproduce

```js
import React from "react";
import { Provider, defaultTheme, Button } from "@adobe/react-spectrum";
import "./styles.css";
import { parseDuration } from "@internationalized/date";

export default function App() {
  return (
    <Provider theme={defaultTheme} height="100%">
      <Button variant={"primary"} onClick={() => {
        parseDuration("PT36H")
      }}>Click Me</Button>
    </Provider>
  );
}

```

### Version

3.32.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### If other, please specify.

_No response_

### What operating system are you using?

Linux

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by limkhl**
Closes #5416

image

As mentioned in the issue, I reviewed the `Temporal.Duration` spec to align the behavior. It seems that the hours value can go up to 130 and beyond, with no explicit maximum limit. Therefore, I’ve adjusted the maximum value to be `Infinity`.

The previously invalid case `P18Y7MT30H15S` is valid in `Temporal` spec, as it returns:
```
{
    years: 18,
    months: 7,
    weeks: 0,
    days: 0,
    hours: 30,
    minutes: 0,
    seconds: 15
}
```
As a result, I’ve updated the test case accordingly.

Additional Notes: Currently, only the `hours` property has had its maximum value limit removed, but properties like `years`, `months`, `minutes`, and `seconds` should also not have maximum limits. To fully align with the `Temporal.Duration` specification, I think it’s necessary to remove the maximum value restrictions for all these properties.

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

### CODE REVIEW

**Review by snowystinger — APPROVED** [review]
seems fine on the surface, will double check with others if there was a reason we did this internally

**Comment by snowystinger** [comment]
message from original implementer

> The limits incorporated were a result of trying to adhere to the ISO8601 standards for a Duration string
My understanding is that based on ISO8601 standards, date and time values can’t exceed their moduli - so a duration string of P18Y7MT30H15S would not technically be a valid in ISO8601 standards
However based on the temporal spec (and the example you shared that the spec accepts overflow), I did a quick test and navigated to https://tc39.es/proposal-temporal/docs/duration.html#new-Temporal-Duration and input the following in the browsers console: Temporal.Duration.from('P18Y7MT30H15S') and no errors are thrown. So that would suggest to me that the temporal spec does indeed accept overflow, despite ISO8601 standards suggesting otherwise

Seems like there was a discrepancy in the specs, but I think we're ok to go ahead with this, though we should really do it for all the fields asap, otherwise we're going to have a weird state in the API during the transition

**Comment by limkhl** [comment]
> Looks like we should remove the limits on all of the segments, not just hours. This should also parse:
> 
> ```
> Temporal.Duration.from('P99Y99M99DT99H99M99S')
> ```

I agree! Would it make sense to set the max for `years`, `months`, `days`, `minutes`, and `seconds` to `Infinity` as well? It seems unnecessary to use `parseNumber(group.replace(',', '.'), min, max)` in this case. Wouldn't it be simpler to replace it with `Number(group.replace(',', '.'))` instead? Would there be any issues with doing it this way?

**Comment by devongovett** [comment]
Yeah that seems fine to me

**Comment by limkhl** [comment]
> Yeah that seems fine to me

I've modified `parseNumber(group.replace(',', '.'), min, max)` to `Number(group.replace(',', '.'))` to remove the min and max limits for all segments. @snowystinger @devongovett Please review again.

**Review by snowystinger — APPROVED** [review]

**Review by devongovett — APPROVED** [review]

**Pull request merged**
