### PR TITLE
Popover(react-aria-components) Allow passing portal target to Popover

### PR DESCRIPTION
**Pull request by aspirisen**
Closes https://github.com/adobe/react-spectrum/issues/4404 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [x] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

1. Create special DOM node in your HTML document
2. Select the DOM node
3. Pass the DOM node into `Popover` using `portalContainer` prop
4. The content of the popover should be rendered inside the DOM node instead of `document.body`

### CODE REVIEW

**Comment by LFDanLu** [comment]
@aspirisen Thank you for the PR! The team is concerned that other part of our code (like our positioning code) may have made assumptions and thus relies that the popover is portaled to `document.body`. Have you tried patching this change yourself in your project and tested the behavior?

**Comment by aspirisen** [comment]
@LFDanLu in my particular case it is working as expected

**Comment by LFDanLu** [comment]
So we actually made use of the portalContainer prop recently for a new feature in Menu where a Popover would be rendered to display contextual information for a unavailable menu item and ran into an issue where the Popover was mispositioned. Still investigating this, but for now this PR will be on hold until we can track down all the cases where positioning issues may occur when altering the portalContainer

**Comment by rlebosse** [comment]
Hi, I'm facing the same need as @aspirisen since I use the 'focus-trap-react' lib to "trap" the focus in a modal.

In this modal, I use the `Select` provided by `react-aria-components`, but since the items displayed (within `Popover`) are appended to `document.body`, they are considered outside of the "focus trap", and I can't set the focus on one of these items (using the keyboard arrows for example).

Being able to pass `portalContainer` with a prop to `Popover` would allow me to specify to append the items displayed to the modal container, and allow the focus on them.

Here is a CodeSandbox I made to illustrate my problematic : https://codesandbox.io/s/react-aria-components-select-focus-trap-react-jrq5z5?file=/src/App.tsx

**Comment by snowystinger** [comment]
Closing, addressed in https://github.com/adobe/react-spectrum/issues/4404
Thanks for your help and understanding!

**Pull request closed without merging**
