### PR TITLE
fix useTreeData root move map

### LINKED ISSUE #5948: useTreeData move only works once
### Provide a general summary of the issue here

The `move()` function of `useTreeData` only works once. All following moves do not update the tree.

### 🤔 Expected Behavior?

every `move()` call should update the tree

### 😯 Current Behavior

`move()` only works once

### 💁 Possible Solution

_No response_

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

```js
const tree = useTreeData({
  initialItems: [
    {
      name: "a",
      items: [{ name: "b", items: [] }],
    },
    {
      name: "c",
      items: [],
    },
    {
      name: "d",
      items: [{ name: "e", items: [{ name: "f", items: [] }] }],
    },
  ],
  getKey: (item) => item.name,
  getChildren: (item) => item.items,
});

tree.move("a", null, 1); // first move works
tree.move("a", null, 0); // second move does not work
```

### Version

3.11.2 @react-stately/data

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

macOS

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by telcy**
Closes #5948

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

## 📝 Test Instructions:

Run test

## 🧢 Your Project:

Internal tool

### CODE REVIEW

**Comment by snowystinger** [comment]
GET_BUILD

**Comment by reidbarber** [comment]
GET_BUILD

**Comment by snowystinger** [comment]
GET_BUILD

**Review by snowystinger — APPROVED** [review]
Thanks for the test!

**Review by reidbarber — APPROVED** [review]

**Pull request merged**
