### PR TITLE
Forward disallowSelectAll from useSelectableList to useSelectableCollection

### LINKED ISSUE #4462: disallowSelectAll from useSelectableList is not passed to useSelectableCollection
# 🐛 Bug Report 

`disallowSelectAll` is not able to be forwarded from `useSelectableList` to `useSelectableCollection`

## 🤔 Expected Behavior

I should be able to forward `disallowSelectAll` from `useSelectableList` to `useSelectableCollection`

## 😯 Current Behavior

`disallowSelectAll` cannot be forwarded from `useSelectableList` to `useSelectableCollection`

## 🔦 Context

I'm making a listbox that uses `useAsyncList` in which case "Select all" isn't really selecting all items but merely the ones that have been loaded so far. We might add a separate "Select all" button/hotkey that does this on the backend but we need to disable the default behavior first.

### PR DESCRIPTION
**Pull request by simenbrekken-visma**
Closes #4462

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

`yarn lint`

## 🧢 Your Project:

Closed-source product

### CODE REVIEW

**Comment by LFDanLu** [comment]
Would you mind adding a story to test this behavior? Would essentially be copying this story but passing `disallowSelectAll` to the list instead: https://github.com/adobe/react-spectrum/blob/1cd18331ac6a87417a1aeff7698dfbbc17d3143a/packages/%40react-aria/selection/stories/useSelectableList.stories.tsx#L220-L226

**Comment by LFDanLu** [comment]
Thanks for the update! The change to MultipleSelection is going to affect a bunch of our components so lemme double check with the team if we are comfortable exposing that prop. It feels pretty innocuous to me and [ctrl + a](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/) is an optional interaction to support in ListBox so it might be ok.

**Review by LFDanLu — APPROVED** [review]

**Comment by snowystinger** [comment]
GET_BUILD

**Review by snowystinger — APPROVED** [review]

**Comment by snowystinger** [comment]
In our release prep, we took another look at this. We'd prefer not to add this prop for a few reasons.
1. We feel that this opens doors for consistency arguments on other keyboard actions.
2. The prop name doesn't accurately reflect what it does when shared out across other collection components, Table for example, where selectAll could still be accomplished with the Select All checkbox. It's a prop specific to useSelectableList.
3. We think there are some other ways to accomplish this.

You could use a capturing listener like so https://codesandbox.io/s/interesting-sea-4qchr6?file=/src/App.js
Or if you're using the hooks, you could possibly override the keydown handler returned by the hook and conditionally call the original function when it's not `cmd+a`

**Comment by simenbrekken-visma** [comment]
> 

The example solution works for me, thanks for taking time to explain your reasoning.

**Pull request merged**
