### PR TITLE
Workaround Android issue where click events are fired on the wrong target

### LINKED ISSUE #1513: When selecting a Menu item, element behind popup receives pointer event
# 🐛 Bug Report 

When a `Menu` item is selected on a touch device, interactive elements *behind* the menu popup receive the pointer event as well.

## 🤔 Expected Behavior

Interactive elements behind a menu popup should do nothing when selecting a menu item.

## 😯 Current Behavior

See [this codesandbox](https://codesandbox.io/s/react-spectrum-menu-pointer-events-wze00?file=/src/App.js) for an example with buttons behind a menu popup. When selecting a menu item, the button also gets clicked (and displays the alert).

https://user-images.githubusercontent.com/20753323/106186087-0e74d280-61a4-11eb-8df9-76d419d3e039.mp4

**Note** that this only happens on mobile devices, and when the pointer device simulation is turned on in browser devtools.

## 💻 Code Sample

https://codesandbox.io/s/react-spectrum-menu-pointer-events-wze00?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.7.0
| Browser          | Firefox, Chrome
| Operating System |

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #1513

On Android Chrome and Firefox, the "click" event may be fired on an incorrect target if the original one is removed during the "pointerup" event (as used by `usePress`). [Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1150073), [Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1692033). This occurs with our overlays which may unmount when a user clicks on a button/menu item inside them, causing an unintended click event to be fired on an element behind it when the overlay unmounts.

A workaround to this is explicitly cancel the `touchend` event via `preventDefault` so that the subsequent click is not fired, being careful not to prevent default on events we _do_ want to go through (such as link clicks, form submits, and input elements like checkboxes). The assumption in this case is that those elements will not result in an overlay unmounting. This is not perfect, but until the browsers fix this issue it's better than nothing.

Story example is from the code sandbox in #3281. When pressing one of the buttons inside the fake overlay, the link should not trigger and the button should not result in the onClick handler calling `alert`.

### CODE REVIEW

**Review by snowystinger — COMMENTED** [review]
Verified that the elements behind are not clicked in responsive mode on Chrome.

In FF they are still clicked, note, you need to put FF into Responsive Mode
Screenshot 2024-09-13 at 10 34 57 AM

**Comment by devongovett** [comment]
Hmm I tested in Firefox on my actual Android device and it didn't click...

**Comment by snowystinger** [comment]
> Hmm I tested in Firefox on my actual Android device and it didn't click...

Interesting, I tried it on my real device as well and it appears to be fixed. It's not triggering a click. @LFDanLu can you try it as well?

**Review by snowystinger — APPROVED** [review]

**Review by LFDanLu — APPROVED** [review]
Tested on Android in Chrome and Firefox, verified that the click events aren't firing on the elements underneath the overlay. Press still seems to work as expected on other elements, so fingers crossed

**Comment by gillesbouvier-qz** [comment]
@LFDanLu Thank you for making this fix. When using Chrome dev tools and loading the page in full width before switching to the responsive mode, I've noticed that the fix does not take effect. Is there a way to make the code re-run on window resize maybe?

**Comment by gillesbouvier-qz** [comment]
@LFDanLu Thank you for making this fix.

On Chrome, when loading a page in full browser width and then switching to responsive mode using the dev tools, I've noticed that the fix is not active, whereas it works if the page is loaded in responsive mode from the start. Is there a way to trigger a reload on window resize?

**Pull request merged**
