### PR TITLE
dnd: when dragging, stop propagation to potential parent draggables

### PR DESCRIPTION
**Pull request by tflanagan**
Closes https://github.com/adobe/react-spectrum/issues/4597

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

Still new to the repo so guidance on these would be nice. I filled out the CLA. As this is such a minor change, I'm unsure if all of these are required.

## 📝 Test Instructions:

See [codepen](https://codesandbox.io/s/hopeful-browser-fqrqu7?file=/src/App.js) for reproduction of issue

Apply the patch and the issue will be resolved.

### CODE REVIEW

**Comment by tflanagan** [comment]
I'm hoping someone with more knowledge of the testing suite can copy/paste from the codepen and add a test for this.

**Comment by LFDanLu** [comment]
GET_BUILD

**Comment by snowystinger** [comment]
Would you mind adding a test for this?

**Comment by LFDanLu** [comment]
For a test, potentially can add one in https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/dnd/test/dnd.test.js, and nest a `Draggable` inside another `Draggable` then test that a drag on the child doesn't trigger a drag on the parent.

**Comment by tflanagan** [comment]
Not sure why the test is failing. In practice, this one-liner fixes the issue.

**Comment by LFDanLu** [comment]
No worries, I'll see if I or someone on the team can take a closer look at the test and help out there. In the meantime, if you need this fix sooner rather than later you could use [patch-package](https://www.npmjs.com/package/patch-package) to patch this in your repo/app

**Comment by tflanagan** [comment]
Thanks again for the support on this, it makes me happy to see a good dnd library for react that's alive and well maintained.

No rush on the fix, I'm just using my branch until then.

**Comment by tflanagan** [comment]
@LFDanLu I found the issues with the tests, just a couple missing stopPropogations

**Comment by LFDanLu** [comment]
@tflanagan Thanks for debugging and figuring that out! Will add this to our next testing session and hopefully can get this merged soon then.

**Comment by LFDanLu** [comment]
GET_BUILD

**Review by LFDanLu — APPROVED** [review]
LGTM, thanks for sticking with the test debugging!

**Review by yihuiliao — APPROVED** [review]
lgtm, thanks for the contribution!

**Pull request merged**
