### PR TITLE
Add backgroundColor prop to Table Cell

### PR DESCRIPTION
**Pull request by dsabsay**
Closes 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [x] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

## 📝 Test Instructions:

See new story.

## 🧢 Your Project:

Adobe

### CODE REVIEW

**Comment by snowystinger** [comment]
Hi, thanks for the PR; however, we do not support background colors on table cells because we ensure a certain level of contrast for accessibility. If you need to indicate the status of a row or cell, please use a StatusLight along with a visible label, as color alone is not enough for some users.

**Comment by dsabsay** [comment]
@snowystinger Thanks for the context. I understand the accessibility requirement. The color I intend for my use case is entirely supplemental to the content of the cell and not required for understanding of the content. What do you think about allowing cell coloring while also ensuring a certain contrast level (method TBD)?

**Comment by dsabsay** [comment]
For additional context, my use case is probably somewhat uncommon in that almost ALL Cells will receive a background color. I would use a `View` embedded in the `Cell`; however, there is a significant amount of padding applied directly in the `Cell` which is undesired:

Screen Shot 2024-04-03 at 2 03 33 PM

Would the option to remove `Cell` padding be acceptable? (And by padding I mean padding and/or margin; I have not looked at how it is implemented)

**Comment by reidbarber** [comment]
Even if you're successfully meeting contrast requirements, this design isn't supported by Spectrum for TableView. I recommend reaching out the Spectrum design team internally for an alternative solution.

**Comment by dsabsay** [comment]
@reidbarber Understood, thanks!

**Pull request closed without merging**
