### PR TITLE
Add readonly & required data attributes to `<TextField />`

### PR DESCRIPTION
**Pull request by sookmax**
Closes https://github.com/adobe/react-spectrum/issues/5930

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

### Docs
http://localhost:1234/react-aria/TextField.html#textfield-2

### CODE REVIEW

**Comment by reidbarber** [comment]
GET_BUILD

**Comment by stefanprobst** [comment]
thanks! should we add these to NumberField/DateField/Select as well?

**Review by reidbarber — APPROVED** [review]

**Review by snowystinger — APPROVED** [review]
These seem like they should be renderProps for the Input as well. Thoughts?

If we want to do that, it can be in a separate PR

**Comment by sookmax** [comment]
@snowystinger Not sure if `<Input />` can be used standalone, but I found the following test in `TextField.test.js`:
https://github.com/adobe/react-spectrum/blob/34924436f5b76b44b8adbb0a4fdb64c1c15de99f/packages/react-aria-components/test/TextField.test.js#L137-L142

Title of which, by the way, doesn't seem to match what it is testing?

**Pull request merged**
