### PR TITLE
SearchAutocomplete: add help text support

### PR DESCRIPTION
**Pull request by reidbarber**
## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Review by LFDanLu — COMMENTED** [review]
LGTM, but would be nice to get some chromatic stories for this. If you wanna do that as a followup that is fine too

**Comment by snowystinger** [comment]
Chromatic currently failing due to tags missing translations. The searchautocomplete stories we have all passed. We can safely ignore the chromatic failure for this PR.

**Review by snowystinger — APPROVED** [review]

**Review by LFDanLu — APPROVED** [review]
LGTM, do we wanna hold for after the release? If not, I'd prefer adding the chromatic stories for safety

**Comment by reidbarber** [comment]
@LFDanLu I'm fine with either, but lean towards waiting since we've tested everything. Also I noticed we don't have help text is most other field components chromatic stories either, so we may want to add those soon as well.

**Comment by reidbarber** [comment]
@LFDanLu I'll merge this now, and add chromatic stories in a separate PR. There may be a few more style fixes we want to get into SearchAutocomplete before getting a baseline.

**Pull request merged**
