### PR TITLE
Fix useOverlayPosition in a few cases where placement="top"

### LINKED ISSUE #1004: useOverlayPosition() is buggy in a few cases when placement=top
# 🐛 Bug Report 

`useOverlayPosition()` sets the `bottom` css prop when `placement=top`.  This currently is buggy in two cases I know of:

* If the container is not body; `computePosition()` is only computed using `boundaryDimensions`, when it should be using `containerOffsetWithBoundary` instead
* When `document.body` as the default container has `position: relative`; as a positioned offset parent, the `bottom` needs to be computed relative to the container's actual height, instead of the "visible height" computed by `getContainerDimensions`

## 🤔 Expected Behavior

placement=top would align overlay above trigger element correctly.

## 😯 Current Behavior

placement=top only works properly right now if the overlay container is `document.body`, and it has `position: static`

## 💁 Possible Solution

PR incoming :smile: 

## 🔦 Context

Noticed this when using `useSelect` when `shouldFlip` kicks in

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.2.0
| Browser          | Chrome 84
| Operating System | Ubuntu 20.04

## 🧢 Your Company/Team

[Plasmic](https://plasmic.app)

### PR DESCRIPTION
**Pull request by chungwu**
Now handles cases where container is not body, or container is
positioned (non-static).

Closes #1004

## ✅ Pull Request Checklist:

- [X] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [X] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [X] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Open the `UsePositionOverlay` stories, which has a simple button triggering overlay positioning in placements top and bottom, in either document.body or a positioned container.  
* For each story, make sure the overlay shows up where you expect.
* Change the window size to force scrolling of the overlay content, and make sure the max-height is set correctly.

## 🧢 Your Project:

[Plasmic](https://plasmic.app)

### CODE REVIEW

**Comment by chungwu** [comment]
Yup, added UseOverlayPosition stories, along with test instructions in this PR.

**Comment by snowystinger** [comment]
Thanks for adding the stories. I had a chance to try them out today, extremely helpful. I had a couple observations, I just want to make sure I'm looking at the right things.

In chrome for me, the story 'positioned container, top' has an unpleasant flash where it's on the bottom first for me before it goes to the top and 'positioned container, bottom' does a similar thing before shifting over
Looks like it might be somewhat because of the shifting button size? (also may have existed before?)

When I shrink the page, the 'positioned container, top' actually won't stay open for me, and the 'positioned container, bottom' disappears as soon as i try to scroll inside it.

**Review by devongovett — APPROVED** [review]
Tested locally. I was able to reproduce the flash but only once - seems like it only happens on the first render. Rob and I couldn't reproduce the closing issue again. I don't think the flash was introduced in this PR though, so going to merge. Thanks and sorry for the delay!

**Comment by chungwu** [comment]
oops, sorry for dropping the ball here, meant to look into it :sweat_smile: I also don't think they're related to the CR, as I'm only changing how the positions are computed, not when etc.... I just haven't had time to dig into it :stuck_out_tongue:

**Pull request merged**
