### PR TITLE
fix useRangeCalendar behavior while interacting outside

### PR DESCRIPTION
**Pull request by QzCurious**
Closes #5703, #5709

This is a proposal to fix `useRangeCalendar` behavior by directly showcasing what was wrong (IMO).
Most problem were state on #5703. But I just can't state the issue any better. This PR would hopefully make things more clear.

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

_The videos is recorded with existing [story](http://localhost:9003/?path=/story/date-and-time-rangecalendar--default-val-visible-months&providerSwitcher-express=false&strict=true)._

The main difference is instead of commit selection, I **canceled** it. And canceling means that `onChange` would not get called.

| Difference | Original | My Proposal |
|--------|--------|--------|
| Click on empty cell, td, title of calendar or anywhere outside | <video src='https://github.com/adobe/react-spectrum/assets/38932402/00dd8f6e-7095-4b53-a29a-5945336ca5fe'/> |<video src='https://github.com/adobe/react-spectrum/assets/38932402/df0e0765-2ca8-4cae-8788-52a8ee535a8d' /> |
| Scrolling start on empty cell, td, title of calendar (or anywhere outside the calendar) should not affect selection | <video src='https://github.com/adobe/react-spectrum/assets/38932402/7a940b21-df13-43e3-bedb-4b08f47b518c'/> |<video src='https://github.com/adobe/react-spectrum/assets/38932402/b3fce4d6-d1a2-403b-9596-063135ec8f46' /> |
| Drag onto empty cell, td, title of calendar or anywhere outside | <video src='https://github.com/adobe/react-spectrum/assets/38932402/7b483452-7753-4311-9749-513d363945a2'/> | <video src='https://github.com/adobe/react-spectrum/assets/38932402/71e6a935-9539-427b-b88f-a4d249daf74a' /> |

| Remain the same | Original | My Proposal |
|--------|--------|--------|
| Scrolling start on a CalendarCell | <video src='https://github.com/adobe/react-spectrum/assets/38932402/a2838307-f0d3-418f-8dd5-4033a35f058c'/> | <video src='https://github.com/adobe/react-spectrum/assets/38932402/497346ab-44e3-4538-a6ea-655a655bc17b' /> |
| Change viewport by navigation buttons | <video src='https://github.com/adobe/react-spectrum/assets/38932402/94ac3f00-a433-4ad8-8542-c0d59c1ddd08'/> | <video src='https://github.com/adobe/react-spectrum/assets/38932402/55bc0e2c-570c-4f78-99bf-b7941ac6cff8' /> |
| Select range by dragging | <video src='https://github.com/adobe/react-spectrum/assets/38932402/e477e33e-98c3-45d7-a06d-df0790a67368'/> | <video src='https://github.com/adobe/react-spectrum/assets/38932402/5369cbf4-4856-4218-82a1-ec0a55a3f357' /> |

## 🧢 Your Project:

https://github.com/QzCurious/react-spectrum

### CODE REVIEW

**Comment by QzCurious** [comment]
I don't know why but it seems like there were a few test case failed on commits before my.

**Review by reidbarber — COMMENTED** [review]
Thanks for the PR, and the detailed testing instructions!

First, you'll need to [sign the Adobe CLA](http://opensource.adobe.com/cla.html) to get that build step to pass.

And it looks like the tests that are failing are correctly failing due to the updated behavior (i.e. `clicking outside calendar commits selection`). We'll need to update those to match the new expected behavior.

If any tests were failing before your changes, they were probably related to a node version mismatch and can be ignored (they'll pass in CI).

**Comment by QzCurious** [comment]
I've signed Adobe CLA and made CI running. Did "updated behavior" mean the code I submitted? If so, could you point me which test cases should I take care of?

It's currently too many tests failed on my machine (node v18.18.2 on commit ee51290b9).
image

I'm not sure these test cases were "correctly failing" or caused by my environment.
image

**Comment by LFDanLu** [comment]
@QzCurious Could you try node version `v18.17.1`? Some versions of node had a breaking change to Date/Time formatting, might be what you are running into here

**Comment by QzCurious** [comment]
It works on `v18.12.1` rather.

image

--- 

The relevant failed cases are:

- releasing drag outside calendar commits it
- clicking outside calendar commits selection
- selects the nearest available date when blurring the calendar

And I've changed those to match new behavior:

- cancel ongoing selection when releasing drag outside calendar
- cancel ongoing selection when clicking outside calendar
- cancel ongoing selection when blurring the calendar

**Comment by QzCurious** [comment]
By the way, `v18.17.1` works on a windows machine.

---

On my mac book, there are other failed tests. Seems like some were caused by encoding. And some might be platform specific.

The output text [here](https://gist.github.com/QzCurious/f49995a89265fa090c1faf9498ab518c)

Screenshot 2024-01-24 at 11 09 55 PM
Screenshot 2024-01-24 at 11 10 05 PM
Screenshot 2024-01-24 at 11 10 17 PM
Screenshot 2024-01-24 at 11 10 30 PM

**Comment by reidbarber** [comment]
GET_BUILD

**Comment by reidbarber** [comment]
GET_BUILD

**Comment by QzCurious** [comment]
Hi, just wanted to know how it goes. Let me know if there's anything I can help with.

**Comment by LFDanLu** [comment]
@QzCurious apologies, we've got a bit side tracked with last release, I'll see if we can get this into an upcoming testing session for the team to evaluate the new behavior.

**Comment by LFDanLu** [comment]
GET_BUILD

**Comment by LFDanLu** [comment]
@QzCurious apologies about the delay, but the team went through the behavioral changes in a testing session today. Overall, we liked the update in behavior that allows the user to now scroll through multiple calendars and finalize a range selection. However, we weren't sure about completely canceling the range selection upon clicking outside the calendar, namely because of a flow where the user might assume that their selection has been made and then they click on an accompanying TimeField to continue configuring their date as shown here:

https://github.com/adobe/react-spectrum/assets/9661127/6eff20f1-2a2c-4f8b-8993-14acc11db2e6

with the new changes that would get canceled:

https://github.com/adobe/react-spectrum/assets/9661127/0dddab9f-eaf9-40c5-ae70-c99df0ec5fcd

**Comment by QzCurious** [comment]
I understand there should have some effort for validating all possible scenarios. And im gald you found a "behavioral bug" for my change.

I'd love to ask if you team would have a plan to sort it all and implement it (because it actually involve some decisions instead of just a bug). Or I could still submit some progress, if any, for you to validate it.


### By the way

For scroll through calendars, first recording is wrong. You should validating it on mobile interface (you can refer to the videos on https://github.com/adobe/react-spectrum/pull/5721#issue-2090932074).

**Comment by LFDanLu** [comment]
From the team's discussion yesterday, we'd be happy to accept a change isolated to fixing the mobile scrolling range selection but it was hard to tell from a glance if that would be easy to pull out from the changes made in this PR. Would that be possible?

> For scroll through calendars, first recording is wrong. You should validating it on mobile interface (you can refer to the videos on https://github.com/adobe/react-spectrum/pull/5721#issue-2090932074).

As for the first recording, that is intentionally showing the desktop behavioral change rather than the mobile behavior. We were concerned that the changes may be confusing to a user using the RSP DateRangePicker because the flow shown in the [first video here](https://github.com/adobe/react-spectrum/pull/5721#issuecomment-1965572524) used to allow a user to confirm a date range selection when they click into the neighboring TimeField but that wouldn't happen after these changes in the PR.

**Comment by QzCurious** [comment]
I see. Thanks for explaining it!

Let me know if you want keep these PR and issues open, or I will close this PR and related issues. And open an issue for "mobile scrolling range selection".

**Comment by QzCurious** [comment]
Close.

## Summery

1. This PR is doing two things
    - Cancel ongoing selection when xxx, instead of select range on blur (see https://github.com/adobe/react-spectrum/pull/5721#issuecomment-1908310751)
    - Allow (mobile) scroll through multiple calendars and finalize a range selection (see https://github.com/adobe/react-spectrum/pull/5721#issue-2090932074: Scrolling start on empty cell, td, title of calendar)
2. This PR would break an expected behavior, a UI that combing a calendar and a TimeFile (see: https://github.com/adobe/react-spectrum/pull/5721#issuecomment-1965572524)
3. It's preferable to only have "mobile scrolling range selection" fixed without breaking existing "select range on blur".

**Pull request closed without merging**
