### PR TITLE
Stop using propagation when escape key is pressed, update useTooltipTrigger.ts

### PR DESCRIPTION
**Pull request by audreyso**
Closes https://github.com/adobe/react-spectrum/issues/4120

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Goto the new story DialogTrigger story "withTooltip". Open the dialog, use the keyboard to select the button, the tooltip opens. Press escape and the tooltip closes, but the dialog does not.

### CODE REVIEW

**Review by snowystinger — COMMENTED** [review]
hey! thanks for the PR, would you mind providing some test instructions (new story if applicable) to use with our storybook or a unit test verifying the new behavior?

**Review by ktabors — COMMENTED** [review]
I tested this locally and this change does fix this issue.

**Review by ktabors — APPROVED** [review]

**Comment by snowystinger** [comment]
GET_BUILD

**Review by snowystinger — APPROVED** [review]

**Comment by snowystinger** [comment]
Verified that pressing escape after the tooltip is closed will still close the dialog.

**Pull request merged**
