### PR TITLE
Make button attr type consistent with @types/react

### LINKED ISSUE #2875: @react-aria/useButton with TypeScript: Types of property 'type' are incompatible
# 🐛 Bug Report 

When using [the example from the `@react-aria/button` docs](https://react-spectrum.adobe.com/react-aria/useButton.html#example), the types for `useButton` in `@react-aria/button@3.4.1` don't match with the React types for the `type` prop on `<button>` elements:

```
Type '{ children: string; ref: MutableRefObject<undefined>; download?: any; href?: string; hrefLang?: string; media?: string; ping?: string; rel?: string; target?: HTMLAttributeAnchorTarget; ... 254 more ...; onTransitionEndCapture?: TransitionEventHandler<...>; }' is not assignable to type 'DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>'.
  Type '{ children: string; ref: MutableRefObject<undefined>; download?: any; href?: string; hrefLang?: string; media?: string; ping?: string; rel?: string; target?: HTMLAttributeAnchorTarget; ... 254 more ...; onTransitionEndCapture?: TransitionEventHandler<...>; }' is not assignable to type 'ButtonHTMLAttributes<HTMLButtonElement>'.
    Types of property 'type' are incompatible.
      Type 'string' is not assignable to type '"button" | "submit" | "reset"'.
```

Downgrading to version `@react-aria/button@3.3.4` makes the error go away.

The bug is still present in `@react-aria/button@3.4.0`

## 🤔 Expected Behavior

No type error

## 😯 Current Behavior

Type error (see above)

## 💁 Possible Solution

Match types with `@types/react` types: use `string | undefined` instead of the `"button" | "submit" | "reset"` literal union.

## 🔦 Context

Use [the example from the `@react-aria/button` docs](https://react-spectrum.adobe.com/react-aria/useButton.html#example)

## 💻 Code Sample

Check out `App.tsx` in this StackBlitz:

https://stackblitz.com/edit/react-ts-ybosd2?file=App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/button   | 3.4.1 |
| Browser          | - |
| Operating System | - |

### PR DESCRIPTION
**Pull request by karlhorky**
Closes #2875

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Run the tests and typechecking with [the example from the @react-aria/button docs](https://react-spectrum.adobe.com/react-aria/useButton.html#example).

## 🧢 Your Project:

--

### CODE REVIEW

**Comment by devongovett** [comment]
This failed type checking.

```
[0]   Type '{ children: string[]; onClick: () => void; isDisabled?: boolean; onPress?: (e: PressEvent) => void; onPressStart?: (e: PressEvent) => void; onPressEnd?: (e: PressEvent) => void; ... 23 more ...; ref: MutableRefObject<...>; }' is not assignable to type 'ButtonHTMLAttributes<HTMLButtonElement>'.
[0]     Types of property 'type' are incompatible.
[0]       Type 'string' is not assignable to type '"button" | "reset" | "submit"'.
```

Are you using a different version of `@types/react` maybe?

I can see here that the types are explicit: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2057

**Comment by devongovett** [comment]
Ah, looks like the problem is that it's resolving to a different overload of `useButton` that is resulting in `AnchorHTMLAttributes` rather than `ButtonHTMLAttributes`. That type uses `string`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2019. So we have ourselves a conflict.

I think the root cause is that typescript doesn't choose the `'button'` overload by default, if an `elementType` option is not provided. Here you can see a working example once that is added. https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMBCyYwgOzgF84AzKCEOAcgAEp0BDAYxgFpGphGB6AIxx581ANwAoUJFhwAVHEao4AJSasyFKtQYsYosWPQAPKfAAm6Uo2QAbeKWT5WwAnACCYMAAoAlIjFw4a3R4BlI4AF5lVRgAOjR0FVJPfBtrb3EAoPgkAVwCAAUKMEUSSPjsPPxPBCIAGjhQ9P0AhhhkKEJPfwC4AB5coUQY4YGCotQSUPCEUKIAPm6e+VRTUkW+-kECBYCmojEgA

**Comment by karlhorky** [comment]
> Ah, looks like the problem is that it's resolving to a different overload of `useButton` that is resulting in `AnchorHTMLAttributes` rather than `ButtonHTMLAttributes`

Right yeah, I noticed this but didn't see a way of overriding the element type

> I think the root cause is that typescript doesn't choose the 'button' overload by default, if an `elementType` option is not provided. Here you can see a working example

Is there an elementType in this example? Is it supposed to be a generic parameter or something? I don't see it 👀

**Comment by devongovett** [comment]
ah sorry, seems my link didn't update. but yeah, if you add `elementType: 'button'` to the `useButton` options it seems to start working. So I think we just need to figure out how to make that the default.

**Comment by karlhorky** [comment]
Ah, got it, thanks! Like this then:

```ts
import { useButton } from '@react-aria/button';
import * as React from 'react';

export default function App() {
  let ref = React.useRef(null);
  let { buttonProps } = useButton({elementType: 'button'}, ref);

  return (
    <button {...buttonProps} ref={ref}>
      asdf
    </button>
  );
}
```

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMBCyYwgOzgF84AzKCEOAcgAEp0BDAYxgFpGphGB6AIxx581ANwAoUJFhwAVHEao4AJSasyFKtQYsYosWPQAPKfAAm6Uo2QAbeKWT5WwAnACCYMAAoAlIjFw4a3R4BlI4AF5lVRgAOjR0FVJPfBtrb3EAoPgkAVwCAAUKMEUSSPjsPPxPBHQgkHR8GAAVAE8wdAAuGlyhaiIAGjhQ9P0AhhhkKEJPfwC4AB4elwQY1aX8QohiklDwhFCiAD5ZuflUU1IThf5BAmOAkaIxIA

**Comment by karlhorky** [comment]
> we just need to figure out how to make that the default

So looking at the `useButton` lines below, maybe it would be possible to make it a generic (instead of overloads)?

https://github.com/adobe/react-spectrum/blob/2c25922e23ec51bd487b7838adb48a60c558dc36/packages/%40react-aria/button/src/useButton.ts#L35-L49

For example, something like this:

```diff
-export function useButton(props: AriaButtonProps<ElementType>, ref: RefObject<any>): ButtonAria<HTMLAttributes<any>> {
+export function useButton<UseButtonElementType extends ElementType = 'button'>(props: AriaButtonProps<UseButtonElementType>, ref: RefObject<any>): ButtonAria<HTMLAttributes<any>> {
```

**Comment by karlhorky** [comment]
For the return type, conditional types could be used (although I think it may be a bit tricky to return the right value inside the function, wasn't able to do this yet):

```ts
import {ElementType, HTMLAttributes, ButtonHTMLAttributes, AnchorHTMLAttributes} from 'react'
import {AriaButtonProps} from '@react-types/button'
import {ButtonAria} from '@react-aria/button'

export function useButton<UseButtonElementType extends ElementType = 'button'>(
  props: AriaButtonProps<ElementType>,
): ButtonAria<
  UseButtonElementType extends 'button' ? ButtonHTMLAttributes<HTMLButtonElement>
 : UseButtonElementType extends 'a' ? AnchorHTMLAttributes<HTMLAnchorElement>
 : HTMLAttributes<HTMLElement>
> {
  return {} as any
}

const {buttonProps} = useButton({type: 'button'})
```

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwKIBsCmI0DsYBUCeYaANHABK4CyAMgIIwxTABGArjGgM6kBC7MELBRr1GLdl1K0sAYwAW0YXQZM2HTgF84AMygQQcAORQ0AQxkxDAKFCRYiWk1N8GggAp6wmnXoOGAAibmMAC0MIRcAPRqAljWttDwCC6xjsCmWrr6RoFmFiGmTtH8gtZWaAAedvDarLIwwIJwrJxoKYIAPACqre1YqBjYeBFwlRxYACaccAOYOAREcAC8RjGlAHwAFFZwcGCenABccGnOJVgeEF4ds0MLaOvEVgCUx32nHTtwPW3nt-MjMbYKarc6GOAAfjgfSUolUEk4HSUfX+MHWO2OPxR6Dmw0WQMm00MpnBUOk8kUVGUYjUXCRVPJCigqPRcGOsJU4nU9JoLKs60QXxMMFYUCwiC0pmmpiw+CsGisVhkgk4STWFwOWhWLV+riwmwQ4SIx0M6sMGmeQA

**Comment by karlhorky** [comment]
haha or... just reorder the overloads, and it also works!

https://github.com/adobe/react-spectrum/pull/2930

**Pull request closed without merging**
