### PR TITLE
issue-3021: throw an error when theme is not provided

### PR DESCRIPTION
**Pull request by lishichengyan**
Closes 
https://github.com/adobe/react-spectrum/issues/3021

I'm not sure if we could update the [type description](https://github.com/adobe/react-spectrum/blob/ad9fc6c065d86de63517874c08d3ddf96f9cfed3/packages/%40react-types/provider/src/index.d.ts#L62-L65) of theme to indicate that the parent provider must have a theme provided as it can still be optional for child provider. Any suggestions/ideas are welcome!

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:
Could use the following code piece to verify the error is thrown:
```
  .add(
    'theme not provided',
    () => {
      let Example = () => {
        return (
          <>
            <Button
              variant="primary">
              Hey hey hey! I'm a button!
            </Button>
          </>
        );
      };
      return (
        <Provider theme={null}>
          <Provider>
            <Example />
          </Provider>
        </Provider>
      );
    })
```

## 🧢 Your Project:
n.a.

### CODE REVIEW

**Review by snowystinger — COMMENTED** [review]
Hey, thanks for the PR, we've definitely had a lot of discussions around this as a team. As you pointed out, we can't make it required for one but not the others. So we haven't come up with a solution everyone is happy with yet to fix the types for it.

We'd shied away from throwing an error specifically because we don't mark it as required, but I think if we're checking the context as well, this could be ok.

**Comment by lishichengyan** [comment]
> Hey, thanks for the PR, we've definitely had a lot of discussions around this as a team. As you pointed out, we can't make it required for one but not the others. So we haven't come up with a solution everyone is happy with yet to fix the types for it.
> 
> We'd shied away from throwing an error specifically because we don't mark it as required, but I think if we're checking the context as well, this could be ok.

Hey @snowystinger, thanks for reviewing! Did you mean checking the [prevContext](https://github.com/adobe/react-spectrum/blob/ad9fc6c065d86de63517874c08d3ddf96f9cfed3/packages/%40react-spectrum/provider/src/Provider.tsx#L43:~:text=let%20prevContext%20%3D%20useProvider()%3B)?

Also I'm wondering if we could provide a default theme if none is provided, something like
```
if (!theme) {
  theme = defaultTheme
}
```

**Comment by snowystinger** [comment]
Including a default theme would increase bundle size for everyone, so that's not something we can do, unfortunately.
And yes, you're already checking it though, so that wasn't saying you need to do anything else.

**Review by snowystinger — APPROVED** [review]

**Review by reidbarber — APPROVED** [review]
Thanks!

**Pull request merged**
