### PR TITLE
Fix @internationalized/date addZoned not handling weeks duration

### LINKED ISSUE #4701: ZonedDateTime add/subtract doesn't work with weeks
# 🐛 Bug Report 

When using a `ZonedDateTime` object, manipulating it by adding or removing weeks does not work and returns the original date and time.

This problem only affects weeks. Minutes, hours, days, months, years are not affected and work correctly.

image

The problem also does not affect `CalendarDate`.

## 🤔 Expected Behavior

`now(getLocalTimeZone()).add({ weeks: 1 })` should return a week from now.
`now(getLocalTimeZone()).subtract({ weeks: 1 })` should return a week ago.

## 😯 Current Behavior

`now(getLocalTimeZone()).add({ weeks: 1 })` returns now.
`now(getLocalTimeZone()).subtract({ weeks: 1 })` returns now.

## 💁 Possible Solution

Unsure.

## 🔦 Context

Trying to calculate a date and time a week from now.

## 💻 Code Sample

https://codesandbox.io/p/sandbox/nifty-dawn-pwdps9?file=%2Fsrc%2FApp.tsx%3A12%2C1-15%2C11

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @internationalized/date   | 3.2.0
| Browser          | Chrome 114.0.5735.133 (Official Build) (arm64)
| Operating System | macOS Ventura 13.4

### PR DESCRIPTION
**Pull request by longzheng**
Closes #4701

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Added test to `manipulation.test.js`

Run `yarn test`

### CODE REVIEW

**Comment by devongovett** [comment]
Thanks for the PR! There are tests for this in ZonedDateTime.test.js (the `add` method calls `addZoned`). Looks like we were missing tests for weeks. If you'd like to add one there that would be great.

**Comment by longzheng** [comment]
@devongovett Fair enough. I tried adding the tests but I'm struggling to understand why it's failing because I'm not familiar with the US timezones.

```js
      it('should add weeks and adjust hours', function () {
        let zoned = toZoned(new CalendarDateTime(2021, 3, 13, 2), 'America/Los_Angeles');
        let expected = toZoned(new CalendarDateTime(2021, 3, 20, 3), 'America/Los_Angeles');
        expect(zoned.add({weeks: 1})).toEqual(expected);
      });

      it('should subtract weeks and adjust hours', function () {
        let zoned = toZoned(new CalendarDateTime(2021, 3, 15, 2), 'America/Los_Angeles');
        let expected = toZoned(new CalendarDateTime(2021, 3, 8, 3), 'America/Los_Angeles');
        expect(zoned.subtract({weeks: 1})).toEqual(expected);
      });
```

These fail because the output hour is not correct.

```
 ZonedDateTime › add › should handle forward timezone transitions › should add weeks and adjust hours

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

    @@ -2,11 +2,11 @@
        "calendar": GregorianCalendar {
          "identifier": "gregory",
        },
        "day": 20,
        "era": "AD",
    -   "hour": 3,
    +   "hour": 2,
        "millisecond": 0,
        "minute": 0,
        "month": 3,
        "offset": -25200000,
        "second": 0,

      71 |         let zoned = toZoned(new CalendarDateTime(2021, 3, 13, 2), 'America/Los_Angeles');
      72 |         let expected = toZoned(new CalendarDateTime(2021, 3, 20, 3), 'America/Los_Angeles');
    > 73 |         expect(zoned.add({weeks: 1})).toEqual(expected);
         |                                       ^
      74 |       });
      75 |
      76 |       it('should subtract weeks and adjust hours', function () {

      at Object.toEqual (packages/@internationalized/date/tests/ZonedDateTime.test.js:73:39)
```

It gets even weirder if I modify the existing test to add a day, to add 7 days, it also fails.

```diff
      it('should add days and adjust hours', function () {
        let zoned = toZoned(new CalendarDateTime(2021, 3, 13, 2), 'America/Los_Angeles');
-       let expected = toZoned(new CalendarDateTime(2021, 3, 14, 3), 'America/Los_Angeles');
+       let expected = toZoned(new CalendarDateTime(2021, 3, 20, 3), 'America/Los_Angeles');
-       expect(zoned.add({days: 1})).toEqual(expected);
+       expect(zoned.add({days: 7})).toEqual(expected);
      });
```

```
  ● ZonedDateTime › add › should handle forward timezone transitions › should add days and adjust hours

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

    @@ -2,11 +2,11 @@
        "calendar": GregorianCalendar {
          "identifier": "gregory",
        },
        "day": 20,
        "era": "AD",
    -   "hour": 3,
    +   "hour": 2,
        "millisecond": 0,
        "minute": 0,
        "month": 3,
        "offset": -25200000,
        "second": 0,

      59 |         let zoned = toZoned(new CalendarDateTime(2021, 3, 13, 2), 'America/Los_Angeles');
      60 |         let expected = toZoned(new CalendarDateTime(2021, 3, 20, 3), 'America/Los_Angeles');
    > 61 |         expect(zoned.add({days: 7})).toEqual(expected);
         |                                      ^
      62 |       });
      63 |
      64 |       it('should subtract days and adjust hours', function () {

      at Object.toEqual (packages/@internationalized/date/tests/ZonedDateTime.test.js:61:38)
```

It's my understanding that the hour is changing because of the forward timezone transition, but I don't quite understand why the hour does not change if we are changing more than a day.

**Comment by longzheng** [comment]
Actually something super weird is happening. I think there might be a bug with timezone handling?

I added this test, which adds 2 days or 48 hours, the output should be the same bug is not?

```ts
      it('should add 2 days and adjust hours', function () {
        let zoned = toZoned(new CalendarDateTime(2021, 3, 13, 2), 'America/Los_Angeles');
        expect(zoned.add({days: 2})).toEqual(zoned.add({hours: 48}));
      });
```

```
  ● ZonedDateTime › add › should handle forward timezone transitions › should add 2 days and adjust hours

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

    @@ -2,11 +2,11 @@
        "calendar": GregorianCalendar {
          "identifier": "gregory",
        },
        "day": 15,
        "era": "AD",
    -   "hour": 3,
    +   "hour": 2,
        "millisecond": 0,
        "minute": 0,
        "month": 3,
        "offset": -25200000,
        "second": 0,

      58 |       it('should add 2 days and adjust hours', function () {
      59 |         let zoned = toZoned(new CalendarDateTime(2021, 3, 13, 2), 'America/Los_Angeles');
    > 60 |         expect(zoned.add({days: 2})).toEqual(zoned.add({hours: 48}));
         |                                      ^
      61 |       });
      62 |
      63 |       it('should subtract days and adjust hours', function () {

      at Object.toEqual (packages/@internationalized/date/tests/ZonedDateTime.test.js:60:38)
```

**Comment by longzheng** [comment]
@devongovett could I get some help with the broken behaviour with timezones?

**Comment by longzheng** [comment]
Since I couldn't figure out what was wrong with the forward timezone tests, I added the tests to `manipulation.test.js` instead with `ZonedDateTime` directly.

**Comment by devongovett** [comment]
I think the behavior is right (see my reply on your other issue). You might want to just choose a different date that isn't on a daylight saving time transition so it isn't as confusing. 😄

**Comment by longzheng** [comment]
@devongovett Thanks. 

Do you want me to keep the tests I added to `manipulation.test.js`?

Do you still want me to add some separate tests to `ZonedDateTime.test.js`?

**Comment by longzheng** [comment]
@devongovett Ping, just following up my last question. Hoping to get this PR merged since it is a pretty serious bug.

**Review by snowystinger — APPROVED** [review]
lgtm, thanks for the fix and tests

**Review by LFDanLu — APPROVED** [review]
LGTM, we can always shift the tests around later but IMO it should be fine as is

**Pull request merged**
