### PR TITLE
Add custom cursor icons back

### PR DESCRIPTION
**Pull request by snowystinger**
Closes 

Adds custom cursor icons back
We addressed parcel issue with a workaround to prevent Parcel from overwriting its assets that it loads into both browser and node environment. See https://github.com/parcel-bundler/parcel/issues/5985#issuecomment-1480331472 for more information

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Review by LFDanLu — COMMENTED** [review]
Hm, something up with the docs build not sure what, but I did verify the the custom icons work locally

**Review by ktabors — APPROVED** [review]
Fantastic!

**Review by LFDanLu — APPROVED** [review]
LGTM, there is a grey outline around the cursor in Safari but should be fine IMO

**Comment by snowystinger** [comment]
following up on the Safari scaled up issue

**Pull request merged**
