### PR TITLE
Update lightningcss

### PR DESCRIPTION
**Pull request by snowystinger**
Closes https://github.com/adobe/react-spectrum/issues/3991

Figured it was a good opportunity to update parcel as well. However, if we want to restrict it, I can do that as well.

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Review by ktabors — DISMISSED** [review]
The update looks fine. Not sure the best way to test this, other than docs and storybook build and thinks look correct. I assume Chromatic was run and everything passes?

**Comment by snowystinger** [comment]
> The update looks fine. Not sure the best way to test this, other than docs and storybook build and thinks look correct. I assume Chromatic was run and everything passes?

Thanks for the reminder, Chromatic shows bad. We have some new specificity collisions

**Review by devongovett — APPROVED** [review]
Tested link in Safari. looks good

**Review by LFDanLu — APPROVED** [review]
LGTM, link shows double underline when focused now and chromatic looks good. Maybe a opportunity to use the docs-differ to check that the rest of the docs don't have any unforeseen visual changes

**Comment by snowystinger** [comment]
ran docs differ, seems good to me

**Pull request merged**
