### PR TITLE
feat: add support for Devanagari & Bengali decimal numbering systems

### PR DESCRIPTION
**Pull request by Rocss**
Closes  https://github.com/adobe/react-spectrum/issues/6623

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

## 🧢 Your Project:

Adobe Express

### CODE REVIEW

**Comment by Rocss** [comment]
Would be nice to get a PR preview link in order for our g18n team to test before marking it as ready for review

**Comment by snowystinger** [comment]
> Would be nice to get a PR preview link in order for our g18n team to test before marking it as ready for review

Unfortunately, we cannot do that on the PR. The best thing to do, if you're on a time crunch, would be to build the project locally, then link the built code into your project. You can use our `verdaccio` script to do this, or you can use any number of other methods to link through your package manager.

Once we merge into main, we'll have a link to a storybook here as well as a nightly build of the packages. I doubt this will make it into our next release as we've just wrapped up testing for that. So we should have plenty of time for testing this off the nightly.

**Review by snowystinger — COMMENTED** [review]
We should add the new ones to https://github.com/adobe/react-spectrum/blob/b46d23b9919eaec8ab1f621b52beced82e88b6ca/packages/dev/docs/pages/react-aria/home/I18n.tsx#L185

**Comment by snowystinger** [comment]
We'll need to do checks with https://github.com/adobe/react-spectrum/pull/6520/files as well

**Pull request closed without merging**
