### PR TITLE
issue-2216: setting null to value should reset NumberField to blank

### PR DESCRIPTION
**Pull request by lishichengyan**
Closes https://github.com/adobe/react-spectrum/issues/2216

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Check if setting `null` to value resets `NumberField` to blank, I've added a storybook example & a test for this in the PR.

Before - 
Screen Shot 2022-11-03 at 11 43 39 AM

After clicking the Reset button - 
Screen Shot 2022-11-03 at 11 43 45 AM

### CODE REVIEW

**Review by reidbarber — COMMENTED** [review]
Looks like there are a few lint issues:

```
[1] /home/circleci/react-spectrum/packages/@react-spectrum/numberfield/stories/NumberField.stories.tsx
[1]   258:49  error  React Hook "useState" is called in function "renderControlledState" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter. React Hook names must start with the word "use"  react-hooks/rules-of-hooks
[1]   264:7   error  The closing bracket must be placed after the last prop{{details}}                                                                                                                                                                                            react/jsx-closing-bracket-location
[1]   266:18  error  Strings must use singlequote                                                                                                                                                                                                                                 quotes
[1]   268:7   error  The closing bracket must be placed after the last prop{{details}}                                                                                                                                                                                            react/jsx-closing-bracket-location
[1] 
[1] /home/circleci/react-spectrum/packages/@react-spectrum/numberfield/test/NumberField.test.js
[1]   2169:22  error  Strings must use singlequote                                       quotes
[1]   2171:11  error  The closing bracket must be placed after the last prop{{details}}  react/jsx-closing-bracket-location
```

For that first one, you can declare that function at the bottom of the file, then render it (similar to `NumberFieldControlled` and others)

**Comment by lishichengyan** [comment]
> Looks like there are a few lint issues:
> 
> ```
> [1] /home/circleci/react-spectrum/packages/@react-spectrum/numberfield/stories/NumberField.stories.tsx
> [1]   258:49  error  React Hook "useState" is called in function "renderControlledState" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter. React Hook names must start with the word "use"  react-hooks/rules-of-hooks
> [1]   264:7   error  The closing bracket must be placed after the last prop{{details}}                                                                                                                                                                                            react/jsx-closing-bracket-location
> [1]   266:18  error  Strings must use singlequote                                                                                                                                                                                                                                 quotes
> [1]   268:7   error  The closing bracket must be placed after the last prop{{details}}                                                                                                                                                                                            react/jsx-closing-bracket-location
> [1] 
> [1] /home/circleci/react-spectrum/packages/@react-spectrum/numberfield/test/NumberField.test.js
> [1]   2169:22  error  Strings must use singlequote                                       quotes
> [1]   2171:11  error  The closing bracket must be placed after the last prop{{details}}  react/jsx-closing-bracket-location
> ```
> 
> For that first one, you can declare that function at the bottom of the file, then render it (similar to `NumberFieldControlled` and others)

sorry, i didn't run yarn lint locally. i'll fix them in a new commit. thanks!

**Comment by snowystinger** [comment]
GET_BUILD

**Review by snowystinger — APPROVED** [review]
lgtm, will probably need to wait until after the coming release before merging so it gets a testing cycle

**Comment by lishichengyan** [comment]
> 

great, thanks for reviewing

**Review by reidbarber — APPROVED** [review]

**Pull request merged**
