### PR TITLE
Add suport for the `textarea` in `useTextField`

### LINKED ISSUE #652: Support `textarea` in `useTextField`
# 🙋 Feature Request

As text inputs & textareas are super similar it would be great to add intuitive support for textareas to `useTextField`

## 🤔 Expected Behavior

Being able to spread `inputProps` onto `<textarea/>`

## 😯 Current Behavior

Currently, `type` prop is always returned and thus it lands on the textarea node when spreading as-is.

## 💁 Possible Solution

Add `inputElementType` prop - similar to `labelElementType`.

### PR DESCRIPTION
**Pull request by maksimsemenov**
Adds `inputElementType` prop to `useTextField` and if it is not `input` it does not include `type` and `pattern` into `inputProps`.

Closes #652 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [x] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:
Set `inputElementType` property of the `useTextField` to `textarea` and make sure, that `type` and `pattern` props are
not included into `inputProps` that are returned from the hook.

### CODE REVIEW

**Comment by LFDanLu** [comment]
@maksimsemenov Hrm sorry, looks like I must have goofed something up when pushing lint fixes to your fork, gonna try and reset back to what you had initially

**Comment by maksimsemenov** [comment]
> @maksimsemenov Hrm sorry, looks like I must have goofed something up when pushing lint fixes to your fork, gonna try and reset back to what you had initially

Oops, sorry I missed them. Thanks for fixing.

Maybe it worth adding pre-commit hook? Or pre-push?

**Comment by LFDanLu** [comment]
Definitely a idea worth considering, maybe using something like husky.

**Comment by devongovett** [comment]
Thank you!

**Pull request merged**
