### PR TITLE
fix: useSelect trigger label

### LINKED ISSUE #4920: `useSelect` merges `label` and `aria-label`
### Provide a general summary of the issue here

When you use `useSelect({ label: 'foo', aria-label: 'bar' })` the trigger prop becomes the label `foo bar`.

### 🤔 Expected Behavior?

the screen reader should read out `bar`

### 😯 Current Behavior

the screen reader reads out `foo bar`

### 💁 Possible Solution

don't merge labels

### 🔦 Context

You might have a select that has emojis or similar in the label, in that case you would like to create a screen reader friendly alternative.

This is currently not possible.

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/strange-sound-gmlr66

### Version

3.16.1

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

Linux

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by jguddas**
Closes #4920 

## Example with `value="Cat"` and `label="Favorite 🐹"`
There is also an element with the id `hello` which contains `Hello World` for this example.
||native select with chrome plus voiceover|this PR|`3.21.0` of `react-aria`s `useSelect`|`3.27.0` of `react-aria`s `useSelect`|
|---|---|---|---|---|
|no additional props|`Cat, Favorite 🐹`|same as native|`Favorite 🐹 Cat`|`Cat Favorite 🐹`|
|`aria-label="Favorite Animal"`|`Cat, Favorite Animal`|same as native|`Favorite 🐹 Favorite Animal Cat`|`Cat Favorite 🐹 Favorite Animal`|
|`aria-labelledby="hello"`| `Cat, Hello World`|same as native|`Hello World Favorite 🐹 Cat`|`Cat Hello World Favorite 🐹`|
|`aria-label="Favorite Animal"` and<br>`aria-labelledby="hello"`| `Cat, Hello World`|`Cat Hello World`|`Hello World Favorite 🐹 Favorite Animal Cat`|`Cat Hello World Favorite 🐹 Favorite Animal`|

## The logic

The trick is to use a self-referencing `aria-label` that includes a comma to suggest a little pause to the screen reader.

```tsx
"aria-label": `, ${ariaLabel ?? ''}`
"aria-labledby": [
  valueId,
  !(ariaLabelledBy && ariaLabel) && targetId,
  !(ariaLabelledBy || ariaLabel) && labelId,
  ariaLabledBy,
].filter(Boolean).join(' ')
```

||`aria-label="Favorite Animal"`|`aria-label={undefined}`|
|---|---|---|
|`aria-labelledby="hello"`|`${valueId} ${ariaLabelledBy}`|`${valueId} ${targetId} ${ariaLabelledBy}`|
|`aria-labelledby={undefined}`|`${valueId} ${targetId}`|`${valueId} ${targetId} ${labelId}`|

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Comment by jguddas** [comment]
This is still super WIP, but I would still love to hear your feedback regarding my approach to the problem, @devongovett and @snowystinger.

**Comment by snowystinger** [comment]
Hey! thanks for the extremely detailed description.

I think this seems like a fine approach. @majornista do you have any opinions here? You did the overhaul to our labelling in https://github.com/adobe/react-spectrum/pull/4191/files#diff-7e599b9da08764665cb17b548a888c3caaa9a9fb472d331de37619fec7f3318e recently.

**Comment by snowystinger** [comment]
GET_BUILD

**Comment by jguddas** [comment]
looks good, ready to go from my part :+1:

**Review by reidbarber — APPROVED** [review]
LGTM, thanks for the PR and thorough description!

**Review by LFDanLu — APPROVED** [review]
LGTM, tested via Talkback and VO. Will add a story to facilitate testing of all combinations tomorrow.

**Pull request merged**
