### PR TITLE
Removes padding on first li link element

### LINKED ISSUE #2212: Breadcrumb first crumb should not have padding
# 🐛 Bug Report 

We implemented Breadcrumbs across several "pages" within our app and noticed that there is padding applied to a crumb text to provide spacing between the text and the delimiter `>`. It seems to be a bug or potential oversight that there is an opinionated padding on the external sides of the element.

## 🤔 Expected Behavior

In my opinion, this padding does not belong on the first child/crumb of the Breadcrumbs component.

image

## 😯 Current Behavior

image

## 💁 Possible Solution

For the first "crumb", set `padding-left: 0;`.

## 🔦 Context

We have several routes that use the breadcrumb component. Our designer has pointed out the extra padding, causing the breadcrumbs to not be left aligned with the other components on the page. While we could override it in the few places we implement breadcrumbs, it seems less scaleable a solution than fixing it at the source. If we did override it, we may also forget to do so when adding a new Breadcrumb, which will be extra work to remedy.

## 💻 Code Sample

https://codesandbox.io/s/stupefied-https-wuc8d?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.12.0
| Browser          | Chrome Version 92.0.4515.131 (Official Build) (x86_64)
| Operating System | Mac OSX 11.5.1

## 🧢 Your Company/Team

Adobe Commerce

### PR DESCRIPTION
**Pull request by sirugh**
Closes #2212 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Run storybook, see that first breadcrumb has 0 left padding but no other crumbs are affected.

## 🧢 Your Project:

https://git.corp.adobe.com/commerce-sales-channels/sales-channels-ui

### CODE REVIEW

**Comment by snowystinger** [comment]
We'll have more information on plans for this in the new year. Sorry it's taken a while.

**Comment by ktabors** [comment]
For the build to pass you'll need to [sign the CLA](http://opensource.adobe.com/cla.html), then close and re-open this PR to let it refresh.

**Comment by sirugh** [comment]
@ktabors I opened this over 2 years ago! Is it even still relevant? I've signed the CLA (though I probably already had done previously, and also I am an Adobe employee)

**Comment by snowystinger** [comment]
closing, see comment https://github.com/adobe/react-spectrum/issues/2212

thanks for your understanding

**Pull request closed without merging**
