### PR TITLE
Fix Combobox HCM non-disabled

### PR DESCRIPTION
**Pull request by snowystinger**
Closes 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Review by LFDanLu — DISMISSED** [review]
LGTM, verified that express/non-express non-disabled combobox has a consistent border color in WHCM

**Review by yihuiliao — DISMISSED** [review]
lgtm

**Review by ktabors — CHANGES_REQUESTED** [review]
I found an issue on mobile where the isQuiet and isDisabled, the button is missing the underline. I confirmed this is new. I think it came in with the PR this is "patching."
image

**Review by ktabors — APPROVED** [review]
That fixed it!

**Review by LFDanLu — APPROVED** [review]
LGTM, tested in desktop and Chrome android

**Pull request merged**
