### PR TITLE
refactor: isolate Table stories

### PR DESCRIPTION
**Pull request by ryo-manba**
related to https://github.com/adobe/react-spectrum/issues/5514

## ✅ Pull Request Checklist:
- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Confirm that nothing has changed by looking at the Table from the storybook.

### CODE REVIEW

**Review by LFDanLu — DISMISSED** [review]

**Review by snowystinger — APPROVED** [review]

**Comment by LFDanLu** [comment]
I pushed an update to fix a conflict here, but it looks like many of the other PRs handling this story refactor are running into a similar conflict issue when any of these is merged in. Do you mind consolidating the story refactors into a single PR instead just to make handling these conflicts easier?

**Review by LFDanLu — APPROVED** [review]

**Review by snowystinger — APPROVED** [review]

**Comment by ryo-manba** [comment]
@LFDanLu 
Sorry for the delay in replying.
I'll try to combine them into one, as there are indeed conflicts in many of the PRs that are out there right now!

**Comment by ryo-manba** [comment]
@LFDanLu 
I've consolidated the PRs into this one: https://github.com/adobe/react-spectrum/pull/5651. This should address the conflict issues we were experiencing with the individual story refactors. Looking forward to your review!

**Comment by LFDanLu** [comment]
Thank you! I'll take a look soon.

**Pull request merged**
