### PR TITLE
Replace "start" with "flex-start" in CSS

### LINKED ISSUE #768: There are some css warnings
# 🐛 Bug Report 

image

## 🤔 Expected Behavior

After installing, the button was displayed according to the document

https://react-spectrum.adobe.com/react-spectrum/getting-started.html

## 😯 Current Behavior

Here is the code
```
import React from 'react';
import './App.css';
import {
  Provider,
  defaultTheme,
  Button
} from '@adobe/react-spectrum';

function App() {
  return (
    <div className="App">
      <Provider theme={defaultTheme}>
        <Button
          variant="cta"
          onPress={() => alert('Hey there!')}>
          Hello React Spectrum!
        </Button>
      </Provider>
    </div>
  );
}

export default App;
```

image

## 💁 Possible Solution

I think it's enough to change the code as below
`fill-available` -> `stretch`
`start` -> `flex-start`

I think the corresponding file is here
`react-spectrum/packages/@adobe/spectrum-css-temp/components/modal/index.css`

`react-spectrum/packages/@adobe/spectrum-css-temp/components/tray/index.css`

## 🔦 Context

I want to get rid of warnings and be aware of warnings and errors that I really want to see

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.0.2
| Browser          | Chrome（latest）
| Operating System | MacOS Catalina（10.15.5）

I submitted my first assignment.
Please let me know if the submission method is incorrect.
Thank you for confirmation.

### PR DESCRIPTION
**Pull request by msabramo**
Currently when using react-spectrum eslint will show a warning about `start` having mixed support:

```
./node_modules/@react-spectrum/breadcrumbs/dist/main.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./node_modules/@rea
Warning

(1:745) start value has mixed support, consider using flex-start instead

./node_modules/@react-spectrum/breadcrumbs/dist/main.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./node_modules/@rea
Warning

(1:83) start value has mixed support, consider using flex-start instead
```

This was reported in #956, #844 and #768.

This fixes those warnings.

This takes over from https://github.com/adobe/react-spectrum/pull/1793 (from @MarkRedeman), which has been inactive since April 2021 and also borrows some changes from https://github.com/adobe/react-spectrum/pull/686 that never got applied.

A total of 5 files are modified:

```
$ git diff --stat main...HEAD
 packages/@adobe/spectrum-css-temp/components/breadcrumb/index.css | 4 ++--
 packages/@adobe/spectrum-css-temp/components/coachmark/index.css  | 2 +-
 packages/@adobe/spectrum-css-temp/components/dialog/index.css     | 2 +-
 packages/@adobe/spectrum-css-temp/components/menu/index.css       | 6 +++---
 packages/@adobe/spectrum-css-temp/components/sidenav/index.css    | 2 +-
 5 files changed, 8 insertions(+), 8 deletions(-)
```

Closes #768

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Review by reidbarber — APPROVED** [review]
LGTM, thanks for cleaning up these!

Verified behavior of `flex-start`: 
>  For items that are not children of a flex container, this value is treated like start.

https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content#values

**Review by snowystinger — APPROVED** [review]

**Comment by reinasalondra** [comment]
2352-contextual-help

> Cierra [# 2352](https://github.com/adobe/react-spectrum/issues/2352)
> 
> ##  Lista de verificación de solicitud de extracción:
> * [ ] Enlace incluido al [problema de GitHub de React Spectrum](https://github.com/adobe/react-spectrum/issues) correspondiente .
> * [ ]  Se agregaron / actualizaron pruebas unitarias y un libro de cuentos para este cambio (para un nuevo código o código que ya tiene pruebas).
> * [ ]  Instrucciones de prueba completas.
> * [ ]  Documentación actualizada (si ya existe para este componente).
> * [ ] Consulte las prácticas de accesibilidad para esta función: [prácticas de Aria](https://www.w3.org/TR/wai-aria-practices-1.1/)
> 
> ##  Instrucciones de prueba:
> image
> 
> Libro de cuentos: https://reactspectrum.blob.core.windows.net/reactspectrum/c61511f17f3a55ac44dcb2ce9b104373f272fb60/storybook/index.html?path=/story/contextualhelp--default



> Cierra [# 2352](https://github.com/adobe/react-spectrum/issues/2352)
> 
> ##  Lista de verificación de solicitud de extracción:
> * [ ] Enlace incluido al [problema de GitHub de React Spectrum](https://github.com/adobe/react-spectrum/issues) correspondiente .
> * [ ]  Se agregaron / actualizaron pruebas unitarias y un libro de cuentos para este cambio (para un nuevo código o código que ya tiene pruebas).
> * [ ]  Instrucciones de prueba completas.
> * [ ]  Documentación actualizada (si ya existe para este componente).
> * [ ] Consulte las prácticas de accesibilidad para esta función: [prácticas de Aria](https://www.w3.org/TR/wai-aria-practices-1.1/)
> 
> ##  Instrucciones de prueba:
> imagen
> 
> Libro de cuentos: https://reactspectrum.blob.core.windows.net/reactspectrum/c61511f17f3a55ac44dcb2ce9b104373f272fb60/storybook/index.html?path=/story/contextualhelp--default

**Comment by deadcoder0904** [comment]
@snowystinger was this ever released? bcz i still get warnings in my console that take up a lot of space :(

**Comment by snowystinger** [comment]
We are in the middle of release planning right now. But good news, your console won't run out of space :)

**Comment by msabramo** [comment]
It appears that this was released in React Spectrum 3.16?

**Comment by snowystinger** [comment]
yes, should be

**Pull request merged**
