### PR TITLE
Fix LabeledValue contextual help alignment for side label

### PR DESCRIPTION
**Pull request by reidbarber**
Found in testing.

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Go to LabeledValue -> Contextual Help story and enable side label position via controls.

Verify that label and contextual help are now aligned.

### CODE REVIEW

**Review by devongovett — APPROVED** [review]
Did you run chromatic?

**Comment by snowystinger** [comment]
Chromatic shows that the two without contextual help the label and the value are now not aligned :(
It's more obvious if you look at the large scale without the green overlay of the diff on it in chromatic

Both the label and the field should have the same margin/padding on top

**Comment by reidbarber** [comment]
> Chromatic shows that the two without contextual help the label and the value are now not aligned :( It's more obvious if you look at the large scale without the green overlay of the diff on it in chromatic
> 
> Both the label and the field should have the same margin/padding on top

@snowystinger Can you take another look? IMO the updated style matches the other side-labeled components better(they also use `flex-start`).

**Review by ktabors — APPROVED** [review]
LGTM on iPhone Safari, OSX Safari, and OSX Firefox.

**Review by snowystinger — APPROVED** [review]

**Pull request merged**
