### PR TITLE
August release

### PR DESCRIPTION
**Pull request by devongovett**
versions and fixes

### CODE REVIEW

**Review by snowystinger — APPROVED** [review]

**Review by LFDanLu — APPROVED** [review]

**Review by yihuiliao — APPROVED** [review]

**Comment by levrik** [comment]
Is there a changelog available for these release somewhere?

**Comment by snowystinger** [comment]
Our release notes can be found here https://react-spectrum.adobe.com/releases/index.html

The release you're commenting on though won't be in there because it was only for spectrum 2 pre release packages which we don't track release notes for yet externally. Any other changes that came through were patches.

Was there something in particular you were asking about or just clarification? If the release caused a regression, let us know in our Issues.

**Comment by levrik** [comment]
@snowystinger No. Just curious what the release includes as I'm depending on some of the packages and not knowing what has changed doesn't feel that great usually. Maybe there also has been a fix for something I should be aware of or so.

So nothing specific, just wondering if there's something written down to get an overview. But looks like this doesn't exist and I would have to go through commits on GitHub which is also fine.

**Comment by andrew-pledge-io** [comment]
We ran into a breaking change in the 1.3.2 release, I've created a separate issue here: https://github.com/adobe/react-spectrum/issues/6956

I understand there weren't any big changes to the public packages so adding something to the releases page is probably overkill. But maybe there can be a lighter version of release notes (like an automated CHANGELOG.md?) to go along with minor version bumps?

**Comment by snowystinger** [comment]
Yep, we're working on automating the creation of release notes/changelog. So hopefully, some day, that will be covered better.

**Pull request merged**
