### PR TITLE
Fix Illustrated Message styling

### LINKED ISSUE #6039: UX mismatch in Drop Zone IllustratedMessage component's font weight and font style
### Provide a general summary of the issue here

In Spectrum contributions - The dropzone box has 'Drag and drop' in bold.
In Spectrum React - the dropzone box has 'Drag and drop' font as regular.
Also, the description text in Spectrum contribution is set as regular font, but in Spectrum react it is displayed in Italics.

image

### 🤔 Expected Behavior?

The design should follow the spectrum contribution guidelines. 

### 😯 Current Behavior

the dropzone box has 'Drag and drop' font as regular

### 💁 Possible Solution

_No response_

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

[As you can see in this example](https://codesandbox.io/p/sandbox/react-spectrum-template-syueo?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltmk84uy00063b6l3u6116gl%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltmk84ux00023b6lr8xc6z6c%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltmk84ux00033b6lg5vuthzo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltmk84ux00053b6l828dqy7d%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltmk84ux00023b6lr8xc6z6c%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltmk84ux00013b6lpszc91f3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cltmkxr6c00023b6lns91731x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A63%252C%2522endColumn%2522%253A2%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cltmk84ux00023b6lr8xc6z6c%2522%252C%2522activeTabId%2522%253A%2522cltmkxr6c00023b6lns91731x%2522%257D%252C%2522cltmk84ux00053b6l828dqy7d%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltmk84ux00043b6lokofrsv0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltmk84ux00053b6l828dqy7d%2522%252C%2522activeTabId%2522%253A%2522cltmk84ux00043b6lokofrsv0%2522%257D%252C%2522cltmk84ux00033b6lg5vuthzo%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltmk84ux00033b6lg5vuthzo%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

the font weight of heading is regular and the font style of content is set to italic.

### Version

3.33.1

### What browsers are you seeing the problem on?

Chrome, Safari

### If other, please specify.

_No response_

### What operating system are you using?

Mac

### 🧢 Your Company/Team

Adobe/Marketo

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by yihuiliao**
Closes #6039 

[chromatic link
](https://www.chromatic.com/build?appId=5f0dd5ad2b5fc10022a2e320&number=726)

all the changes in chromatic are to be expected with this update

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

### CODE REVIEW

**Review by reidbarber — APPROVED** [review]
LGTM

**Review by LFDanLu — APPROVED** [review]
LGTM

**Comment by snowystinger** [comment]
Where'd the values come from?
It doesn't quite look the same to me, but maybe I'm looking in the wrong place. Can't remember how to change color versions in XD
Screenshot 2024-04-02 at 9 48 07 AM

**Comment by yihuiliao** [comment]
> Where'd the values come from? It doesn't quite look the same to me, but maybe I'm looking in the wrong place. Can't remember how to change color versions in XD

Good catch, I'll open a separate PR for the colors

**Pull request merged**
