### PR TITLE
Use correct document and window object

### PR DESCRIPTION
**Pull request by slye-stripe**
Closes 
https://github.com/adobe/react-spectrum/issues/3350
https://github.com/adobe/react-spectrum/discussions/2237

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 🧢 Your Project:

Stripe - Connect Embedded Components

### CODE REVIEW

**Comment by LFDanLu** [comment]
Thanks for the draft PR and RFC. The team discussed this PR today along with a related [PR](https://github.com/adobe/react-spectrum/pull/4694) (credit to @ritz078) and had a couple of comments:

1. We would be open to accepting this change incrementally, but we are worried about accidentally breaking the work done here as time goes on and additional changes are made in the codebase. Ideally we'd have tests and/or a lint rule that  would help us know if we've broken something.
2. There are concerns about scenarios where we don't have access to a element ref with which to look up the document/window. For instance `useFocusVisible` tracks/updates the interaction modality via document level listeners (and thus doesn't have a element ref) but if we want to handle iframes then we'd need to have a separate piece of state for each level alongside attaching listeners on the target frame from which useFocusVisible is being called.

**Comment by slye-stripe** [comment]
@LFDanLu 
1. By incrementally, do you mean starting on a package at a time, i.e. `interactions` -> `focus`, etc. or a file at a time approach? Would the lint rule be to throw if `document` or `window` is used instead of `getDocument` or `getWindow`?
2. We are actually facing an issue with `useFocusVisible` exactly because of the aforementioned issue. We have added an extra optional argument to it in our own patch to accept an element and get the corresponding document and window. There's also the additional issue where there's a single state as you mentioned. Is this something that your team would be able to help us with?

**Comment by LFDanLu** [comment]
@slye-stripe 

> By incrementally, do you mean starting on a package at a time, i.e. interactions -> focus, etc. or a file at a time approach? 

By incrementally, I meant the team recognizes that shifting to the correct document and window object would need to be done in many other places beyond what was covered in the PR but we'd be ok with what you've provided as a starting point.

> Would the lint rule be to throw if document or window is used instead of getDocument or getWindow?

Yep, just something to help guard against reversing/break the progress you've helped us make with this conversion. 

> There's also the additional issue where there's a single state as you mentioned. Is this something that your team would be able to help us with?

The team will need to do some prioritization juggling here so I don't have a good answer for you yet, but will get back to you on that.

**Comment by slye-stripe** [comment]
@LFDanLu I started the first PR here - https://github.com/adobe/react-spectrum/pull/5096#pullrequestreview-1632067315, who should I tag as reviewers going forward? Should we set up a Slack channel for easier communication?

**Comment by LFDanLu** [comment]
@slye-stripe The team will jump in to review the PR individually as it progresses, no need to tag anyone specifically. We also discussed this some more in our grooming session just now and there were some uncertainty on what exactly was breaking here with iframes. Do you have a simple example/sandbox that you could share with us to illustrate the issue? We wanna see if we can suggest any alternatives if any exist and would be happy to meet/chat (either via Slack or whatever you feel most comfortable with) from there.

**Comment by slye-stripe** [comment]
@LFDanLu This is the sandbox I created - https://codesandbox.io/s/exciting-hellman-z73wv6?file=/src/App.tsx

**Comment by snowystinger** [comment]
Just to triple check, this is very close to your actual setup? you will have code outside the iframe which creates the iframe and then renders into the iframe?

As opposed to only existing inside the iframe and someone else will render the iframe?

**Comment by slye-stripe** [comment]
@snowystinger Yea, the issue is that we have our main javascript code running on an iframe and dialogs/drawers/popovers/tooltips are rendered in separate iframes. However, using ReactDOM.createPortal, the javascript context is still executed on the main iframe cc @michaelphines-stripe

**Comment by slye-stripe** [comment]
Hey @snowystinger @LFDanLu wanted to check if there are any updates regarding this?

**Comment by snowystinger** [comment]
Thanks for the ping, checking in with team again. Will hopefully have a reply to you soon. Just as a heads up though, responses may slow for a week or so as we do release prep.

**Comment by snowystinger** [comment]
Hey, we talked about this more today and the complexity keeps increasing. We think it'd be easiest to talk about this in slack.  We'll send you an invite.

**Pull request closed without merging**
