### PR TITLE
Remove invalid selector characters from React.useId

### PR DESCRIPTION
**Pull request by dkryaklin**
Closes 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Comment by devongovett** [comment]
I don't think we should modify the ids generated by react (the colons are generated by react), or we could easily get into a situation where they conflict.

I believe colons are allowed in ids, but if you're using `querySelector` you have to escape them. You can also use `getElementById` instead. Any of these should work:

```js
document.getElementById('foo-:bar:');
document.querySelector('#foo-\\:bar\\:')
document.querySelector('#' + CSS.escape('foo-:bar:'));
```

**Comment by dkryaklin** [comment]
> I don't think we should modify the ids generated by react (the colons are generated by react), or we could easily get into a situation where they conflict.
> 
> I believe colons are allowed in ids, but if you're using `querySelector` you have to escape them. You can also use `getElementById` instead. Any of these should work:
> 
> ```js
> document.getElementById('foo-:bar:');
> document.querySelector('#foo-\\:bar\\:')
> document.querySelector('#' + CSS.escape('foo-:bar:'));
> ```

Thanks! I totally get your point about colons and querySelector. But considering that colons are reserved for pseudo-classes in CSS, it might simplify things if we escape these special characters at the library level instead.

This way, the IDs would still be valid in HTML, and the handling code wouldn't need to account for special characters, making the process more intuitive and less prone to errors.

Please have a look at this code:
```javascript
notifications
  .getButton()
  .should('have.attr', 'aria-labelledby')
  .then((ariaLabelledBy) => {
    cy.get(`#${ariaLabelledBy}`)
      .should('match', 'label')
  });
```

So I don't really want to go and find every single place where I should fix (escape) myself an invalid id value.

Also, if you are interested here is code from React: https://github.com/facebook/react/commit/4729ff6d1f191902897927ff4ecd3d1f390177fa#diff-d00892997f98c06b59b26eaf1c703e784fd4a62a74338bef439f26b6d23d39c4R234-R251
Not sure why they decided to choose colons. But I think it is safe to assume that removing the first and last characters would not hurt.

Just my two cents, hoping it helps!

**Comment by snowystinger** [comment]
Here's the same issue in React https://github.com/facebook/react/issues/26839 just as an fyi

**Comment by dkryaklin** [comment]
@devongovett, I have updated the pull request to align with your previous comment. Additionally, I've raised the issue on the React repository, which can be viewed [here](https://github.com/facebook/react/issues/26839#issuecomment-1618244898).

I would appreciate your thoughts on this approach. Please share your feedback when you have a moment.

**Comment by beamery-tomht** [comment]
bump, facing this issue too

**Comment by devongovett** [comment]
Closing. We don't want to override react's behavior here. Please see the react issue https://github.com/facebook/react/issues/26839, or the comment above https://github.com/adobe/react-spectrum/pull/4738#issuecomment-1614894496 for workarounds.

**Pull request closed without merging**
