### PR TITLE
TagGroup shows FocusRing when maxRows and isEmpty

### PR DESCRIPTION
**Pull request by ktabors**
Closes #justfixit

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Goto the "maxRows + onRemove" story.
Use the keyboard to focus a tag in the TagGroup.
Use 'Delete' key to delete all the tags.
When everything is deleted, the empty TagGroup gets focus and shows a FocusRing.

## 🧢 Your Project:
RSP

### CODE REVIEW

**Review by snowystinger — COMMENTED** [review]
Is there a browser i should try for this? and what commit on main is showing the issue? because I tried on Devon's PR adding the taggroup docs as a reference, and I'm not seeing a focus ring appear.

Should I delete with the mouse or with keyboard? Do I need to have in collapsed or uncollapsed?

**Comment by ktabors** [comment]
> Is there a browser i should try for this? and what commit on main is showing the issue? because I tried on Devon's PR adding the taggroup docs as a reference, and I'm not seeing a focus ring appear.
> 
> Should I delete with the mouse or with keyboard? Do I need to have in collapsed or uncollapsed?

I found this in OSX Chrome. It's also in Safari. I updated the instructions to specify use a keyboard.

**Comment by dannify** [comment]
FYI I am seeing the focus ring without this code change so I am not sure what it is fixing.

**Comment by ktabors** [comment]
TagGroup maxRows no FocusRing

**Review by LFDanLu — APPROVED** [review]

**Review by yihuiliao — APPROVED** [review]

**Review by dannify — APPROVED** [review]

**Pull request merged**
