### PR TITLE
Fix edge cases in DatePicker with min/max dates and eras

### LINKED ISSUE #3109: DatePicker breaks when setting date to December of year 9999
# 🐛 Bug Report 

When selecting or setting date to December of 9999, the component breaks.

## 🤔 Expected Behavior

Allow user to select end of time/date 9999-12-31

## 😯 Current Behavior
- Go to https://react-spectrum.adobe.com/react-spectrum/DatePicker.html
- Set date in the simple DatePicker to November 9999 
image

- Click Next icon to December of 9999 
image

- Error in console log:
image

## 💁 Possible Solution

N/A

## 🔦 Context

At Adobe, current practice of Pricing team is to default End Date of a new pricing to end of time 9999-12-31. This process is migrating from SAP ECC to another UI that uses Spectrum libraries. In Spectrum V2, 9999-12-31 is working fine but V2 DatePicker is not very pretty when render inside of V3 Dialog/containers. 

## 💻 Code Sample

N/A

## 🌍 Your Environment

N/A

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

Adobe/EnterpriseCommerce

## 🕷 Tracking Issue (optional)

N/A

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #3109.

This fixes a few edge cases:

* Minimum and maximum dates in a calendar system, e.g. we currently support up to year 9999 in the Gregorian calendar, and some calendar systems have minimum dates as well (e.g. we only support back to the Meiji era (~1868) in the Japanese calendar). Now we constrain the dates within the valid range of the calendar system.
* Dates in the BC era of the Gregorian calendar should display the era wherever they are shown.
* Noticed a weird bug in Firefox where sometimes clicking on a segment in DatePicker would not make it editable.

## 📝 Test Instructions:

1. In DatePicker, enter a date in December of the year 9999, and open Calendar. Verify that the next button is disabled. Verify that you cannot navigate to any future dates via keyboard, etc.
2. In the date picker, change the year to 1, and press the down arrow. Verify that you are now at 1 BC (the era should appear). 
3. Change the date to January of the year 9999 BC. Open the calendar, and verify that the previous button is disabled.
4. Change the date to September of 1868. Switch the calendar system to Japanese. Open the calendar, and verify that the previous button is disabled, and the month appears to start at day 8 (on a Tuesday). This is the first supported date.
5. With dates in BC, verify that all places the date is displayed or announced include the BC era.

### CODE REVIEW

**Review by snowystinger — APPROVED** [review]
did tests in the description, those all work as described, did some smoke tests as well, nothing else came up

**Review by ktabors — COMMENTED** [review]
If I goto year 1 of the Gregorian calendar and take us into BC, I can tab to the era as a segment. If I press the up or down arrow the era goes away and nothing is focused.
image

**Review by dannify — APPROVED** [review]

**Comment by anguyenatadobe** [comment]
Hi @devongovett in which release will this fix be included?

**Comment by dannify** [comment]
No exact date yet but planning release in the next 2-3 weeks.

**Comment by devongovett** [comment]
I think another rc will be available before then though.

**Pull request merged**
