### PR TITLE
Fix drag preview not displaying text in TableView

### PR DESCRIPTION
**Pull request by ryo-manba**
Closes https://github.com/adobe/react-spectrum/issues/4895

The fix ensures that when rowHeader is not present, the drag preview displays the content of the first element, excluding checkboxes and dragButtons.

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

1. Visit http://localhost:9003/?path=/story/tableview-drag-and-drop--drag-out-of-table-without-table-header&args=selectionStyle:highlight&providerSwitcher-express=false&strict=true
2. In the Table, drag a row.
3. Verify that the text from the first column ("First name") of the dragged row is displayed in the drag preview.

### CODE REVIEW

**Comment by snowystinger** [comment]
GET_BUILD

**Review by Haeven — APPROVED** [review]
Covers all test cases and complies with best practice ⭐ Good job on this @ryo-manba

**Review by snowystinger — APPROVED** [review]
thanks for the fix!

**Review by reidbarber — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
