### PR TITLE
fix: export FocusVisibleProps

### PR DESCRIPTION
**Pull request by warsawgentleman**
Hello,
first of all thank you for amazing work!

In my project, I am building little component library and I stumbled upon such Typescript error when I tried to use `useFocusVisible` hook:

`Exported variable 'withFocusVisible' has or is using name 'FocusVisibleProps' from external module "some_path/node_modules/@react-aria/interactions/dist/types" but cannot be named.ts(4023)`

In my `tsconfig` `declaration` is set to `true`, so I guess Typescript needs to add `FocusVisibleProps` interface to bundled declaration types, but it can't because it is not exported. 

Closes: I didn't create issue

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Review by snowystinger — COMMENTED** [review]
Thanks, we'll need to export it a little further though if you don't mind.
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/index.ts#L34
and
https://github.com/adobe/react-spectrum/blob/main/packages/react-aria/src/index.ts#L55

**Comment by warsawgentleman** [comment]
> Thanks, we'll need to export it a little further though if you don't mind. https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/index.ts#L34 and https://github.com/adobe/react-spectrum/blob/main/packages/react-aria/src/index.ts#L55

Done :)

**Review by snowystinger — APPROVED** [review]
lgtm

**Comment by techquestions** [comment]
My team is also waiting for this PR. 
Could we please get a second approval on it?

**Review by devongovett — APPROVED** [review]

**Pull request merged**
