### PR TITLE
Remove 'invalid' focus styles from focused input fields

### PR DESCRIPTION
**Pull request by reidbarber**
When input fields are focused, they shouldn't have a red focus ring (the focus ring should instead match the valid state). This PR removes those styles from various input fields.

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

1. Open stories at [Form -> validationState: invalid](https://reactspectrum.blob.core.windows.net/reactspectrum/ba906442dc7e53f3c783229c02e298ef5174f731/storybook/index.html?path=/story/form--validationstate-invalid&providerSwitcher-toastPosition=bottom) and [Form -> validationState: invalid, isQuiet: true](https://reactspectrum.blob.core.windows.net/reactspectrum/ba906442dc7e53f3c783229c02e298ef5174f731/storybook/index.html?path=/story/form--validationstate-invalid-isquiet-true&providerSwitcher-toastPosition=bottom)
2. Focus on input fields and verify that focus rings are no longer red

## 🧢 Your Project:

RSP

### CODE REVIEW

**Review by snowystinger — DISMISSED** [review]

**Review by ktabors — CHANGES_REQUESTED** [review]
I went to NumberField isQuiet validationState: invalid and saw the following 
image

Since we don't have controls yet can we duplicate the story you linked to and add isQuiet?

**Comment by reidbarber** [comment]
@ktabors fixed this and added stories for quiet forms with validation states. Thanks!

**Review by ktabors — APPROVED** [review]
~~Looks good to me.~~ Just checked a couple other browsers and found an issue. Will keep testing.
On mobile it looks like your most recent build fixed the following too thick focus when not focused, but when I open the top one, where the blue is there is a flicker as the tray opens. Since it's a flicker and being hidden do we care?
image
Another edit: With the newest build I just got the blue line after the red to show up on iOS Safari.

**Comment by reidbarber** [comment]
@ktabors great find. Cleaning up the mobile combobox issue now. It was a bit of a different case since it's a fake input.

**Comment by reidbarber** [comment]
Closing for #3384

**Pull request closed without merging**
