### PR TITLE
Fix useTagGroup set aria-live to 'polite' for better screen reader support

### PR DESCRIPTION
**Pull request by ryo-manba**
The current `useTagGroup` implementation has `aria-live` set to `off`, which means updates aren't announced when an input element is outside the grid, as seen in the [APG example](https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/layout-grids/).

image

According to the [specification](https://www.w3.org/TR/wai-aria-1.2/#aria-live), even if `aria-live` is set to `'off'`, screen readers will read the updates if the region is focused.

> Indicates that updates to the region should not be presented to the user unless the user is currently focused on that region.

Therefore, setting `aria-live: 'polite'` only when focused seems unnecessary.

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

### CODE REVIEW

**Review by snowystinger — COMMENTED** [review]
I'm not sure I understand the comparison between the APG example and our implementation. The aria-live region in the APG example is for the "last change to tags" hidden region, whereas ours is the tag group itself. So I think they are a little different.

I think what you're suggesting is that `aria-live` could be left as `off` because it'll announce when it has focus anyways. If we set it to be `polite` always, then it will always announce, regardless of if focus is in the group or not.

Apologies if I've misunderstood.

**Comment by snowystinger** [comment]
Thanks, I did some digging, and this particular line of code is 6+ years old. I'll see if anyone can remember why we have it.

**Comment by ryo-manba** [comment]
It looks like these commits might be related.

- [Commit in react-spectrum](https://github.com/adobe/react-spectrum/commit/6da8fb542e77cacf46c54e451d562e929799e7b3)
- [Commit in coral-spectrum](https://github.com/adobe/coral-spectrum/commit/fd366c2e06cd7fff5e9a9d140ecc78ffe5b5c263)

**Comment by majornista** [comment]
I tend to be careful with leaving static `aria-live="polite"` attributes on things. In this case, if the user isn’t actively interacting with the TagList, I think we want to avoid out-of-band live region announcement of new Tags. This sort of logic was added to preemptively avoid the sort of out of band announcement of content marked with `aria-live="polite"` that would overflow the VoiceOver buffer and interfere with a users ability to read content in other tabs when a W3C spec was open in a Chrome browser tab:
- https://github.com/w3c/respec/issues/1456
- https://github.com/w3c/aria-practices/issues/715

**Comment by ryo-manba** [comment]
Thank you, @majornista , for highlighting the caution needed with static `aria-live="polite"`.
As @snowystinger mentioned, following the APG example might be a viable approach. If we opt for `aria-live="off"`, then settings like `aria-atomic` and `aria-relevant` would become unnecessary.

However, the [TagGroup documentation](https://react-spectrum.adobe.com/react-aria/TagGroup.html) notes:

> Accessible – Follows the ARIA grid pattern, with additional selection announcements via an ARIA live region.

So, if we're considering adapting the announcement behavior, I believe we should test the approach I suggested.

**Comment by snowystinger** [comment]
```
export const ExternalControl: TagGroupStory = {
  render: () => (
    <App />
  )
};

let index = 2;
let App = () => {
  let [items, setItems] = useState<Array<{key: string, label: string}>>([{key: '1', label: 'Cool Tag 1'}, {key: '2', label: 'Cool Tag 2'}])

  let onRemoveFirst = () => {
    setItems(prev => prev.slice(1));
  };
  let onAddNew = () => {
    setItems(prev => {
      index++;
      return [...prev, {key: index, label: `Cool Tag ${index}`}];
    });
  };

  return (
    <>
      <TagGroup aria-label="Tag group with icons" items={items}>
        {(item: any) => (
          <Item key={item.key} textValue={item.label}>
            <Audio />
            <Text>{item.label}</Text>
          </Item>
        )}
      </TagGroup>
      <Button variant="primary" onPress={onRemoveFirst}>Remove first</Button>
      <Button variant="secondary" onPress={onAddNew}>Add New</Button>
    </>
  );
}
```

You can try it with this story in the React Spectrum component stories. You'll notice that the newly added tag is announced regardless of focus being outside the taggroup, which is not what we want.

**Comment by ryo-manba** [comment]
@snowystinger 
Thanks for the code sample, I tested it out.

With the existing code, newly added tags are not announced when the focus is outside the TagGroup because `aria-live: polite` is only active when the grid is focused. 

https://github.com/user-attachments/assets/242d0e40-86c5-4997-8d5e-1cc4ac431283

With the suggested code, newly added tags are announced regardless of whether the TagGroup is focused or not.


https://github.com/user-attachments/assets/96d0a4df-2d56-41dc-8cc0-360bfbf539c8


I used [Assistiv Labs](https://assistivlabs.com/) with Chrome 126 and NVDA for testing.

**Comment by snowystinger** [comment]
Right, that is the behavior we do NOT want. Tags added or removed should only be announced when you are in the group. If you have a composite control, then you can add your own announcer to handle that, such as is shown in the APG example.

**Pull request closed without merging**
