### PR TITLE
fix: DatePicker with defaultValue persists time zone

### PR DESCRIPTION
**Pull request by boutahlilsoufiane**
Closes [#6005](https://github.com/adobe/react-spectrum/issues/6005)

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [X] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

### CODE REVIEW

**Review by snowystinger — DISMISSED** [review]

**Comment by snowystinger** [comment]
Looks like you might need to sign the CLA? https://react-spectrum.adobe.com/contribute.html#contributor-license-agreement

**Comment by boutahlilsoufiane** [comment]
Thanks for the review, I have just signed the CLA.

**Comment by snowystinger** [comment]
Thank, I'll close and reopen as it looks like it's stuck at the moment.

**Comment by snowystinger** [comment]
trying again to get it unstuck

**Review by snowystinger — APPROVED** [review]

**Review by yihuiliao — APPROVED** [review]

**Pull request merged**
