### PR TITLE
(WIP) Fix overlay positioning when pinch-zooming

### LINKED ISSUE #2700: Pinch-zoom on Mac OS with Popover opened
# 🐛 Bug Report 
When we try to use macbook's trackpad for zooming in and out, using pinch - in and out, then one can observe movement of popover as shown in the gif below:
My new video project

## 🤔 Expected Behavior
Popover shall remain static 

## 😯 Current Behavior
Popover is moving sometimes vertical sometimes horizontal.

## 💁 Possible Solution
Nothing that I can think of right now.

## 🔦 Context
I was trying to create a popover for grouped actions. On its opening user would choose what it may feel reqd.

## 💻 Code Sample
N/A

## 🌍 Your Environment
Since this video was recorded on documentation site it must be the latest one i.e. [December 16 Release](https://react-spectrum.adobe.com/releases/2021-12-16.html) . I could dig up more and found that video was recorded on 7th December thus it seems to be an issue existing in [November 24 Release](https://react-spectrum.adobe.com/releases/2021-11-24.html).  

## 🧢 Your Company/Team
Adobe

### PR DESCRIPTION
**Pull request by samulisuomi**
Closes #2700

The decision to use visualViewport comes from https://github.com/adobe/react-spectrum/pull/1176/commits/73535b42d7cb57e133b7b02a2437c59b533ae90f#diff-f4cd45647233fa6ce298370ea0a2c8b9f3849d6ad45c45198bf8ea4427d9ad83R99 Not sure how to test keyboard functionality that the commit message is talking about.

To Dos:
- [ ] It seems the `document.body container top` story gets broken after my change.
- [ ] Also a ton of tests break, hinting that some other functionality also broke.

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

1. Run the storybook w/ `yarn start`
2. Test out overlay storybooks in their own tab, e.g.: [document-body-container-bottom](http://localhost:9003/iframe.html?providerSwitcher-express=false&strict=true&scrolling=false&providerSwitcher-locale=&providerSwitcher-theme=&providerSwitcher-scale=&args=&id=useoverlayposition--document-body-container-bottom&viewMode=story)
3. Pinch zoom with your trackpad or mobile device while the overlay is open. I'm on an M1 MacBook Pro myself.

### Before

After a certain point, the `delta` calculations (see [getDelta](https://github.com/marg0l/react-spectrum/blob/1dd4d3f18e8ce2b314ee6519aaf8728fc5818e2e/packages/%40react-aria/overlays/src/calculatePosition.ts#L139)) would result in negative values and thus the overlay would be pushed to a wrong place:

https://github.com/adobe/react-spectrum/assets/3490745/28706559-4d66-47cc-a477-9db83a5b0462

### After

https://github.com/adobe/react-spectrum/assets/3490745/32386fa4-c646-4f06-8e3c-ea7b41db4811

### CODE REVIEW

**Review by snowystinger — COMMENTED** [review]
I think we could probably take some inspiration from floating-ui

https://github.com/floating-ui/floating-ui/blob/master/packages/dom/src/utils/getViewportRect.ts

https://github.com/floating-ui/floating-ui/blob/master/packages/dom/src/utils/getDocumentRect.ts

we do eventually want to see if we can replace our popover positioning code with theirs

**Comment by LFDanLu** [comment]
Perhaps we just need to offset our calculations by offsetLeft/Top like in the [floating ui code](https://github.com/floating-ui/floating-ui/blob/39e9393e7fd5bb31466c7af727c4f614715f90bf/packages/dom/src/utils/getViewportRect.ts#L22-L25).

**Comment by snowystinger** [comment]
> Perhaps we just need to offset our calculations by offsetLeft/Top like in the [floating ui code](https://github.com/floating-ui/floating-ui/blob/39e9393e7fd5bb31466c7af727c4f614715f90bf/packages/dom/src/utils/getViewportRect.ts#L22-L25).

Not quite this straightforward, I just tried it and it does not affect the positioning of the Combobox issue you showed me. Will need to dig into this more.

**Comment by LFDanLu** [comment]
I believe this has been solved by a combination of https://github.com/adobe/react-spectrum/pull/5612 and https://github.com/adobe/react-spectrum/pull/5660 which both just went out with the latest release (3.34). Let us know if the changes work for you!

**Pull request closed without merging**
