### PR TITLE
fix: Remove iOS HiddenSelect workaround

### PR DESCRIPTION
**Pull request by snowystinger**
Closes 

Alternative to https://github.com/adobe/react-spectrum/pull/7103

I have tried this out in iOS 18.0.1 and our hidden input isn't enabling the next/previous arrows which come with form filling anyways. So it doesn't really matter if it's removed.
We could also attempt to fix the behaviour for next/previous.

Can someone try the next/prev arrows in iOS 17? we suspect it wasn't working there already.

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

### CODE REVIEW

**Comment by yihuiliao** [comment]
not sure if i tested this correctly but this is what happens when i try using the next/prev arrows in a form. doesn't really seem to work too well for some of the components. i'm on iOS 17.6.1


https://github.com/user-attachments/assets/303fc820-207b-48a1-ba83-628423329d3a

**Comment by snowystinger** [comment]
> not sure if i tested this correctly but this is what happens when i try using the next/prev arrows in a form. doesn't really seem to work too well for some of the components. i'm on iOS 17.6.1

@yihuiliao can you pop it out into a new tab? I found that works better. otherwise the iframe seems to interfere.

**Comment by yihuiliao** [comment]
okay this is what's happening on main right now. 

https://github.com/user-attachments/assets/a9c36ec5-9819-4990-8c52-12e25aeda339

i also briefly tested the next/prev arrows on this pr, same story, and it doesn't seem to be any different from what's happening on main

**Comment by snowystinger** [comment]
@yihuiliao thank you for confirming. Next/Previous do skip over our Pickers/Selects

**Comment by yihuiliao** [comment]
Correct me if I'm wrong but this is the direction that we chose to go with at the end of otter time since it seems our support for the prev/next button has always been a bit finicky

**Review by devongovett — DISMISSED** [review]
Can you drop the mention of this feature from the docs for both RAC and hooks?

**Review by devongovett — APPROVED** [review]

**Review by yihuiliao — APPROVED** [review]

**Pull request merged**
