### PR TITLE
Make plop pick current year

### PR DESCRIPTION
**Pull request by solimant**
Closes https://github.com/adobe/react-spectrum/issues/2147

## ✅ Pull Request Checklist:

- [X] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:
1. Run `yarn plop`
2. Do the needful
3. Inspect license header in generated files
4. Should pick current year (2021 as of the year of authoring this PR)

## 🧢 Your Project:
Adobe/RSP

### CODE REVIEW

**Review by snowystinger — DISMISSED** [review]
Nifty, thanks for that

**Review by LFDanLu — CHANGES_REQUESTED** [review]
LGTM for the most part, noticed that the `Component.chromatic.tsx.hbs` and `Component.stories.tsx.hbs` don't have this `{{currentYear}}` change though

**Comment by solimant** [comment]
> Component.chromatic.tsx.hbs

@LFDanLu - Good catch, thank you! Added.

**Review by LFDanLu — APPROVED** [review]
LGTM, thanks for the speedy turn around!

**Review by snowystinger — APPROVED** [review]
thanks!

**Pull request merged**
