### PR TITLE
provide autofocus property

### LINKED ISSUE #1229: Support autofocus on Picker
# 🙋 Feature Request

We have an input form where a Picker is the first field but we can not mark it as the initial focus receiver as unlike eg TextField it has no autofocus-Property.

## 🤔 Expected Behavior

Provide an autofocus-Property like it is available on other Elements like buttons, text-inputs, ...

## 😯 Current Behavior

Property is not available

## 💁 Possible Solution

Looking at other controls they all inherit `FocusableProps` so one possibility would be to make PickerProperties extend that as well although I'm not sure whether this was left out for a reason. A simpler and more focus solution would be to just add the autoFocus-Property directly and pass it on to FieldButton.

If you think this is a valid request it would be great if you could tell me which of the 2 options I should implement.

### PR DESCRIPTION
**Pull request by tomsontom**
Closes #1229 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Run the new story book sample

### CODE REVIEW

**Review by snowystinger — APPROVED** [review]

**Review by LFDanLu — APPROVED** [review]
LGTM

**Comment by tomsontom** [comment]
May I ask why those changes have not been included in the release that was done on December 22nd?

**Comment by snowystinger** [comment]
Hey, we didn't have enough time to do a complete testing of the release and we were focused on getting Slider out. This will be in our next release.

**Comment by tomsontom** [comment]
ok - so how does one know if a fix is getting released? As you don't assign PRs nor Issues to Milestones I thought if it is merged into main it is going to part of the next release. Where/How do you track that controls who have changes are not yet released (including their prerequsits eg Picker needs a new version of utils)?

**Comment by snowystinger** [comment]
Normally things merged to main will be in the next release. This was a special case because we didn’t have time for a full testing of the changes beyond the release of Slider because of the holiday period

**Pull request merged**
