### PR TITLE
Set default value for type parameter in SelectProps

### LINKED ISSUE #6960: Type param in SelectProps<T> is not used
### Provide a general summary of the issue here

The type param `T` is used in `CollectionBase<T>` to define the `children` and `items` props.

However they are both omitted by `SelectProp`.

https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/Select.tsx#L65

So the type param is just noise and doing nothing.

### 🤔 Expected Behavior?

remove it or use it

### 😯 Current Behavior

doing nothing

### 💁 Possible Solution

_No response_

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

n/a

### Version

rac 1.3.1

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

macOS

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by kp047i**
Closes #6960 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

### CODE REVIEW

**Review by snowystinger — COMMENTED** [review]
Thanks for submitting!

I'm not sure the best way to mark this as deprecated now. Perhaps using overload syntax we could mark this particular signature as deprecated

**Comment by kp047i** [comment]
@snowystinger 
I tried using overload syntax to deprecate only the function signatures where a type parameter is provided, but I couldn’t get it to work. Here’s my attempt: [TypeScript Playground](https://www.typescriptlang.org/play/?#code/PQKhFgCgAIWgBAJgUwA4CdkGMCGAXZRaAFQAtlo8BPVC1HdHAW2QPWgANiPoBLAZ2goM2fISixgUAGYBXAHZY8vAPbzoyAB7NUAG2QAxBUtXyAPMQB8ACgBuOXbOQAuEgEpXxANwzjytRraTHqGfqZ2Dk6u-HjovPIA5h7QMXGJPpC+iv7qWjr6Rtnh9o4u0DjyVMkVVNAA3hLQTZh4sujqJU4ZAL5QUFhqMdCY-LK6eACM0AC8gfmhRWrWAEQAEsi6uioAhMtuGQPyQyNjeABMM3PBBWFqZvKyTABGyOg2ACxn+0A).

Could you check if my approach is correct, and let me know if there’s a better way to achieve this?

Thanks!

**Review by snowystinger — DISMISSED** [review]
Hmmm, I am not good enough at Typescript to figure out how to do it. I had a good google around. Thanks for also checking that out and confirming it.

**Comment by kp047i** [comment]
@snowystinger 
Is there anything I should do?

**Comment by snowystinger** [comment]
Might need to run `git rebase origin/main` after updating your main branch, looks like the git history went wonky due to an accidental change we had on main

**Review by snowystinger — APPROVED** [review]

**Review by LFDanLu — APPROVED** [review]

**Pull request merged**
