### PR TITLE
LocalizedStringProvider: nonce parameter for Content Security Policy

### LINKED ISSUE #6218: LocalizedStringProvider: missing nonce parameter when CSP is enabled
### Provide a general summary of the feature here

When I activate CSP on Next.js with nonce ([doc](https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy#nonces) and [example](https://github.com/vercel/next.js/tree/4ccb99fc1f2ed63d9fdd2eeda60f76deb92b7985/examples/with-strict-csp)).

I have a problem with LocalizedStringProvider because it ends up as an inline script but I can't manual set the nonce parameter into it

### 🤔 Expected Behavior?

I would expect to do something like that:

```tsx
<LocalizedStringProvider locale={lang} nonce={nonce} />
// or
<LocalizedStringProvider locale={lang} extraScriptProps={{nonce}} />
```

I have a PR ready for the first option

### 😯 Current Behavior

The current behavior ends up with this kind of error:

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-NTM4MTg1ZDUtZDhkMS00MGE1LTgwMTgtOWU2MDUyMmMzNjkz' 'strict-dynamic'"
```

because the html returned for that page contains:

```html
<!-- missing nonce -->
 <script>
            window[Symbol.for('react-aria.i18n.locale')] = "en";
            {
                let A = (e)=>`Selected Date: ${e.date}`
                  , B = "Previous"
                  , C = "Next"
                  , D = "Select";
                window[Symbol.for('react-aria.i18n.strings')] = {
```

### 💁 Possible Solution

- accept nonce in LocalizedStringProvider
- accept an `extraScriptProps` for any of the script props: this is what Apollo is doing
- automatically detect nonce? I guess this is framework dependent 

Apollo wrapper:
```tsx
<ApolloNextAppProvider makeClient={makeClient} extraScriptProps={{ nonce }}>
```

### 🔦 Context

This is a blocker for me because I need to active the CSP header in my Next.js app and I'm unable to deploy without having the nonce in all inlined scripts.

### 💻 Examples

deployed example https://csp-next-and-react-aria-components-provider.vercel.app/

associated code: https://github.com/Julienng/csp-next-and-react-aria-components-provider

### 🧢 Your Company/Team

Semarchy

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by Julienng**
Closes #6218

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [LocalizedStringProvider: missing nonce parameter when CSP is enabled](https://github.com/adobe/react-spectrum/issues/6218).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [x] Updated documentation (if it already exists for this component). Would like help on where to document there
- [x] ~~Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)~~ no concern

## 📝 Test Instructions:

https://github.com/adobe/react-spectrum/issues/6218
Reproduction repo and deployed test on vercel to check

### CODE REVIEW

**Review by snowystinger — APPROVED** [review]
Seems reasonable, we should see about adding it to our example project for verification.
https://github.com/adobe/react-spectrum/tree/main/examples/next-app

**Comment by Julienng** [comment]
@snowystinger I've added the example project. It matches with the `next-app` but with CSP

By testing it, I noticed hydration error with CSP because the browser remove nonce parameter from the DOM before React hydration.

To circumvent that problem, I followed the same pattern as `next-themes` in this PR: https://github.com/pacocoursey/next-themes/pull/262

new code:

```tsx
<script nonce={typeof window === 'undefined' ? nonce : ''} suppressHydrationWarning dangerouslySetInnerHTML={{__html: getPackageLocalizationScript(locale, strings)}} />;
```

**Comment by snowystinger** [comment]
Linking relevant React issue https://github.com/facebook/react/issues/26028

**Review by snowystinger — COMMENTED** [review]
Ok, might be a silly question, but how do I run this to verify what it's doing?
I tried
```
cd examples/next-app-csp
yarn
yarn dev
```
and it just renders a blank page with an error, which is about the nonce, element in question. So is this what it's supposed to do?
Screenshot 2024-05-14 at 5 43 20 PM

**Comment by snowystinger** [comment]
> Oh yeah, I had to `yarn build` before for the example to work. I don't know if this is expected (from the monorepo perspective)?

totally fine, I think we should include instructions though. With all the different systems, I sometimes forget the commands I need to run and in what order.

**Review by snowystinger — APPROVED** [review]
I was able to successfully run it, verified the suppress warning and checked sent-through nonce via the attribute

**Review by LFDanLu — APPROVED** [review]
Verified the behavior before and after the nonce addition. Might be good to add a small blurb to the docs SSR docs highlighting that this prop exists?

**Pull request merged**
