### PR TITLE
adding support for functions and variable interpolation

### LINKED ISSUE #1716: Allow to use CSS-Functions for Dimension properties
# 🙋 Feature Request

Currently one can use %,em, ... but it is not possible to use CSS functions like min/max/calc/clamp to size components using CSS-Functions

## 🤔 Expected Behavior

Pass through min/max/calc/clamp as it is currently done for %,em, ...

## 😯 Current Behavior

Value is not passed

## 💁 Possible Solution

Add a check for min/max/calc/clamp - if you agree this is a good idea I'd prepare a PR.

## 🔦 Context

I'd like to size elements using some clever CSS-Functions

### LINKED ISSUE #1773: onCancel should fire in AlertDialog if Escape is pressed
# 🐛 Bug Report (or maybe feature request?)

When adding an `onCancel` handler to an AlertDialog, it should fire if the dialog is closed via the Escape key.

See here for a repro: https://codesandbox.io/s/adoring-meadow-7cl4c?file=/src/App.js

Open the dialog, click Cancel, dialog will close, you'll see 'Canceled' in the console.
Open the dialog, press Escape key, dialog will close, no 'Canceled' in the console.

### PR DESCRIPTION
**Pull request by tomsontom**
Closes #1716

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Review by snowystinger — APPROVED** [review]
Thanks for the work, I've added tests as well.
I think this is probably good for the moment. We'll add docs when we do a release assuming this passes API review.

**Comment by devongovett** [comment]
I'm slightly concerned about inventing our own CSS syntax here. It seems rather brittle at the moment - e.g. what happens if a variable name conflicts with a CSS keyword? What do you think about doing something like `<View width="calc(100px + var(--size-250))">` instead? We would still add the prefixes for you, but at least the syntax would be CSS compatible and more obvious what's a variable to replace. What do you think?

**Comment by devongovett** [comment]
Also, is `calc` the only function that is actually supported? If so, then maybe we should make the regex more specific?

**Comment by snowystinger** [comment]
https://caniuse.com/css-math-functions would indicate that min/max/clamp are supported as well as calc
I'm on the fence about adding `var()`, it'd make it easier to replace and using other variables would end up looking like that. I guess it's odd just because the standalone version is already not decorated with `var()`
`width="size-200"` not `width="var(--size-200)"`
yet it'd be
`width="calc(100% - var(--size-200))"` not `width="calc(100% - size-200)"`

**Comment by tomsontom** [comment]
### On making the regex more specific:
As @snowystinger pointed there's more than `calc` supported I used https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions#math_functions and use eg `min` in my grid definitions and as you can nest functions useing a regex would not work anymore. Further more I think it is an advantage that we automatically support new functions once they are available.

### On using var:
I personally find the version **without** `var` much more readable - the example shows a very simple function but it could get even more complex so leaving out the `var()` function pays off even more. I highly doubt that the there will ever be a keywould `size-\d+` but naturally there's no 100% guarantee. 

One problem I see with `var()` is that supporting something `var(--size-200, var(--size-250))` is something I don't see how it'll work. It won't work with the plain syntax either but because we advertise the useage of `var()` people might be tempted to believe they could use it.

In the end `size-200` is in reality is **not** a CSS-Variable but a macro that we are expanding so marking that macro as a `var` feels wrong to me. Going on with the idea that we are having a macro here are some proposals:
* `#size-200`
* `<size-200>`
* `$size-200`
* `@size-200`

Anyways it's your call and I'll implement whatever you guys decide is the best for the project and from your comments I see you lean towards the use of `var()` which is fine for me.

**Comment by tomsontom** [comment]
@devongovett @snowystinger any thoughts on my comment - I ask because I could invest some time into this at the end of the week

**Comment by tomsontom** [comment]
@devongovett @snowystinger how do want to proceed - otherwise we should close this as wontfix

**Review by devongovett — APPROVED** [review]

**Comment by devongovett** [comment]
Thanks. Going to merge as is. This seems to be the most pragmatic approach. Ideally we would try to type this as well (possibly using [Template literal types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html)), and add something about this to the docs (probably here https://react-spectrum.adobe.com/react-spectrum/styling.html#dimension-values). If you would like to work on that, please feel free to send followup PRs!

**Comment by tomsontom** [comment]
> Thanks. Going to merge as is. This seems to be the most pragmatic approach. Ideally we would try to type this as well (possibly using [Template literal types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html)), 

I looked at that - https://github.com/adobe/react-spectrum/issues/1716#issuecomment-815302680 and template literals are not required - the problem I ran into was that this does not work in `.d.ts` which is used to define `DimensionValue` -  need to see if one can use them im `.d.ts` but what's the minimum version you require - template literals require a fairly new version of typescript.

Let me see what I can find out and I'll open a ticket to add typing support.

**Pull request merged**
