### PR TITLE
Upgrade storybook to v6

### PR DESCRIPTION
**Pull request by snowystinger**
Dev week PR - preparation for moving to CSF
Closes 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Review by LFDanLu — COMMENTED** [review]
The upgraded storybook seems to work fine, I assume you've tried running chromatic against it as well?

**Comment by snowystinger** [comment]
We unfortunately do not run chromatic vs React 17 builds. It'd be hard to do that other than manually and I don't want it to be in any way a baseline

**Review by LFDanLu — APPROVED** [review]
Did a quick sweep of the chromatic as well, nothing seems super broken, just shifts in overal positions.

**Review by ktabors — DISMISSED** [review]
LGTM

**Comment by dannify** [comment]
To be merged after the outcome of testing next week.

**Review by dannify — DISMISSED** [review]
Concerned about the updates to lock file but let's test to be sure.

**Review by ktabors — COMMENTED** [review]
Is there a different pull where you rewrite stories in the new style or you didn't have time that week?

**Review by dannify — APPROVED** [review]

**Pull request merged**
