### PR TITLE
ColorSlider and ColorWheel labeling improvements

### PR DESCRIPTION
**Pull request by devongovett**
Closes #1545

This is an adjusted version of #1545. Moves the translations and default labeling into Spectrum and adds some tests. See https://github.com/adobe/react-spectrum/pull/1545#pullrequestreview-583716516 for an explanation.

### CODE REVIEW

**Comment by devongovett** [comment]
Another alternative if we want to enable non-spectrum users to use our translations would be to put them in stately, and add a method like `getLocalizedChannelName(channel, locale)`. We've never put translations in stately before though.

**Comment by majornista** [comment]
It seems like Color is now the only case where i18n is not part of the `@react-aria` package.

**Comment by devongovett** [comment]
Slider and a couple others have translations in spectrum too

**Review by LFDanLu — APPROVED** [review]
LGTM, confirmed Voiceover behavior in ColorSlider and ColorWheel. 

Only odd points came from testing Android Talkback where changes in the thumb position were alway announced as percentages (e.g. 0 - 100% rather than 0-225). Also had an issue where Android talkback could only go from 0 to 1 for the alpha channels but this seems to be a problem with range inputs with small min max in general. Out of scope

**Review by dannify — APPROVED** [review]

**Pull request merged**
