### PR TITLE
Support spectrum express theme

### PR DESCRIPTION
**Pull request by devongovett**
Depends on #3604 and #3650.

This adds support for the [Spectrum Express](https://spectrum.adobe.com/page/theming/) theme by overlaying variable overrides on top of our existing CSS. This was mostly done by diffing the latest `@spectrum-css/vars` and `@spectrum-css/expressvars` packages, and then mapping the variable names back to our version. In addition, I compared the XD files manually. There's now a checkbox in storybook to turn on the express theme.

Other than variable overrides, this has a few other CSS changes, mostly to always implement focus rings as halo elements. Then a variable is adjusted between themes to change the gap.

To do

- [x] Figure out icons
- [x] Add `@react-spectrum/theme-express` package
- [x] Add to chromatic somehow
- [ ] Documentation

### CODE REVIEW

**Comment by dannify** [comment]
Don't listen to him linter. You are doing a great job. Keep it up!

**Comment by devongovett** [comment]
This is now passing Chromatic, so there are no unexpected changes to regular spectrum as far as I know. No new Chromatic stories have been added yet - need to figure out how we want to handle that.

**Review by snowystinger — COMMENTED** [review]
Screenshot 2022-10-28 at 4 22 41 PM
calendar doesn't fit in the grey background square quite right

I think this was meant to be AlertDialogExpress? https://www.chromatic.com/test?appId=5f0dd5ad2b5fc10022a2e320&id=635c3a9b0ec84555f8181aa9

**Review by snowystinger — DISMISSED** [review]

**Review by snowystinger — APPROVED** [review]

**Comment by dannify** [comment]
Small bug on DatePicker 
image
Can be a follow up. The rest looks good.

**Review by dannify — DISMISSED** [review]

**Review by snowystinger — DISMISSED** [review]

**Review by reidbarber — APPROVED** [review]

**Review by LFDanLu — APPROVED** [review]
Did a quick sweep, the spectrum themed components look good to me. Also confirmed that quiet ComboBox/SearchAutocomplete are opening properly on desktop and mobile

**Review by snowystinger — APPROVED** [review]
Did a quick sweep of places in Firefox where I thought that Transform translate would apply. I don't see any issues with them. Also checked the fixes you made, they are behaving well

**Pull request merged**
