### PR TITLE
Fix use range calendar with mobile scrolling

### LINKED ISSUE #5975: [useRangeCalendar] Should allow (mobile) scroll through multiple calendars and then finalize a range selection
### Provide a general summary of the issue here

I have a multi-month range calendar that I can scroll to reveal other months. I'd love to start selection on a day of first month, touch-scroll to third month and then end selection on a day of third month. But current implementation would finalize the selection while I touch-scrolling.

### 🤔 Expected Behavior?

I can touch-scroll a calendar and then finalize a range selection

### 😯 Current Behavior

touch-scroll a calendar immediately finalize a range selection

### 💁 Possible Solution

_No response_

### 🔦 Context

I want to make a scrollable RangeCalendar as Booking.com:

https://github.com/adobe/react-spectrum/assets/38932402/13290232-d501-49ca-ac0f-e8d8ae550b41

Here's a [codesandbox](https://codesandbox.io/p/sandbox/react-aria-scrollable-range-calendar-h78c39) with useRangeCalendar (modified from the code [example](https://react-spectrum.adobe.com/react-aria/useRangeCalendar.html#styled-examples)):

https://github.com/adobe/react-spectrum/assets/38932402/1a194afd-e490-4fbb-b555-5cd279d00c67

The issue: It finalize the ongoing range selection when I touch-scroll

### 🖥️ Steps to Reproduce

1. Open this [codesandbox](https://codesandbox.io/p/sandbox/react-aria-scrollable-range-calendar-h78c39)
2. Use devtools to emulate mobile touch screen
3. Select a date
4. Touch-scroll to scroll the multi-month calendar
5. Select another date
6. The issue happens, the end of range is not "another date" by previous stop

### Version

@react-aria/calendar 3.5.6

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

macOS 14.3.1

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by QzCurious**
Closes #5975

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

## 📝 Test Instructions:

You can test it on an existing [story](http://localhost:9003/?path=/story/date-and-time-rangecalendar--default-val-visible-months&providerSwitcher-express=false&strict=true):

https://github.com/adobe/react-spectrum/assets/38932402/55845ecc-e885-4325-9b10-ad6d10260529

### CODE REVIEW

**Comment by LFDanLu** [comment]
GET_BUILD

**Review by LFDanLu — APPROVED** [review]
LGTM, tested locally on my Android test device, behavior looks good to me. Thanks for splitting this out into this smaller change, will get it into another testing session soon!

**Comment by QzCurious** [comment]
I case you missed it. The only relevant change is deleting the line:

https://github.com/adobe/react-spectrum/pull/5976/commits/8a7aec39ca3fc63417e642185c1c86f64f7b8ea0
image

I'm not sure why `'pointercancal'` were concerned back than. Perhaps you might want to double-check the purpose again.

**Comment by LFDanLu** [comment]
yep, it came from this commit: https://github.com/adobe/react-spectrum/commit/6d84224fe3ae4aa2687fd8fc5511d109e4df9fe6. I couldn't figure out what flow specifically that line was fixing in the touch scroll/press drag range selection case, those flows seemed to still work on my own phone for the most part. We'll do more cross device testing in the upcoming testing session, will keep you posted on any findings there

**Comment by yihuiliao** [comment]
I don't have any new information to share but I just wanted to let you know that the team will be slow to review as we address some other priorities at the moment. We appreciate your understanding and apologize for the wait.

**Comment by QzCurious** [comment]
I see. Thanks for your information.

**Comment by LFDanLu** [comment]
GET_BUILD

**Review by ktabors — APPROVED** [review]

**Pull request merged**
