### PR TITLE
ListView storybook updates and filterDomProps

### PR DESCRIPTION
**Pull request by reidbarber**
Covers:
- added filterDomProps (support data* attributes)
- add ActionBar examples storybook
- Cleanup example stories (use ActionGroup, Content, etc.)
- Use better fake data in stories

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Test ListView stories:
- verify stories render with new data and updates
- test new 'with ActionBar' stories

## 🧢 Your Project:

RSP

### CODE REVIEW

**Review by snowystinger — COMMENTED** [review]
Minor comment, can we include some stories or tests with the filtered dom props?

**Comment by reidbarber** [comment]
> Minor comment, can we include some stories or tests with the filtered dom props?

There should be a new test called "supports custom data attributes"

**Review by snowystinger — APPROVED** [review]
aye, there is, it was small and I missed it, thanks!

**Review by LFDanLu — APPROVED** [review]
LGTM, though I forget if there was some additional work to be done for the ListView stories to make them more real world (faint recollection of something about that in planning?) 
Can do that in a follow up if so anyways so approving.

DNM until after release

**Pull request merged**
