### PR TITLE
Docs: fix layout shifting on dialog open

### PR DESCRIPTION
**Pull request by hamitaksln**
## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 🧢 Your Project:

There is a annoying layout shifting when any dialog opens. So I generally solve this problem with `overflow-y:scroll`

https://user-images.githubusercontent.com/23298031/234929464-da4256be-3980-40db-b26c-c8da108e2c8d.mp4

### CODE REVIEW

**Comment by snowystinger** [comment]
Thanks for the concern, however, we do not want to allow scrolling.
https://github.com/adobe/react-spectrum/issues/2926

That said, it looks like maybe something is happening around here  https://github.com/adobe/react-spectrum/blob/bd89c6aba9dd1bf763a5166d37524ab6fb612509/packages/%40react-aria/overlays/src/usePreventScroll.ts#L43 because this comment would indicate we tried doing something to prevent that shift by reserving space for the scrollbar.

**Comment by hamitaksln** [comment]
I see, still we can prevent layout shifting with blocking scroll on dialog open I believe.

**Comment by ktabors** [comment]
Thanks for the PR, while reading the conversation above and reviewing this PR I noticed that the CLA has not been signed. For the build to pass you'll need to [sign the CLA](http://opensource.adobe.com/cla.html), then close and re-open this PR to let it refresh. There is additional information at https://react-spectrum.adobe.com/contribute.html#contributor-license-agreement.

**Comment by ktabors** [comment]
Please reopen this when the CLA is signed.

**Pull request closed without merging**
