### PR TITLE
Replace Zero-width space with css margin on label's necessity indicator

### PR DESCRIPTION
**Pull request by reidbarber**
Found in slack.

A zero-width space character (`\u200b`) is used to separate the label from the necessity indicator. Seems like this has potential to cause issues with assistive technologies or testing tools. I've updated this with a css margin that matches Spectrum's designs. Not sure if there was a specific reason this was originally included, but this seems better.

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Comment by reidbarber** [comment]
This test is failing because it includes a `U+200b` character. Not sure if that gives us a hint as to whether it was needed, or if the test should just be updated.

https://github.com/adobe/react-spectrum/blob/b2abc5d94162a7bd614fffcdf11e3d3754dc7d9f/packages/%40react-spectrum/form/test/Form.test.js#L75

**Comment by snowystinger** [comment]
> This test is failing because it includes a `U+200b` character. Not sure if that gives us a hint as to whether it was needed, or if the test should just be updated.
> 
> https://github.com/adobe/react-spectrum/blob/b2abc5d94162a7bd614fffcdf11e3d3754dc7d9f/packages/%40react-spectrum/form/test/Form.test.js#L75

seems needed, or like we need to add it to the locale string

```
{
  labelRequired: '${label} (required)',
  labelOptional: '${label} (optional)',
}

format(labelRequired, {label: props.label})
```

something like that, we really probably shouldn't be joining strings together like we currently are

**Comment by reidbarber** [comment]
> seems needed, or like we need to add it to the locale string. My guess, and you can verify this locally, is that it reads off 'field(optional)' as all one word, or tries to.

VoiceOver looks fine, but I'm not sure about others:
TextField necessity indicator with VoiceOver

Firefox Accessibility Inspector shows this:
Screen Shot 2022-02-09 at 12 03 40 PM

I think you're right though, the method you mentioned seems ideal.

**Comment by majornista** [comment]
As I recall, the zero-width space may have been included to ensure that screen readers don't concatenate and announce the necessity indicator for "optional" or "required" with the label as a single string.

**Comment by majornista** [comment]
As I recall, the zero-width space may have been included to ensure that screen readers don't concatenate and announce the necessity indicator for "optional" or "required" with the label as a single string.

**Pull request closed without merging**
