### PR TITLE
Allow FileTrigger to accept the same file twice

### LINKED ISSUE #4925: RAC FileTrigger should accept the same file twice
### Provide a general summary of the issue here

FileTrigger in React Aria Components uses the native input which is hidden by the user. If the native input contains the value of some file, it is not possible to upload the same file again.

### 🤔 Expected Behavior?

It should be possible to upload the same file twice in a row.

### 😯 Current Behavior

After uploading a file, it is not possible to upload the same fail again right after.

### 💁 Possible Solution

As a temporary fix, we clear the `value` of the input after each change.
https://github.com/bratislava/konto.bratislava.sk/blob/7206955eb4f809bcac4b4b6758070dcfc7309821/next/components/forms/widget-components/Upload/UploadButton.tsx#L70

It might be also possible to clear if before [triggering click event](https://github.com/adobe/react-spectrum/blob/09a258f098147f7e67a0430b593b08168220ec4a/packages/react-aria-components/src/FileTrigger.tsx#L50C38-L50C38) on the input.

I am not sure if it is possible to do that on library scale, but as the input is hidden, and the only time the file reference is accessed is `onChange`, it may be safe to do so. Maybe as an optional prop.

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/proud-moon-mvq7qz

1. Upload "file1.txt".
2. See console.
3. Upload "file1.txt".
4. See that console only contains one log.

### Version

react-aria-components@1.0.0-alpha.6

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

Windows

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by yihuiliao**
Closes #4925 

We decided to move this component away from forms, hence the removal of the name prop. As a future follow-up, we'd like to create a separate file input component that works specifically for forms. 

With this implementation, we would expect that a user be able to submit the same file twice and that if the user clicked canceled on the file picker that the value of the file input would be cleared. 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

In the stories, you should be able to submit the same file twice and onSelect should be fired twice. 

Might also want to sweep through DropZone/FileTrigger docs to make sure everything looks good.

## 🧢 Your Project:

RSP

### CODE REVIEW

**Comment by yihuiliao** [comment]
Since we want to move this out of Forms, what category should this go under in the docs? Maybe drag and drop?

**Comment by snowystinger** [comment]
> Since we want to move this out of Forms, what category should this go under in the docs? Maybe drag and drop?

DnD is a bit weird, it's associated, but maybe a better name for that section would then be something that joins them?
Asset Management
Assets
Asset Choosers
Asset Pickers
(replace word 'asset' with 'file'?)


otherwise... Buttons?

**Review by LFDanLu — COMMENTED** [review]
behavior looks good to me. As for the section, perhaps a new one ('File system')?

**Comment by devongovett** [comment]
Would rather not have a whole new category for just one component. I'd say either Buttons or leave it in Forms anyway.

**Review by snowystinger — APPROVED** [review]
Looks good
last question, is it weird to have FileTrigger before ToggleButton? I know it's alphabetical, but feels weird all the same in a section called buttons
I don't expect a change for that in this pr

**Comment by yihuiliao** [comment]
> Looks good last question, is it weird to have FileTrigger before ToggleButton? I know it's alphabetical, but feels weird all the same in a section called buttons I don't expect a change for that in this pr

yeah i agree it does feel a bit strange. maybe we can reconsider where to put it in a follow-up

**Review by devongovett — APPROVED** [review]

**Pull request merged**
