### PR TITLE
Fix TextArea not using full height when custom height provided

### PR DESCRIPTION
**Pull request by reidbarber**
Seems to have broken in https://github.com/adobe/react-spectrum/pull/3521

For labelPosition: top, when a fixed height is provided, the textarea doesn't fill the height of its container.

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

In Storybook, go to TextArea -> Custom height with label

Verify that textarea now fills its container.

Double check other TextArea stories and height behavior when typing.

Ensure that quiet TextArea grows to a max of the specified height when typing, and the help text is just below the line.

### CODE REVIEW

**Comment by snowystinger** [comment]
Can we run chromatic on this one?

**Review by ktabors — COMMENTED** [review]
I went to the 'changeable helptext custom height' story, use a control to set isQuiet=true, the TextArea and help text (description) both move, then set isQuiet=false and the TextArea goes to its default height, not the height set via the props and the helptext goes to the initial position. Is this desired?

initial state
image
isQuiet=true
image
isQuiet=false
image

**Comment by reidbarber** [comment]
@ktabors I believe that is an existing issue with switching to quiet and back, which I don't think would happen in real apps. We are setting the custom height (only relevant to quiet, for growing it when typing) and then not unsetting it.

**Review by devongovett — APPROVED** [review]

**Review by LFDanLu — APPROVED** [review]
Tested locally, LGTM on Chrome, Safari, and FF

**Pull request merged**
