### PR TITLE
Do not change modality when switching browser tab in useFocusVisible

### PR DESCRIPTION
**Pull request by BartoszGamza**
Closes  #1813 

Added tab switch tracking with the help of `document.visbilityState`. If user leaves the tab, the visibility changes to `hidden` and when comes back its `visible` (again). Im tracking both states if they occurred in aforementioned order and then resetting it after each case when meeting the criteria: `handleFocusEvent()` with `hasEventBeforeFocus` set to `false` which fires when regaining focus on the tab.

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

It's easily replicable with `docs` of interactions/useFocusVisible. You can see a gif I prepared in the issue and compare it.

## 🧢 Your Project:

https://www.livechat.com/

### CODE REVIEW

**Review by snowystinger — COMMENTED** [review]
It does appear to be working in storybook, just pulled it down locally and tried it out with a mouse.
Any chance you'd be willing to write some tests for it as well?
You should be able to fix the CLA failure if you follow instructions here https://react-spectrum.adobe.com/contribute.html#contributor-license-agreement

**Comment by BartoszGamza** [comment]
@snowystinger Thanks for your feedback! I've added tests and signed CLA, would you mind taking a look again?

**Review by snowystinger — CHANGES_REQUESTED** [review]
Spent some more time on this today, it looks like it's working in Chrome only. Firefox is not doing the right thing (surprising) and Safari is not doing it right (unsurprising based on https://caniuse.com/?search=visibilitychange )
iOS Safari seems to be working correctly, but it looks like that was already the case.

I also noticed that there are two other values that might be on `document.visibilityState`, I think we probably need to ignore them in handleVisibilityChange? https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

On a side note, there are a lot of lint errors here, could you run `yarn lint` and address them? I'm not sure why the PR didn't run it automatically

**Comment by BartoszGamza** [comment]
Thanks again for checking @snowystinger , I've checked that again and indeed browser beahvious vary alot in this case. Chrome is the most stable example - it fires focus events only after visibilitychange event so my initial approach worked perfectly fine for the case. Firefox and Safari are a bit wild however, I noticed the following:
- both Firefox and Safari fire focus events before visibilitychange after returning to the tab which is a bit surprising since they actually lie about tab not being visible at the moment of focus.
- Safari also fires additional focus events after visibilitychange on returning to tab which essentially makes the resetting logic much harder

I've managed to fix this though by extending the condition so that it does not matter if browser's visibilityState is visible as long as it switched to hidden in some place in time. It sounds like it could be just treated with single boolean value but Chrome still needs its stable values and I didn't want to mix the focus handler with visibility change handler (so that visibility would only set negative value and focus would set not-confirmed-by-browser-just-yet 'visible' value plus it wouldn't work with Safari's additional focus events) 

On the lint issues, pardon the mess, I've fixed it. There is actually prettier in the project but it seems not configured (?). Adding a [pre-commit hook](https://prettier.io/docs/en/precommit.html) could additionally help a lot in maintaining that at ease 👍

**Comment by snowystinger** [comment]
Thanks, I'll take a look later today hopefully.

Just to quickly answer your question about prettier, we use it for code block formatting in our documentation site so it renders nicely in small screens, we don't use it for developers in the repo yet. It's been something we've thought about adding, but haven't gotten around to/haven't spent the time trying it out yet. As for the pre-commit hook, lint takes a couple minutes to run at the moment, so we didn't want it there either. We only expect it to be addressed when ready for review. I agree there is still much that can be improved on this front. :)

**Review by snowystinger — APPROVED** [review]
I've tested it out in FF/Safari/Chrome on Mac and Safari on iOS, it's working for me in all of them now.

Unfortunately it's not specified the order in which the events are run https://www.w3.org/TR/page-visibility/#h-reacting-to-visibilitychange-changes but this is probably a good thing to file a bug for. I think I expect it to work the way that chrome does. I've filed bugs against Safari and FF https://bugs.webkit.org/show_bug.cgi?id=225265 & https://bugzilla.mozilla.org/show_bug.cgi?id=1708864

**Pull request merged**
