### PR TITLE
Export Color classes

### LINKED ISSUE #5213: Export Color classes
### Provide a general summary of the feature here

Please export the Color classes from https://github.com/adobe/react-spectrum/blob/main/packages/%40react-stately/color/src/Color.ts so that they can be used for `instanceof` checks etc

### 🤔 Expected Behavior?

Color classes should be importable

### 😯 Current Behavior

Color classes are not importable

### 💁 Possible Solution

You can do something like

```js
const Hsl = parseColor("hsl(0, 0%, 0%)").constructor;
const Color = parseColor("hsl(0, 0%, 0%)").__proto__.__proto__.constructor;
```

but that's nasty.

### 🔦 Context

I can't use the Color classes for `instanceof` checks etc

### 💻 Examples

_No response_

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by reidbarber**
Closes #5213

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Comment by reidbarber** [comment]
> Let's only export the abstract class Color so we don't export all of our implementation details

@snowystinger We currently export the `Color` interface, so I think we would have a namespace collision then? Or should it replace it?

**Comment by snowystinger** [comment]
Unfortunate. We can't replace it as that'd be breaking I think, but we can rename it in the exporting. `export {Color as AColor} from ...` for Abstract Color?  open to other names

**Comment by reidbarber** [comment]
Would it be breaking though? We're exporting the interface as a type, and the abstract Color class implements it.

**Comment by snowystinger** [comment]
Unsure, you'd have to try it out

**Comment by reidbarber** [comment]
@snowystinger Doesn't look like that worked, so I named the export instead

**Comment by devongovett** [comment]
Are we sure we want to export this? The public API is `parseColor` which returns an interface type so that the implementation details are hidden.

**Comment by reidbarber** [comment]
@devongovett Use case was:
> I’m using [zod](https://github.com/colinhacks/zod) for form validation. It would be useful to be able to represent colors directly with the class instead of parsing/formatting to string etc

 https://github.com/adobe/react-spectrum/issues/5213#issuecomment-1751541417

**Review by snowystinger — APPROVED** [review]

**Comment by snowystinger** [comment]
approved for now, can override though if we come up with something better

**Comment by reidbarber** [comment]
After discussing with the team, we don't want to expose this at this time since the color package is still pre-release and there is potential for implementation to change.

**Pull request closed without merging**
