### PR TITLE
fix: resolve bug where onAction is executed multiple times

### PR DESCRIPTION
**Pull request by yajihum**
Closes https://github.com/adobe/react-spectrum/issues/6643

## Menu Component
1. Case of RAC
The following table shows what triggers the onAction passed to Menu or MenuItem

  | Menu only | MenuItem only | Menu and MenuItem
-- | -- | -- | --
item.props |   | ⭕️ | ⭕️
props |   | ⭕️ | ⭕️
menuData | ⭕️ |   |  

- `item.props` and `props` both contain the same onAction passed to the MenuItem, which is the cause of the bug.
- First of all, props.onAction is deprecated, so it is preferable not to use it.
- It is also problematic that when onAction is passed to both Menu and MenuItem, the onAction passed to Menu is not executed

Based on the above, it has been modified so that it executes as follows:

  | Menu only | MenuItem only | Menu and MenuItem
-- | -- | -- | --
item.props |   | ⭕️ | ⭕️
props |   |   |  
menuData | ⭕️ |   | ⭕️

2. Case of react-spectrum
  In `@react-spectrum`'s Menu, the onAction received in the Menu's props was being passed to the MenuItem's props. However, since it can be obtained from menuData, onAction is no longer passed to MenuItem."

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

## 📝 Test Instructions:

I have added tests for Menu as mentioned in the issue, as well as for GridList and ListBox, which are also collection components. There may be other collections with onAction, so please check those as well.

### CODE REVIEW

**Review by snowystinger — COMMENTED** [review]
I think we can simplify all of this. If we change `useMenu`'s `performAction` to have this logic instead:

```
    if (item?.props?.onAction) {
      item.props.onAction();
    } else if (props.onAction) {
      props.onAction(key);
    }

    if (data.onAction) {
      data.onAction(key);
    }
```

Then we don't need the changes in useMenu stories, any of the React Spectrum components, nor the React Aria component.

Or have I overlooked something?

**Comment by yajihum** [comment]
@snowystinger 

Thank you for your comment!

First, to clarify, as [described in the property explanation](https://github.com/adobe/react-spectrum/blob/81abb2185cb3a9c52a8feaf76a136c64852aea13/packages/%40react-aria/menu/src/useMenuItem.ts#L81), onAction is originally treated as Menu's onAction, but in the example you provided, it changes to be treated as MenuItem's onAction. We need to decide which one to prioritize.

In my case, I prioritized the former and made the correction. However, my perspective might be incorrect as I have only recently started looking at the code.

If we decide to treat it as MenuItem's onAction, it would be best to change it as you suggested. However, in the react-spectrum code, [Menu's onAction is passed as a prop to MenuItem](https://github.com/adobe/react-spectrum/pull/6671/files#diff-436b932d6ca6264e48704fd14948b87daaeeab8f8d2ef431fc6e9314caba9a3dL111), resulting in `props.onAction` and `menuData` being executed twice, causing the same bug. Therefore, a fix is necessary in any case.

**Comment by snowystinger** [comment]
Ah, I see, we pass through onAction to the props of MenuItem even though we should already have access to that value. So we're missing some tests.
I was trying it out locally, I'll go ahead and push the changes I think make sense in a moment.

**Review by snowystinger — APPROVED** [review]

**Review by reidbarber — APPROVED** [review]
LGTM

**Pull request merged**
