### PR TITLE
ListView DnD follow ups 

### LINKED ISSUE #2897: ListView DnD Followup
- [x] Can't perform a drop operation via double tap when using TalkBack
- [x] The drag indicator will flash in and out of view when scrolling on mobile, perhaps delay the appearance?
  -  Maybe remove isPressed and isHovered, spectrum is talking about only showing it on focus, ask for confirmation
- [x] There is an indicator issue with using the keyboard and drag and drop. Goto an item like "Item g", select the drag indicator, press "return", it selects the drag target field, press "return" again to drop. The drag indicator is still selected. Press tab and the "Item a" and "Item g" drag indicators are both selected. "Item a" is actually the one selected. There is another version of this where both the item and the drag and drop indicator are focused at the same time.
- [x] Can start a drag operation on press and hold on a button/menu trigger on android (need to prevent drag when on interactable indicator)
  - Split out into its own issue, issue to be made 
- [x] Using keyboard, go to item 'd', initiate drag. Drop item 'd' on the drop zone. Tab back to the list. Focus goes to first element, item 'a'. Press down arrow, suddenly jump to item 'e'.
- [x] If dnd is enabled for the list, we should make all items select on mouse up, not just for items that are draggable. 
- [x] Drag handle should not have browser or our focus ring on mouse down
- [x] screen reader announcement of rows is weird. "drag item d, select item d, not selected". it should probably only announce the name of the row, not the drag indicator/checkbox. Make it behave like TableView.
  -  covered by https://github.com/adobe/react-spectrum/issues/2946
- [x] NVDA + FF: cannot drop. pressing enter over drop target does nothing. manually switching to forms mode fixes this.
  -  related to outstanding NVDA bug? Add bug to this issue when found 
- [x] NVDA + FF: navigating with arrow keys to checkbox enters browse mode, and then you cannot navigate to anything else
  -  related to outstanding NVDA bug? Add bug to this issue when found
- [x] When I select multiple items, some draggable and some not, with voiceover it tells me that I'm dragging all the selected items. This seems wrong since some of the items aren't draggable.
- [x] Firefox: some row dividers are missing 
  - Unable to reproduce on FF Windows and Mac (97.0.2) (DL)
- [x] Firefox: right blue line on selection is missing
  - Unable to reproduce on FF Windows and Mac (97.0.2) (DL)
- [x] Additionally it seems like the drop operation on mobile doesn't quite recognize multiple item drops the same way like it does in desktop, something to do with writeToDataTransfer from what I can tell. onDrop will have the proper number of items in onDrop's items when performed on desktop but only have one item when performed on mobile (and seemingly combines all the items together instead)? (ANDROID specific?)
  -  known issue, file browser bug 

Not caught during testing but noticed that pageUp/Home/End don't seem to work. Page down seems to work though?

# 🐛 Bug Report 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

### PR DESCRIPTION
**Pull request by LFDanLu**
Closes #2897 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

1. ListView dnd operation should be performable via Android talkback, specifically the drop action
2. Drag indicator should only appear on keyboard focus
3. Announcement made when focusing the drag handle should accurately reflect the number of selected _draggable_ items. It shouldn't include items that are selected but not draggable.
4. The drag preview shouldn't have the drag handle

## 🧢 Your Project:

RSP

### CODE REVIEW

**Review by majornista — DISMISSED** [review]
Both @jnurthen and I tested the drag and drop behavior with Talkback on Android and are experiencing similarly unsuccessful results. 

1. Focusing the visually hidden drag handle button using the Talkback cursor does not cause the drag handle to become visible. It seems that the focus event for the drag handle may not be firing with the Talkback cursor so `showDragHandle` remains false for the ListViewItem.
2. Double tap to activate the drag handle does not seem to fire the `onDragStart` event, and  Talkback does not seem to announce the "Started dragging..." message. Double tap and hold fire the onDragStart event, as perhaps a pass-through gesture, but the "Started dragging..." message does no announce, and even though the drag handle button announces a in the dragging state, there does not seem to be a way to complete the task.
3. With an ListViewItem theoretically selected for dragging, moving the Talkback cursor to the drop target does not highlight the drop target as able to receive a drop action, and double tapping to complete the drop action, does not fire any of the expected events.

**Comment by LFDanLu** [comment]
@majornista @jnurthen 

> Focusing the visually hidden drag handle button using the Talkback cursor does not cause the drag handle to become visible. It seems that the focus event for the drag handle may not be firing with the Talkback cursor so showDragHandle remains false for the ListViewItem.

This one feels tricky since moving the Talkback cursor doesn't actually trigger a modality change in `useFocusVisible` unlike Voiceover. I'm not sure if there is a way for us to detect this Talkback cursor movement without the user actually triggering some kind of interaction via Talkback. I figured the handle not showing up visually wouldn't be a big deal since the Talkback user can get to the button via swiping and gets an announcement of the button's functionality when the cursor lands on it.
 

> Double tap to activate the drag handle does not seem to fire the onDragStart event, and Talkback does not seem to announce the "Started dragging..." message. Double tap and hold fire the onDragStart event, as perhaps a pass-through gesture, but the "Started dragging..." message does no announce, and even though the drag handle button announces a in the dragging state, there does not seem to be a way to complete the task.

What version of Android/Talkback are you on? I'm getting the proper dragStart event and "Started dragging..." message announced upon double tapping the drag handle via Talkback.

> With an ListViewItem theoretically selected for dragging, moving the Talkback cursor to the drop target does not highlight the drop target as able to receive a drop action, and double tapping to complete the drop action, does not fire any of the expected events.

Same question as above, I'm able to complete the drop operation by starting the drag operation via double tapping when focusing a drag handle, swiping to the drop target, then double tapping to complete the drop.

**Comment by majornista** [comment]
> What version of Android/Talkback are you on? I'm getting the proper dragStart event and "Started dragging..." message announced upon double tapping the drag handle via Talkback. I'm on Android 10, Accessibility version 11.5.00.23, Talkback 6.2, seems to be the latest I can get on my phone.
EDIT: Updated to Talkback 12.1, OS is still the same, the interaction mentioned about still works.

I'm on Android 7.1.1, but have Talkback 12.1 and Chrome 100.0.4896.88. @jnurthen is using the latest Talkback and Chrome versions as well.

**Comment by LFDanLu** [comment]
Follow up information: @majornista and I talked and confirmed that Talkback ListView DnD works on certain Android devices (my Samsung S9 phone) but not on other Android devices (non Samsung android tablet and phones). For those devices, it seems to be an issue with the visually hidden styles (clip/clip-path) making it impossible for Talkback to trigger a click event. @majornista found success making the visually hidden element 10px by 10px and is experimenting with other sizes

**Comment by LFDanLu** [comment]
Going to make the VisuallyHidden Talkback issues a followup captured here: https://github.com/adobe/react-spectrum/issues/3047. Out of scope for this PR since it affects all VisuallyHidden components

**Review by snowystinger — APPROVED** [review]
LGTM tested in chrome

matches Mac OS finder behavior in terms of selections and dragging unselected items while there is a selection in place

**Pull request merged**
