### PR TITLE
Fix: Hue Normalization

### PR DESCRIPTION
**Pull request by theMosaad**
Closes https://github.com/adobe/react-spectrum/issues/6202

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

### CODE REVIEW

**Review by snowystinger — COMMENTED** [review]
GET_BUILD

**Comment by snowystinger** [comment]
GET_BUILD

**Review by snowystinger — COMMENTED** [review]
Tried out the ColorWheel, I can get it to fire onChange with both 0 and 360. This seems poor as it could result in an extra/ambiguous render.

Should the color wheel be unambiguous and only fire 0-359? but parsing can handle the 0-360 range?

Screenshot 2024-05-28 at 11 57 19 AM

**Review by snowystinger — APPROVED** [review]

**Comment by yihuiliao** [comment]
GET_BUILD

**Comment by yihuiliao** [comment]
GET_BUILD

**Comment by snowystinger** [comment]
GET_BUILD

**Comment by ktabors** [comment]
> Tried out the ColorWheel, I can get it to fire onChange with both 0 and 360. This seems poor as it could result in an extra/ambiguous render.

I was still able to get a hue value of 360 from an onChange with the latest build. I did it by slowly dragging the handle with a mouse event. I'm not able to get it with keyboard events.
image

**Review by ktabors — APPROVED** [review]

**Pull request merged**
