### PR TITLE
feat: forward styles VirtualizerItem

### PR DESCRIPTION
**Pull request by patrickkuhlmann**
I didn't open a github issue. I need this change as I can't use the className option, but need to add styles.

Kind regards

### CODE REVIEW

**Comment by LFDanLu** [comment]
@patrickkuhlmann Hi, thanks for the PR! Would you mind expanding on your use case here? From my knowledge all of our components handle calling VirtualizerItem directly so I'm guess you are building your own virtualized component using the Virtualizer internals?

**Comment by patrickkuhlmann** [comment]
Yes, happy to help!

I am trying to build a virtualized carousel which needs `scroll-snap-align` on the virtualized item. The carousel is exported as library and it would be a challenge to pass styles via the class.

**Comment by LFDanLu** [comment]
I see, so this addition of the style prop isn't to support user provided styling (aka a possibly large, unknown set of styles) but more for a style specific to the implementation. I wonder if instead this should be information set on the layout info of a node like how sticky is handled here: https://github.com/adobe/react-spectrum/blob/4980928d36e9e47b51fbf3f43cba6b3136c55c78/packages/%40react-aria/virtualizer/src/VirtualizerItem.tsx#L73-L83, but hard for me to say without knowing how common use that style may be (definitely feels like we might want this for our own carousel when we get to implementing that). I'll bring it up with the team, if you could share any other details about the rough implementation (mainly around how you've used VirtualizerItem, etc) that would helpful!

**Comment by patrickkuhlmann** [comment]
Oh sure no problem!

I am using `overflow: auto` to force a scrolling context as basis for the carousel. To make this scroll container an actual carousel I'm adding scroll snap points and the possibility to programmatically scroll to put it on other controls. A carousel to me is a scroll container that gave up fine grained control over the scroll position.

Autoplay is just sprinkles on top using the exposed api to control the scroll position. 

Focus behavior is similar to `useSelectableCollection` with allowsTabNavigation just that it knows about slide boundaries and lets you tab after the carousel once you reached the end of the slide.

I'm following aria guidelines listed here [w3.org carousel](https://www.w3.org/WAI/ARIA/apg/patterns/carousel)

Hope that helps!

**Comment by LFDanLu** [comment]
Thank you for the additional information! Apologies for the delay, the team's been busy prepping for another release but will try and get back to you soon. I'll be on PTO for the next week so I'll see if someone can bring this up in one of our meetings in the coming week.

**Review by devongovett — APPROVED** [review]
I think this is fine. We allow className so I don't see any reason we wouldn't allow inline styles too.

**Review by snowystinger — APPROVED** [review]

**Comment by snowystinger** [comment]
Any chance you can sign the CLA? https://react-spectrum.adobe.com/contribute.html#contributor-license-agreement then we can get this merged in.

Thanks for the PR!

**Comment by patrickkuhlmann** [comment]
Thanks for having me, no worries!

Agreement signed & submitted.

**Pull request merged**
