### PR TITLE
ActionBar docs updates

### PR DESCRIPTION
**Pull request by devongovett**
General example simplification and wording updates. Also fixed the fonts in the anatomy diagram.

### CODE REVIEW

**Comment by ktabors** [comment]
Kyle bot docs https://reactspectrum.blob.core.windows.net/reactspectrum/be518d20cf20c044b2bfcab0cfdc513346a7daa4/docs/index.html

**Review by reidbarber — DISMISSED** [review]

**Review by ktabors — APPROVED** [review]
LGTM - Why were all the ActionBar examples with `items` removed?

**Comment by devongovett** [comment]
Not all of them, the one under content still has dynamic items. I was generally trying to reduce the number of lines though.

**Review by LFDanLu — APPROVED** [review]
LGTM on desktop and mobile

**Pull request merged**
