### PR TITLE
Implement scroll anchoring for overlay positioning

### LINKED ISSUE #3944: Selected item is not scrolled into view when listbox is opened
# 🐛 Bug Report 
I have built a select component and selected listbox item is not scrolled into the view when listbox is opened. 

## 🤔 Expected Behavior

Selected element should scroll into view when listbox is opened.

## 😯 Current Behavior

As noted by @LFDanLu [here](https://github.com/adobe/react-spectrum/issues/3910#issuecomment-1399145162), this issue occurs when a listbox height is more than the available viewport height and an explicit height is not set for the listbox container.

## 💁 Possible Solution
Looks like the listbox height is calculated as if there's no scroll (like it's not resized) thus the item is considered already in view. Having this in my `ListBoxOption` component seems to workaround the issue for now:
```ts
const onResize = () => {
  if (isSelected && isFocused) {
    scrollIntoView(
      listBoxRef.current as HTMLUListElement,
      domRef.current as HTMLLIElement
    );
  }
};

useResizeObserver({
  ref: listBoxRef as RefObject<HTMLUListElement>,
  onResize: onResize,
});
```

## 🔦 Context

Selected item should scroll into view for a proper UX.

## 💻 Code Sample

Here's a link that shows the issue https://codesandbox.io/s/adoring-microservice-uwylx2

You can test by clicking the select button a few times. When the listbox is opened for the first time, the selected item is scrolled into view properly but on consecutive clicks the list remains scrolled to top.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | |
| Browser          | Chrome 109 |
| Operating System | MacOS |

### PR DESCRIPTION
**Pull request by devongovett**
Closes https://github.com/orgs/adobe/projects/19/views/4?pane=issue&itemId=63064435

I think this fixes #3944 as well.

When an overlay repositions, its height might change, causing the focused item to go out of view. Even if the height didn't change, this might occur because we change the max-height before positioning in order to get the correct intrinsic size. This causes the browser to lose the previous scroll position. This happens during auto focus as well, when focusing happens prior to positioning.

This PR implements scroll anchoring. We save the offset of the focused element from the scroll container before positioning, and adjust the scroll position afterward so that it appears to remain in the same place relative to the viewport, even if the height of the scroll container changed.

**Test instructions**:

1. Open Picker story
2. resize the window to be small and select an item at the bottom
3. re-open the picker. Should scroll the auto focused item into view
4. Resize the height of the browser window. Focused item should remain anchored in view.
5. Repeat the same steps with RAC Select many items story.

### CODE REVIEW

**Comment by snowystinger** [comment]
I'm not getting the item scrolled into view for https://reactspectrum.blob.core.windows.net/reactspectrum/a7d75fc6e8e32b6fcf1997a4fa15138c2f5e9bee/storybook/index.html?path=/story/picker--dynamic-sections&providerSwitcher-express=false
Steps:
1. Open picker
2. Select Ross
3. Close picker
4. Open picker
  1. observe Ross is not scrolled into view

**Comment by devongovett** [comment]
hmm this looks like a different problem with ListLayout not including the persisted key...

**Comment by devongovett** [comment]
@snowystinger added a commit to address it. Needed to clean up some old layout infos that should have been removed when we relayout from scratch (when Picker re-opens) so that we don't think the persisted keys are available when they are not.

**Comment by snowystinger** [comment]
> @snowystinger added a commit to address it. Needed to clean up some old layout infos that should have been removed when we relayout from scratch (when Picker re-opens) so that we don't think the persisted keys are available when they are not.

It doesn't appear to have fixed it, in Chrome MacOS. Happy to help debug tomorrow.

The scroll anchoring seems to help, but I think it can jitter sometimes because we constantly flip the overlay to see if it can fit better one way or the other.

**Comment by devongovett** [comment]
hmm it's working for me...

**Comment by majornista** [comment]
This doesn't seem to work after selecting of a long item below the fold in stories like: https://reactspectrum.blob.core.windows.net/reactspectrum/c7e714598a3ba3093990ec8b053fe06c063ee2f3/storybook/index.html?path=/story/picker--long-item-text&providerSwitcher-express=false or https://reactspectrum.blob.core.windows.net/reactspectrum/c7e714598a3ba3093990ec8b053fe06c063ee2f3/storybook/index.html?path=/story/picker--long-item-text&providerSwitcher-express=false, and focus does not seem to go to the open listbox.

**Review by LFDanLu — APPROVED** [review]
I think this is fine to go in for now since its an big improvement on the current behavior on main where things aren't scrolling into view at all

**Review by snowystinger — DISMISSED** [review]

**Review by snowystinger — DISMISSED** [review]

**Review by ktabors — DISMISSED** [review]
This improvement seems great.

**Review by snowystinger — APPROVED** [review]

**Pull request merged**
