### PR TITLE
Fix two unavailable menu dialogs from being open

### PR DESCRIPTION
**Pull request by snowystinger**
Closes 

Found in testing. This prevents interaction with the trigger that opened the sub dialog in the first place. This also has the benefit of keeping the menu open when clicking the item which was previously noted as an oddity that the dialog would close and then reopen.

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Review by ktabors — COMMENTED** [review]
Still able to reproduce the error of two open context menus.

**Comment by snowystinger** [comment]
> Still able to reproduce the error of two open context menus.

how? I can't anymore. steps I'm using are
1. Open menu
2. mouse over an unavailable item
3. click that item
4. arrow key down

I'm not seeing anything happen when I click the item and it's not giving focus to the trigger item, so arrow keys do nothing as well.

**Comment by reidbarber** [comment]
I can still reproduce as well:

1. Open the first submenu via keyboard
2. Mouse hover over that same menu item
3. Arrow down and open the other one via keyboard

Screenshot 2023-05-03 at 10 24 18 AM

**Review by ktabors — APPROVED** [review]
No longer able to get two context menus to open.

**Review by reidbarber — APPROVED** [review]
LGTM

**Pull request merged**
