### PR TITLE
Fix resize indicator for RTL

### PR DESCRIPTION
**Pull request by snowystinger**
Closes 

Found in testing

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Review by reidbarber — APPROVED** [review]
LGTM. I think we need to fix the padding of `.spectrum-Table-headCellButton` too, but outside the scope of this PR.

**Comment by snowystinger** [comment]
I think that has more to do with an LTR language when we're in RTL, if we change the headers to 

> LGTM. I think we need to fix the padding of `.spectrum-Table-headCellButton` too, but outside the scope of this PR.

good call, easy enough to fix. i had originally thought it was due to us not having any examples with hebrew text, but that wasn't it, it was the padding shortcut property

**Review by reidbarber — DISMISSED** [review]

**Review by ktabors — COMMENTED** [review]
This looks correct, but there appears to be an issue you switch locales. That isn't a real usecase so I'm assuming me ignore.

I resized a couple columns, switched to RTL, starting to resize my first column via the dropdown and this happened.
image

I tried to reproduce it via loading a story in RTL, but couldn't. I started switching locales and resizing and saw the following. 
image

**Review by ktabors — DISMISSED** [review]

**Comment by snowystinger** [comment]
@ktabors can you provide more details to reproduce what you're seeing? I am unable to reproduce it

**Review by reidbarber — APPROVED** [review]

**Review by LFDanLu — APPROVED** [review]

**Pull request merged**
