### PR TITLE
fix(@react-aria/dnd): add support for SSR

### PR DESCRIPTION
**Pull request by Dev-CasperTheGhost**
Closes 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding issue: #3615.
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.

## 📝 Test Instructions:

Directly edited the `node_modules` with this fix.

## 🧢 Your Project:

[codesandbox](https://codesandbox.io/p/github/Dev-CasperTheGhost/ssr-react-aia-dnd/draft/vibrant-panna?file=%2Fpages%2Findex.tsx&workspace=%257B%2522activeFileId%2522%253A%2522cl919iryl0001lth02pdr8kfm%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522key%2522%253A%2522cl919jg4p00dd2a693g23ejjq%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl919j0l800at2a69d26hgkd5%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl919iz7f007f2a693uck8yfr%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

### CODE REVIEW

**Comment by Dev-CasperTheGhost** [comment]
Tests passed now 👍

**Review by reidbarber — APPROVED** [review]
Thanks!

**Review by snowystinger — APPROVED** [review]

**Comment by reidbarber** [comment]
Hey @Dev-CasperTheGhost if you don't mind updating your branch, we can get it merged in. Thanks!

**Comment by Dev-CasperTheGhost** [comment]
@reidbarber branch updated :)!

**Pull request merged**
