### PR TITLE
Fix: SelectStateOptions is not exported in .d.ts

### PR DESCRIPTION
**Pull request by LosYear**
Closes https://github.com/adobe/react-spectrum/issues/4460

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Comment by reidbarber** [comment]
GET_BUILD

**Review by reidbarber — APPROVED** [review]
Thanks!

**Review by LFDanLu — APPROVED** [review]
Thanks for the fix!

**Comment by LFDanLu** [comment]
Not sure why the CLA check is stuck, gonna close and reopen

**Comment by LFDanLu** [comment]
Gonna close+reopen one more time to try and get the CLA status

**Comment by snowystinger** [comment]
Don't know why the CLA is stuck, I'm going to open this as a complete new PR and I'll close this one after

**Pull request closed without merging**
