### PR TITLE
Improve tree shaking

### LINKED ISSUE #1669: Revisit bundling strategy
We currently build all files in each package into two dist files: an ESM version and a CommonJS version. This has the advantage that it prevents users from accessing internal functions that we didn't mean to expose (e.g. `import 'foo/dist/private.js'`), but has the disadvantage that tree shaking is less effective. This is because the `sideEffects: false` option in package.json only applies on the file level, and we bundle all files into one. See #1378 for some discussion about this.

We should consider splitting these out and not bundling all files together. The [exports](https://nodejs.org/api/packages.html#packages_package_entry_points) field in package.json could potentially be used to prevent unintended access to private modules, but only if actually implemented by tools (e.g. Parcel doesn't currently support it). It's also possible that we could bundle some packages and not others, or do some smarter bundling strategy where modules that are only imported from one other file are bundled together, but publicly accessible files are separate entry points. We could also allow accessing certain sub-paths via the `exports` field, e.g. `import '@react-aria/interactions/usePress'` and treat these as entry points into the graph.

### LINKED ISSUE #5798: Incompatible with chunking, large initial bundle sizes
### Provide a general summary of the issue here

When using a multi-chunk app (as suggested for client performance), **all** react-aria's components will always be entirely packaged into the first chunk that loads **any one** of them.  
Since this is generally the root chunk, it bloats it up significantly if eg. the root only needs one component, but the rest of the app uses all of them.

This is tangentially related to #5639 (might be same root cause?) but different "result".

### 🤔 Expected Behavior?

When using react-aria modules in a multi-chunk app, the initial chunk should only include components it needs.

### 😯 Current Behavior

All components of an entire package are included into the first chunk.

### 💁 Possible Solution

It's quite simple underneath really - since all of the submodules in eg. `react-aria-components` are pre-compiled/bundled into a single `dist/import.mjs` file, there is no way this can work in any bundler, since AFAIK no bundler cuts up modules into smaller chunks. (confirmed with at least Vite, esbuild & rollup)

Tree-shaking of course "works", but has no significant effect once you start using a large portion of the components.

The solution is to **not** pre-bundle everything into `import.mjs`, but instead compile every component (ie. file) into a a corresponding separate `<component>.mjs` file, and then make `import.mjs` re-export them.

Bundlers AFAIK _do_ see through this "simple" indirection and can then distribute the components into appropriate chunks.

### 🖥️ Steps to Reproduce

The bundle visualizer results in #5639 demonstrate this (the giant `import.mjs` blobs), although this is more relevant for react-aria-components, since it only uses a single npm module, while the others at least are divided into `@react-aria/*` subpackages.

### Version

react-aria-components 1.0.1

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #5798, closes #1669

This uses the new `@parcel/bundler-library` plugin (https://github.com/parcel-bundler/parcel/pull/9489) to build our packages for publishing to npm. This outputs many more files into the dist directory (one per input file) rather than bundling into a single dist file. That way, tree shaking is much more effective when consuming our libraries due to the `sideEffects` field in package.json, which allows a bundler to remove an entire file when nothing it it is used. Without this we rely on the minifier to analyze this which is difficult and more error prone.

This mostly improves react-aria-components, which contains many components in a single package, rather than in individual packages. One example app I tested locally got 4x smaller after this change, and no longer included large things like drag and drop and table even when they weren't used.

### CODE REVIEW

**Comment by devongovett** [comment]
Devonbot:

Verdaccio builds:
      [CRA Test App](https://reactspectrum.blob.core.windows.net/reactspectrum/423baa72c3d7ae87197217d08179999f990d0acd/verdaccio/build/index.html)
      [NextJS Test App](https://reactspectrum.blob.core.windows.net/reactspectrum/423baa72c3d7ae87197217d08179999f990d0acd/verdaccio/next/index.html)
      [RAC Tailwind Example](https://reactspectrum.blob.core.windows.net/reactspectrum/423baa72c3d7ae87197217d08179999f990d0acd/verdaccio/rac-tailwind/index.html)
      [RAC Spectrum + Tailwind Example](https://reactspectrum.blob.core.windows.net/reactspectrum/423baa72c3d7ae87197217d08179999f990d0acd/verdaccio/rac-spectrum-tailwind/index.html)
      [CRA Test App Size](https://reactspectrum.blob.core.windows.net/reactspectrum/423baa72c3d7ae87197217d08179999f990d0acd/verdaccio/publish-stats/build-stats.txt)
      [NextJS App Size](https://reactspectrum.blob.core.windows.net/reactspectrum/423baa72c3d7ae87197217d08179999f990d0acd/verdaccio/publish-stats/next-build-stats.txt)
      [Publish stats](https://reactspectrum.blob.core.windows.net/reactspectrum/423baa72c3d7ae87197217d08179999f990d0acd/verdaccio/publish-stats/publish.json)
      [Size diff since last release](https://reactspectrum.blob.core.windows.net/reactspectrum/423baa72c3d7ae87197217d08179999f990d0acd/verdaccio/publish-stats/size-diff.txt)
      [Docs](https://reactspectrum.blob.core.windows.net/reactspectrum/423baa72c3d7ae87197217d08179999f990d0acd/verdaccio/docs/index.html)
      [Storybook](https://reactspectrum.blob.core.windows.net/reactspectrum/423baa72c3d7ae87197217d08179999f990d0acd/storybook/index.html)

**Review by snowystinger — APPROVED** [review]

**Review by LFDanLu — COMMENTED** [review]
The built example apps seem to work just fine still, is there a particular app configuration/setup that would easily demonstrate the build size improvement? I tried with my own nextJS/vite app locally w/ verdaccio locally but didn't see much of a difference in the build size but my test apps are quite simple

**Comment by devongovett** [comment]
It would mainly affect RAC since RSP is already split per component (in multiple packages). Since RAC is only a monopackage, that's where you'd see a difference.

**Comment by LFDanLu** [comment]
Right, I pulled in just RAC TableView + Button into those test apps thinking the bundle size prior to building verdaccio on this branch would be dramatically larger since it would be pulling in everything (?) but they were still pretty similar before and after :/

**Comment by devongovett** [comment]
@LFDanLu Depends how many components are being used I guess. Looking at the RAC + tailwind example, the [version from this branch](https://reactspectrum.blob.core.windows.net/reactspectrum/423baa72c3d7ae87197217d08179999f990d0acd/verdaccio/rac-tailwind/index.html) downloads 652kb vs 708kb on [main](https://reactspectrum.blob.core.windows.net/reactspectrum/9412e3cc88eac64430546734c21f2c1e0d701270/verdaccio/rac-tailwind/index.html). Inspecting the JS code you can see that for example the dnd hooks are no longer included in this version for example. But since it uses many of the components there's less of a difference than in a simpler app with only a few components.

**Comment by devongovett** [comment]
The RAC Spectrum + Tailwind example shows a much bigger difference since it only uses a few components: 892kb on [main](https://reactspectrum.blob.core.windows.net/reactspectrum/9412e3cc88eac64430546734c21f2c1e0d701270/verdaccio/rac-spectrum-tailwind/index.html) vs 245kb [on this pr](https://reactspectrum.blob.core.windows.net/reactspectrum/423baa72c3d7ae87197217d08179999f990d0acd/verdaccio/rac-spectrum-tailwind/index.html)

**Review by LFDanLu — APPROVED** [review]
Thanks for the links, verified the differences in the sources JS, LGTM.

**Pull request merged**
