### PR TITLE
fix(ActionBar): Inconsistency in ActionGroup buttons display between …

### PR DESCRIPTION
**Pull request by adnicolae**
…Firefox and Chrome

Closes [#5254](https://github.com/adobe/react-spectrum/issues/5254)

Due to browser-specific sub-pixel rendering and rounding, the `offsetWidth` of the container element was different between Chrome and Firefox for this case, but the `computedSize` of ActionGroup actions was similar, thus triggering the ActionGroup responsiveness (hiding the labels due to actions width computed to be larger than the container width).

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:
Using the following actions within `actionbar/stories/Example.tsx`: 
```js 
<Item key="edit" textValue="Edit">
    <Edit size="S" />
    <Text>Bearbeiten</Text>
</Item>
<Item key="loschen" textValue="Delete">
    <Delete size="S" />
    <Text>Löschen</Text>
</Item>
<Item key="dataadd" textValue="DataAdd">
    <DataAdd size="S" />
    <Text>Datenansicht erstellen</Text>
</Item>
```

Open the storybook in Chrome and Firefox, all 3 buttons and labels should be displayed when there is enough space in the viewport in both browsers. 

## 🧢 Your Project:

Adobe/Analytics

### CODE REVIEW

**Comment by yihuiliao** [comment]
Thanks for the PR? Could you sign the CLA? https://react-spectrum.adobe.com/contribute.html#contributor-license-agreement You may need to close the PR and reopen it to get it to take effect

**Comment by reidbarber** [comment]
GET_BUILD

**Review by snowystinger — APPROVED** [review]
I've added a visual regression test which will run against FF and chrome
Thanks for the example and PR!

**Comment by reidbarber** [comment]
GET_BUILD

**Pull request merged**
