### PR TITLE
fix: prevent classname to be overwritten in color swatch component

### LINKED ISSUE #6583: ColorSwatch does not apply UNSAFE_className
### Provide a general summary of the issue here

Using `ColorSwatch`, I want to give it a border, but it is not applied, no matter what I do 😅 

### 🤔 Expected Behavior?

Given this code:

```typescript
    <ColorSwatchPicker>
      {colors.map((color) => (
        <ColorSwatch
          key={color}
          color={color}
          UNSAFE_className="border border-black/10" // < does not work
        />
      ))}
    </ColorSwatchPicker>
```

### 😯 Current Behavior

no border showing

### 💁 Possible Solution

I checked the component source code, but to me it seems that `className` is [applied after using `useStyleProps`](https://github.com/adobe/react-spectrum/blob/2fd87d9f1d894e6b00a595cce73c6e8828029132/packages/%40react-spectrum/color/src/ColorSwatch.tsx#L64-L87) so maybe it gets overwritten?

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

Paste code above with list of some color codes and try to apply `UNSAFE_className`

### Version

3.35.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### If other, please specify.

_No response_

### What operating system are you using?

macOS

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by CHE1RON**
Closes #6583

### CODE REVIEW

**Comment by CHE1RON** [comment]
Not sure I did it right @snowystinger, but the failing test seems to be coming from somewhere else .. ?

**Comment by reidbarber** [comment]
It looks like lint is just failing because the imports need to be sorted.

**Comment by CHE1RON** [comment]
Thanks for reminding me, I committed again but now I don't know what the linter wants me to do 😅

**Comment by yihuiliao** [comment]
Pushed up a couple of fixes for the lint, hope you don't mind! Thanks for the PR :))

**Review by snowystinger — APPROVED** [review]

**Comment by CHE1RON** [comment]
@yihuiliao thanks very much! it's my first contribution to the project, but I'm picking things up fast 😅

**Review by yihuiliao — APPROVED** [review]

**Comment by CHE1RON** [comment]
Thanks everyone!

**Pull request merged**
