### PR TITLE
Genericize `useFocus()` for narrowed event handler types

### PR DESCRIPTION
**Pull request by imhoffd**
Builds on top of https://github.com/adobe/react-spectrum/pull/4039 to provide narrowed types for the event handlers and `focusProps` of `useFocus()` by adding a generic parameter for the focusable element.

Before:

```ts
const { focusProps } = useFocus({
  onFocus: (event) => {
    // typeof event = FocusEvent<Element>
  },
})

// typeof focusProps = DOMAttributes<FocusableElement>
```

After:

```ts
const { focusProps } = useFocus<HTMLInputElement>({
  onFocus: (event) => {
    // typeof event = FocusEvent<HTMLInputElement>
  },
})

// typeof focusProps = DOMAttributes<HTMLInputElement>
```

### CODE REVIEW

**Comment by snowystinger** [comment]
Closing and reopening to try to kick off the pipeline

**Comment by imhoffd** [comment]
@snowystinger Can you kick it again?

**Comment by imhoffd** [comment]
It looks like the docs are failing to build:
> parcel-optimizer-ssg: Cannot read properties of undefined (reading 'properties')

Is this an issue on my end?

**Comment by LFDanLu** [comment]
Seems so, I reran the build and it failed for the same reason so it doesn't seem to be one of our occasional flaky build results. I'll have to dig further as to why it is failing, I'm guessing our docs type processor is having trouble resolving the types changes when generating the docs prop tables/interfaces?

**Review by LFDanLu — APPROVED** [review]
LGTM, docs render with the expected types and confirmed the typing of useFocus with and without a type param provided

**Review by snowystinger — APPROVED** [review]

**Pull request merged**
