### PR TITLE
Expose `shouldCloseOnInteractOutside` on Modal / ModalOverlay

### PR DESCRIPTION
**Pull request by sookmax**
Closes https://github.com/adobe/react-spectrum/issues/5916

In addition to the fix, I updated how `Pick<>` TS type is handled in `DocsPackager.js`. 

In particular, the condition that [I wrote last time](https://github.com/adobe/react-spectrum/pull/5316/commits/9c5ac925951cd6810d92d8ba96a156b7d44ef21e#diff-ea18fe8150ebc7897b4f4ec1e895cbd1fe6863f1a9f614d7d4d6addc117a6ba8R143) to avoid some side effects (i.e., `if (application[0]?.type === 'application')`) was preventing the correct parsing of `Pick<>` when the expression doesn't involve generics (e.g., when the condition is present, something like `Pick<AriaOverlayProps, 'shouldCloseOnInteractOutside'>` wouldn't work whereas something like `Pick<DatePickerStateOptions<T>, 'shouldCloseOnSelect'>` would).

So by removing the aforementioned condition, a side effect such as the one described in the comment would come to life again unfortunately. I couldn't find a way to distinguish and process differently for such a case.

Without that condition it's the same as how `Omit<>` is processed. And yes, I checked `Omit<>` also suffers from the same side effects.

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

### Stories
* http://localhost:9003/?path=/story/react-aria-components--modal-interaction-outside-example&providerSwitcher-express=false&strict=true
* http://localhost:9003/?path=/story/react-aria-components--modal-interaction-outside-default-overlay-example&providerSwitcher-express=false&strict=true

### Docs
* http://localhost:1234/react-aria/Modal.html#props

### CODE REVIEW

**Comment by snowystinger** [comment]
GET_BUILD

**Review by snowystinger — APPROVED** [review]
thanks for submitting!

**Review by LFDanLu — APPROVED** [review]
LGTM, thanks! We can try to dig into making the docs types processer better for the Pick as a followup

**Comment by sookmax** [comment]
@LFDanLu I'm not so sure if we can distinguish the case where we need the literal `Pick<>` from the case where we want to merge the `Pick<>` (most of the use cases) in the current docs-processing structure. I even tried to use one of the JS doc's tag `@constant` to label the literal `Pick<>` in the comment and process them differently, but failed to make it work 😭.

But maybe there's a way that I'm not aware of, and I'm all for correcting this docs-processing issue, so let me know if I can be of any help achieving that!

**Pull request merged**
