### PR TITLE
Fix #1177: Use delay value if passed in as prop

### LINKED ISSUE #1177: useTooltipTriggerState always uses constant TOOLTIP_DELAY as opposed to the `delay` value passed as prop
# 🐛 Bug Report 

The `delay` prop in `useTooltipTriggerState` can't be used to control the delay for showing the tooltip, instead a constant is always used. Please see: https://github.com/adobe/react-spectrum/blob/423d56867ad76a320537f4e3e127ed7b26c13b58/packages/%40react-stately/tooltip/src/useTooltipTriggerState.ts#L103

However, passing a `delay` value of 0 will work, since it causes the hook to not call the `warmupTooltip` routine, thus displaying the tooltip immediately. 

## 🤔 Expected Behavior

Expected `delay` prop to be used to control the delay of showing the tooltip for other values than 0

## 😯 Current Behavior

`delay` is effectively ignored and a constant 1500ms is always used for delaying showing the tooltip

## 💁 Possible Solution

Change to use the passed in `delay` in the `setTimeout` call, e.g:

```
if (!isOpen && !globalWarmUpTimeout && !globalWarmedUp) {
  globalWarmUpTimeout = setTimeout(() => {
    globalWarmUpTimeout = null;
    globalWarmedUp = true;
    showTooltip();
  }, delay);
}
```

## 🔦 Context

I want tooltips to show with a delay of 500ms instead of 1500ms

## 💻 Code Sample

https://github.com/adobe/react-spectrum/blob/423d56867ad76a320537f4e3e127ed7b26c13b58/packages/%40react-stately/tooltip/src/useTooltipTriggerState.ts#L103

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

Visly

### PR DESCRIPTION
**Pull request by johnjacobkenny**
Closes #1177

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Comment by dannify** [comment]
Thanks for the fix!

**Review by dannify — DISMISSED** [review]

**Comment by johnjacobkenny** [comment]
@dannify I rebased because of updates in upstream and I didn't know it would mark your review as stale ☹ Should I merge next time?

**Comment by dannify** [comment]
Nope, it's all good. I can't merge just yet as we are in the middle of a release but I wanted to approve so it can go in when we are done. I'll merge it today or Monday. Thanks!

**Comment by snowystinger** [comment]
Would you mind adding these two tests? if you don't have time before this is merged, don't worry about it, I can follow up
```
  describe('custom delay', () => {
    it('opens immediately for focus',  () => {
      let {getByRole, getByLabelText} = render(
        <Provider theme={theme}>
          <TooltipTrigger onOpenChange={onOpenChange} delay={350}>
            <ActionButton aria-label="trigger" />
            <Tooltip>Helpful information.</Tooltip>
          </TooltipTrigger>
        </Provider>
      );

      let button = getByLabelText('trigger');
      act(() => {
        button.focus();
      });
      expect(onOpenChange).toHaveBeenCalled();
      let tooltip = getByRole('tooltip');
      expect(tooltip).toBeVisible();
      act(() => {
        button.blur();
      });
      expect(onOpenChange).toHaveBeenCalledWith(false);
      act(() => {
        jest.advanceTimersByTime(CLOSE_TIME);
      });
      expect(tooltip).not.toBeInTheDocument();
    });

    it('opens for hover',  () => {
      let {getByRole, getByLabelText} = render(
        <Provider theme={theme}>
          <TooltipTrigger onOpenChange={onOpenChange} delay={350}>
            <ActionButton aria-label="trigger" />
            <Tooltip>Helpful information.</Tooltip>
          </TooltipTrigger>
        </Provider>
      );
      fireEvent.mouseDown(document.body);
      fireEvent.mouseUp(document.body);

      let button = getByLabelText('trigger');
      fireEvent.mouseEnter(button);
      fireEvent.mouseMove(button);
      expect(onOpenChange).not.toHaveBeenCalled();
      expect(() => getByRole('tooltip')).toThrow();
      // run half way through the timers and see if it's appeared
      act(() => {jest.advanceTimersByTime(350 / 2);});
      expect(onOpenChange).not.toHaveBeenCalled();
      expect(() => getByRole('tooltip')).toThrow();
      // finish the full amount of time, now it should be visible, note this is still way before the default opening time
      act(() => {jest.advanceTimersByTime(350 / 2);});
      expect(onOpenChange).toHaveBeenCalledWith(true);
      let tooltip = getByRole('tooltip');
      expect(tooltip).toBeVisible();
      fireEvent.mouseLeave(button);
      expect(onOpenChange).toHaveBeenCalledWith(false);
      act(() => {
        jest.advanceTimersByTime(CLOSE_TIME);
      });
      expect(tooltip).not.toBeInTheDocument();
    });
  });
```

**Comment by johnjacobkenny** [comment]
@snowystinger I would love to continue in contributing and learning from you. However I am relatively new to the codebase and still finding my way around it. Here are my observations.

I looked in the original package location and couldn't find the test for this. Then I did a search using VS Code and found this file [packages/@react-spectrum/tooltip/test/TooltipTrigger.test.js](https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/tooltip/test/TooltipTrigger.test.js). **1. Is this the right file?**

In the file I see two places where the test for _'opens for hover'_ is included ([L82](https://github.com/adobe/react-spectrum/blob/879cbbdd5031a8d6ac4e91272c8e73d7dd38b0c9/packages/%40react-spectrum/tooltip/test/TooltipTrigger.test.js#L82), [L371](https://github.com/adobe/react-spectrum/blob/879cbbdd5031a8d6ac4e91272c8e73d7dd38b0c9/packages/%40react-spectrum/tooltip/test/TooltipTrigger.test.js#L371)). **2. Should I be replacing one of those, or simply adding this one?**

You have mentioned the value 350 in a few places. [At the top of the test file](https://github.com/adobe/react-spectrum/blob/879cbbdd5031a8d6ac4e91272c8e73d7dd38b0c9/packages/%40react-spectrum/tooltip/test/TooltipTrigger.test.js#L25), there is a variable `let CLOSE_TIME = 350`. **3. Should this variable be used instead?**

Thank you for giving me the chance to work with all you awesome people! :heart:

**Comment by snowystinger** [comment]
Yep, that's the right file.

You should be adding this as two completely new tests in a new describe block, you can add it right before this block https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/tooltip/test/TooltipTrigger.test.js#L534

This 350 value is arbitrary, no reason to turn it into a variable, you could change it to 250 or anything else, so long as it's not equal to the default and not associated with the variable at the top of the file for close time. If you felt like it you could add tests for when the number is bigger as well, but I think this is enough to catch a potential regression.

I haven't tried running the two tests I wrote on your branch, so if they don't work, your code is probably correct and I just missed something with the tests. Let me know if you run into any issues.

**Comment by johnjacobkenny** [comment]
I have added the tests

**Review by snowystinger — APPROVED** [review]

**Comment by johnjacobkenny** [comment]
Thank you for giving me this chance to contribute! It means a lot ❤️

**Pull request merged**
