### PR TITLE
fix: v3 Accordion borders

### PR DESCRIPTION
**Pull request by reidbarber**
Removes transparent border that was visible when hovering over an item.

Old:
Screenshot 2024-10-29 at 12 43 33 PM

New:
Screenshot 2024-10-29 at 12 48 10 PM

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

### CODE REVIEW

**Comment by yihuiliao** [comment]
Screenshot 2024-10-29 at 3 36 06 PM

The divider under "Shared with you" looks thicker than the rest

**Comment by reidbarber** [comment]
@yihuiliao Good catch! Updated.

**Comment by yihuiliao** [comment]
Screenshot 2024-10-29 at 5 05 59 PM

Oh another thing, same story as before, but it looks the disclosure panel is missing some padding on top. Seems to be only in the story with the disabled disclosure

**Comment by reidbarber** [comment]
@yihuiliao Yeah, since the other stories have a `<p>`, they have padding built in. I guess this wasn't as visible when we didn't have a hover state. I adjusted it to have equal padding on all sides, which seems fine.

**Comment by LFDanLu** [comment]
I'm updating the chromatic on main, will run against this branch after

**Comment by LFDanLu** [comment]
Chromatics from main if you wanna double check the accordion stories: 
https://www.chromatic.com/build?appId=5f0dd5ad2b5fc10022a2e320&number=817 (the accordions increased in height which I think is intended)
https://www.chromatic.com/build?appId=651b502f6b74abaae4ee734c&number=43 (forced colors one has extra thick border, will see if it is fixed by this PR)

**Comment by reidbarber** [comment]
@LFDanLu IMO equal padding on all sides seems better. I like the current value, but I'm happy to update it. We could try to better match the S2 values.

**Review by snowystinger — APPROVED** [review]
Do we need to run chromatic again?

**Comment by reidbarber** [comment]
Just ran https://www.chromatic.com/build?appId=5f0dd5ad2b5fc10022a2e320&number=820

**Pull request merged**
