### PR TITLE
Change word in @internationalized/number readme

### PR DESCRIPTION
**Pull request by o-az**
Great set of tools. Thank you

Arab: person, ethno-linguistic category
Arabic: language

Closes 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

### CODE REVIEW

**Review by snowystinger — APPROVED** [review]
Thanks for the PR!

**Comment by snowystinger** [comment]
could you sign the CLA? you may need to close and reopen the PR after doing that
https://react-spectrum.adobe.com/contribute.html#contributor-license-agreement

**Review by yihuiliao — APPROVED** [review]

**Comment by yihuiliao** [comment]
closing due to inactivity — i've opened a pr with your changes here https://github.com/adobe/react-spectrum/pull/6321

**Comment by o-az** [comment]
> closing due to inactivity — i've opened a pr with your changes here https://github.com/adobe/react-spectrum/pull/6321

Thank you

**Pull request closed without merging**
