### PR TITLE
docs(@internationalized): replace quote symbols with html entities

### PR DESCRIPTION
**Pull request by mikoloism**
replace hardcoded single quote symbols with html entity code
update  `date/docs/Calendar.mdx`

Closes 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [x] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

### CODE REVIEW

**Comment by snowystinger** [comment]
Thanks for the interest, what's the reason behind this change?

**Comment by mikoloism** [comment]
Hi @snowystinger :wave:  and Thank you for your question!

I have to tell you that, the change to replace quotation marks with entity codes in markdown files is intended to enhance the consistency and safety of the rendered HTML output.

even though markdown files are not HTML themselves, they are converted to HTML during rendering. if quotation characters are included directly in the markdown content, they can be converted into raw HTML without proper escaping, which may lead to issues such as malformed HTML or potential security vulnerabilities in the rendered output.

also, in HTML, quotation marks is a reserved character used to denote attribute values. if quotations appears in attribute values or text content without being properly encoded in some browser kit's, it can lead to parsing errors or security issues such as cross-site scripting (XSS) vulnerabilities.

by using simple `&quot;` entity code in the markdown files, we ensure that when they are transformed into HTML, the resulting code is more robust and adheres to best practices for escaping characters. this helps in preventing any unexpected rendering issues or security concerns.

**Comment by snowystinger** [comment]
I'm not sure that the security matters. We're not running anything user created or from a database or from a third party.

We're also not rendering the quotes inside an element tag, so it shouldn't interfere with the reserved usage. I'm not aware of any rendering engine which has a problem with this.

I'm fine to have this go in, I just think it's unnecessary.

You'll need to sign the CLA, then close and reopen the PR https://react-spectrum.adobe.com/contribute.html#contributor-license-agreement

**Comment by reidbarber** [comment]
Thanks for the interest in contributing. If this were rendering incorrectly in any browsers, we would definitely be interested in fixing it, but that doesn't appear to be the case. This is all statically built, so there doesn't appear to be any XSS risks either. To avoid unnecessary changes, we won't be merging this, but thanks for the interest.

**Comment by mikoloism** [comment]
Hi @reidbarber and @snowystinger,

Thank you for your feedback and for taking the time to review my pull request. I appreciate your insights regarding the current state of the project and the rationale behind not merging this change.

I understand that the current implementation is functioning as intended and that there may not be immediate security concerns. My intention was to promote best practices in code consistency and safety, particularly regarding how markdown is rendered to HTML. However, I respect your decision to prioritize the existing codebase and avoid unnecessary changes.

Thank you again for your consideration!

**Pull request closed without merging**
