### PR TITLE
Fix SearchAutocomplete to call onClear

### PR DESCRIPTION
**Pull request by reidbarber**
Closes 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Review by snowystinger — APPROVED** [review]

**Review by LFDanLu — APPROVED** [review]
LGTM. As an aside I noticed that the field doesn't clear when hitting `Esc` but that seems to be pre-existing so can be handled later

**Comment by reidbarber** [comment]
> LGTM. As an aside I noticed that the field doesn't clear when hitting `Esc` but that seems to be pre-existing so can be handled later

Weird, it does for me. Any other steps to reproduce?

**Comment by LFDanLu** [comment]
Ah, I should've clarified: specifically after you've selected an option. I was expecting `Esc` to clear the selected key and empty the input but it seems to reset it back to the selected key's text. A bit odd since clicking the `'x'` clears the key so probably something isn't quite hooked up the same

**Comment by reidbarber** [comment]
Ahh good catch. Yeah, we can handle in a follow-up.

**Pull request merged**
