### PR TITLE
 feat: adding the ability to pass dom attributes to <Item/> in ActionGroup collapsed menu

### PR DESCRIPTION
**Pull request by cgood92**
In ActionGroup, if the menu is collapsed, then it doesn't currently pass along DOM attributes of `<Item/>` to the menu items.

This fixes that.

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Much like the unit test says, if you add a `data-testid="hello"` prop to the `<Item/>` component of an `<ActionGroup/>` that is collapsed, those attributes will now be passed down to the DOM.

## 🧢 Your Project:

Adobe Workfront

### CODE REVIEW

**Review by reidbarber — COMMENTED** [review]
Thanks for the PR! We were planning on doing an audit soon to see if we missed any more of these anywhere. 

Instead of introducing an API addition, I think you should just be able to add

```tsx
let domProps = filterDOMProps(item.props);
```

to `MenuItem.tsx`

Here is a similar PR for ListBox: https://github.com/adobe/react-spectrum/pull/2655

**Comment by cgood92** [comment]
> Thanks for the PR! We were planning on doing an audit soon to see if we missed any more of these anywhere.
> 
> Instead of introducing an API addition, I think you should just be able to add
> 
> ```tsx
> let domProps = filterDOMProps(item.props);
> ```
> 
> to `MenuItem.tsx`
> 
> Here is a similar PR for ListBox: #2655

Thank you for your very quick response.  I hadn't even finished filling out all the PR information for this yet :) You're on top of it.

So, I now see what you are saying.

It seems like `CollectionBuilder` needs to gather props in order for them to be available in MenuItems.

So, in `CollectionBuilder` instead of passing something that contains just `data-*` stuff, you could pass any dom attributes... how does that work when in this whole Menu/Item stuff they do their own `aria-` stuff, and `data-key` stuff, etc?

Sorry, I'm just learning here.

**Comment by cgood92** [comment]
> > Thanks for the PR! We were planning on doing an audit soon to see if we missed any more of these anywhere.
> > Instead of introducing an API addition, I think you should just be able to add
> > ```tsx
> > let domProps = filterDOMProps(item.props);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to `MenuItem.tsx`
> > Here is a similar PR for ListBox: #2655
> 
> Thank you for your very quick response. I hadn't even finished filling out all the PR information for this yet :) You're on top of it.
> 
> So, I now see what you are saying.
> 
> It seems like `CollectionBuilder` needs to gather props in order for them to be available in MenuItems.
> 
> So, in `CollectionBuilder` instead of passing something that contains just `data-*` stuff, you could pass any dom attributes... how does that work when in this whole Menu/Item stuff they do their own `aria-` stuff, and `data-key` stuff, etc?
> 
> Sorry, I'm just learning here.

Never mind, I know what you are saying.  Let me change.

**Comment by cgood92** [comment]
@reidbarber sorry for being so late in responding.  I have taken your suggestion and passing all DOM props now.  I have updated the code, PR description, etc.

Can you please review?

**Review by reidbarber — APPROVED** [review]
LGTM, thanks!!

**Review by LFDanLu — APPROVED** [review]
LGTM, thanks for the PR!

**Comment by cgood92** [comment]
Moved to this PR: https://github.com/adobe/react-spectrum/pull/4499

**Pull request closed without merging**
