### PR TITLE
fix: port placeholder change from spectrum-css

### LINKED ISSUE #2759: Placeholder text contrast incorrect
# 🐛 Bug Report 

Placeholder text is `--spectrum-global-color-gray-600`

it should be `--spectrum-global-color-gray-800`

## 🤔 Expected Behavior

Should meet color contrast ratios - current text does not.

## 🔦 Context

Placeholders currently fail WCAG - this mostly impacts Pickers where placeholder text is commonly used for the unselected value.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

### PR DESCRIPTION
**Pull request by jnurthen**
Closes #2759 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

- Run any page using picker
- Check the color of the text used as the placeholder
- It should be gray-800 colors

### CODE REVIEW

**Review by majornista — DISMISSED** [review]

**Comment by dannify** [comment]
I had the understanding that the placeholder text color was only being updated for Picker and not the other form elements. Placeholders for TextField, Combobox etc. are being deprecated.

**Comment by majornista** [comment]
> I had the understanding that the placeholder text color was only being updated for Picker and not the other form elements. Placeholders for TextField, Combobox etc. are being deprecated.

That placeholder text has been deprecated in React-Spectrum shouldn't mean that the placeholder color in our CSS does not need to be updated to conform to WCAG text contrast requirements. It will take a long time for teams to transition to using HelpText instead of placeholder text, and for this reason, the contrast change should be for TextField, ComboBox etc as well.

**Comment by devongovett** [comment]
I think making the placeholder look like a filled in value is worse than deprecating the placeholder prop (perhaps with a console warning), and letting teams solve this design problem of where to move the placeholder in their UI.

**Comment by carolframpton** [comment]
@devongovett I am confused. Even your Picker examples with help text show a placeholder. This is identified as an issue in the external accessibility review for Microsoft.

image

**Comment by devongovett** [comment]
Yes. Spectrum design changed the placeholder color _only_ for Picker, and not for other components. However, the change in this PR affects all components. If the PR is updated to only affect Picker, it will be merged.

**Review by devongovett — APPROVED** [review]

**Review by snowystinger — APPROVED** [review]

**Comment by devongovett** [comment]
lol @snowystinger you beat me to the merge! I was preparing a followup ticket to deprecate placeholders across the rest of our components: https://github.com/adobe/react-spectrum/issues/2935.

**Pull request merged**
