### PR TITLE
Fix generic issue with SelectAria to follow useSelect<T>

### LINKED ISSUE #3061: Unknown type in useSelect menu props
# 🐛 Bug Report 

The return type of `useSelect<T>` doesn't use the generic argument passed to it, instead using `unknown` for its `menuProps` and forcing a type cast.

## 🤔 Expected Behavior

The return type of `useSelect<T>` should use the generic argument `T` to fill in the `menuProps` generic argument.

## 😯 Current Behavior

The return type of `useSelect<T>` doesn't use the generic argument `T`. Instead, the `menuProps` returned from it is typed as `AriaListBoxOptions<unknown>`.

## 💁 Possible Solution

Use the generic argument `T` passed to `useSelect` inside the `SelectAria` interface. This would cause `SelectAria['menuProps']` to have a type of `AriaListBoxOptions<T>`.

## 🔦 Context

I am trying to spread the props of `useSelect<T>` into a `ListBox` component which has prop `items` defined as `Iterable<T>`. This `items` definition inside the `ListBox` component comes from `@react-types/listbox`'s `ListBoxProps`.

When the `menuProps` returned by `useSelect<T>` are spread into the `ListBox` component, the `items` property contained within the `menuProps` has a type of `Iterable<unknown>`, while the `items` property contained within the `ListBoxProps<T>` has a type of `Iterable<T>`.

I expect here that the `menuProps` returned by `useSelect<T>` should fit into a `ListBoxProps<T>`, if`<T>` is the same.

## 💻 Code Sample

https://codesandbox.io/s/gifted-pine-if2czq?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-types/listbox   | 3.2.4
| @react-aria/select  | 3.5.4
| Browser          | X
| Operating System | X

### PR DESCRIPTION
**Pull request by fitiskin**
Closes #3061

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

You can use same Code Sample from the original issue.

## 🧢 Your Project:

No

### CODE REVIEW

**Review by snowystinger — APPROVED** [review]
lgtm, matches combobox

**Comment by LFDanLu** [comment]
@fitiskin mind closing and reopening this PR again? Not sure why the commit status is stuck...

**Comment by fitiskin** [comment]
I'm sorry. Fixed a problem with the docs build.

**Comment by LFDanLu** [comment]
GET_BUILD

**Review by LFDanLu — APPROVED** [review]
LGTM, thanks for the fix!

**Review by snowystinger — APPROVED** [review]
lgtm

**Pull request merged**
